### ISSUE TITLE
Support the same GraphQL fields as gatsby-transformer-remark

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#1]
`gatsby-mdx` should probably support the same fields as the Gatsby remark plugin.

**Fields**:
- [x] frontmatter (both classic and MDX-style) 
- [x] exerpt
- [x] rawMarkdownBody (rawBody?)
- [x] fileAbsolutePath
- [x] headings
- [x] timeToRead
- [x] tableOfContents
- [x] wordCount

**Comment by avigoldman** [comment]
@ChristopherBiscardi how do you think we should handle the `tableOfContents`? `gatsby-transformer-remark` generates out an html string but that feels wrong for MDX.

**Comment by youngboy** [comment]
How is the status of `toc` field ?

I have implement it my self in https://github.com/youngboy/gatsby-mdx/commit/392b826f8f64c799de83ee63801a4028881a7765

```
// source
# Something if

## Something else

Text.

## Something elsefi

# Something iffi 

// query
{
  allMdx {
    edges {
      node {
        toc
      }
    }
  }
}

// query result
          "node": {
            "toc": {
              "items": [
                {
                  "url": "#something-if",
                  "title": "Something if",
                  "items": [
                    {
                      "url": "#something-else",
                      "title": "Something else"
                    },
                    {
                      "url": "#something-elsefi",
                      "title": "Something elsefi"
                    }
                  ]
                },
                {
                  "url": "#something-iffi",
                  "title": "Something iffi"
                }
              ]
            }
          }
...

```

works for me, still need to consider to pass extra `mdast-util-toc` options or other cases

**Comment by ChristopherBiscardi** [comment]
that's dope @youngboy thanks.

That triggered a thought that maybe we could just allow the passing in of custom mdast utils and expose those as graphql queryable fields too?

**Comment by avigoldman** [comment]
@ChristopherBiscardi seems like we should have an `mdxAst` field and allow people to do what they want with the AST in their own codebase (and add whatever fields they want to with the [`createNodeField`](https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField) action), instead of running extra transformers to add any fields in the mdx plugin.

**Comment by ChristopherBiscardi** [comment]
@avigoldman should probably have an ast field anyway, but that mandates the use of unified + rehype-react or similar to render it on the client side. Someone is almost better off just shipping the raw source and using mdx manually in that case. We could offer a <RenderMDXSource/> component though.

for toc, I think we'll always have it, so it doesn't need to be generalized @youngboy . What you have seems fine for now, I was musing about the possible future mostly.

**Comment by ChristopherBiscardi** [comment]
We had to change the `wordCount` field to `wordCounts` because the object type name conflicts with transformer-remark in the graphql namespace. I wonder if schema stitching would have helped here (what's the status of that? anyone know?)

**Comment by KyleAMathews** [comment]
That's weird there was a name conflict — seems like we should have been able to resolve that another way? GraphQL allows for different types to have fields with the same name.

GraphQL stitching is unrelated (it's for pulling in 3rd party graphql servers). It's merged though https://github.com/gatsbyjs/gatsby/pull/6475

**Comment by KyleAMathews** [comment]
Haha :-D

I'm also trying to recover from jetlag but in London instead of SF — which is why I'm chatting on Github in the wee hours of the morning I guess...

Ok, yeah, so you changed the type name not field name — in core we track every type name and whenever there's duplicates, we auto-add something the end to make GraphQL happy 🤷‍♂️

**Comment by geddski** [comment]
gatsby-transformer-remark also has an `html` field. 

Related: #47

**Comment by avigoldman** [comment]
@ChristopherBiscardi #48 closes out `tableOfContents` and it looks like the discussion on #47 is handles the `html` field. Any reason not to close this out?

**Comment by ChristopherBiscardi** [comment]
not that I know of. Closing it.
