### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by greggb** [ChristopherBiscardi/gatsby-mdx#102]
https://hacktoberfest.digitalocean.com is coming up. If there's any work for first time contributors it would be great to add and label them! It's a great initiative to get folks involved.

**Comment by macklinu** [comment]
I made a Hacktoberfest label 🎃 @ChristopherBiscardi we good to create issues for first time contributors/hacktoberfesters and tag them as we see technical tasks or features needed?

**Comment by ChristopherBiscardi** [comment]
Sounds great :) feel free to create/label issues y'all feel are good for this

**Comment by greggb** [comment]
Thanks!
