### ISSUE TITLE
[docs] add a Webpack alias for the components directory

### ISSUE THREAD

**Issue by macklinu** [ChristopherBiscardi/gatsby-mdx#103]
via https://github.com/ChristopherBiscardi/gatsby-mdx/pull/97#issuecomment-417861262:

> ...an alias for the components directory `$components/Notification<or whatever>`

/cc @greggb 

I think this improvement to the docs component library would be helpful. Not sure what's involved but a PR is welcome!

**Comment by ChristopherBiscardi** [comment]
In the kitchen sink (and contentfuk iirc) example we have this:

```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"]
    }
  });
};
```

Just need to add src/components and put it in the docs example
