### ISSUE TITLE
Expose filter node on GraphQL

### ISSUE THREAD

**Issue by chrisrzhou** [ChristopherBiscardi/gatsby-mdx#105]
Hey there, thank you so much for this awesome plugin!

I'm running into the use case of using multiple instances `gatsby-source-filesystem` to manage my code.  Example:
```
// In your gatsby-config.js
module.exports = {
  plugins: [
    // You can have multiple instances of this plugin
    // to read source nodes from different locations on your
    // filesystem.
    //
    // The following sets up the Jekyll pattern of having a
    // "pages" directory for Markdown files and a "data" directory
    // for `.json`, `.yaml`, `.csv`.
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
  ],
}
```

In my `allMdx` query, I would like to apply a filter on the source name (`data` and `pages`).

With `allMarkdownRemark`, there is a way to filter on the `fileAbsolutePath` (see this [comment](https://github.com/gatsbyjs/gatsby/issues/1634#issuecomment-368304967)). In `allFile` and other similar queries, there are ways to get to this using `sourceInstanceName`.

I wasn't able to find a way to filter on this field in `allMdx` while exploring iGraphQL.  Is there a way to do this and any thoughts on supporting it?

Thank you!

**Comment by ChristopherBiscardi** [comment]
Seems like a useful and important feature to support, especially if the remark transformer is already doing it too. I'll have to do some research on how best to support it :) thanks for filing the issue

**Comment by juice49** [comment]
This was possible before 0.1.3, but I'm not sure if it is now. I'm a GraphQL beginner (:

This worked before:

```GraphQL
allMdx(
  filter: {
    fileAbsolutePath: {
      regex : "\/posts/"
    }
  }
)
```

**Comment by macklinu** [comment]
I wonder if support for this was removed in #84?

**Comment by ChristopherBiscardi** [comment]
`fileAbsolutePath` was removed because you can access it via the `parent` field and that makes more sense (because some MDX types don't have file paths). I don't know how this affects the `filter` functionality. Need to find the source of truth for how gatsby adds that in and see if you can filter on sub-fields.

**Comment by ChristopherBiscardi** [comment]
So you can't subselect on the parent of a node in the filter section of the graphql query, but what you can do is add arbitrary additional fields under the `fields` object, like this in gatsby-nodes.

This code checks that the current node is an MDX node and that it was created from a File parent. If both of those are true, create the `sourceName` field with a value of the file sources `sourceInstanceName`.

```js
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions;

  if (node.internal.type === `Mdx`) {
    const parent = getNode(node.parent);

    if (parent.internal.type === "File") {
      createNodeField({
        name: `sourceName`,
        node,
        value: parent.sourceInstanceName
      });
    }
  }
};
```

You can then query it like this using `eq`, `regex`, etc as usual:

```graphql
{
  allMdx(filter: { fields: { sourceName: { eq: "posts" } } }) {
    edges {
      node {
        id
        fields {
          sourceName
        }
        code {
          scope
        }
      }
    }
  }
}
```

**Comment by ChristopherBiscardi** [comment]
Going to close this for now, since it is possible to achieve the desired behavior. It's possible that we could add the absolutePath functionality back (or add it conditionally in gatsby-mdx's `onCreateNode` when the File is a parent) if it's a common enough use case or we want to go full parity with remark.
