### ISSUE TITLE
[docs] create /contributing page via the repo root's CONTRIBUTING.md

### ISSUE THREAD

**Issue by macklinu** [ChristopherBiscardi/gatsby-mdx#106]
via https://github.com/ChristopherBiscardi/gatsby-mdx/pull/100#issuecomment-417892080

Keep the CONTRIBUTING.md file in the root of the repo, but use `gatsby-source-filesystem` to load it and turn it into a page for the docs site.

**Comment by johno** [comment]
This is now done 🎉.
