### ISSUE TITLE
Error: "Only one default export allowed per module."

### ISSUE THREAD

**Issue by fredrik-sogaard** [ChristopherBiscardi/gatsby-mdx#110]
**Describe the bug**
I'm trying to create a page layout to wrap my MDX files in `page` directory, but get an error saying "Only one default export allowed per module."

**To Reproduce**
I have this in `src/layouts/work.js`:
```
import React from 'react'

export default ({ children }) => (
  <div>
    <h1>My Layout</h1>
    <div>{children}</div>
  </div>
)
```
I have this in `src/pages/work/projectName.js`:
```
import PageLayout from '../../layouts/work';
export default PageLayout

# My first MDX Page
Some awesome content
```

If I inline the layout file in the MDX file, everything works fine and the layout wraps the content:
```
export default ({ children }) => (
  <div>
    <h1>My Layout</h1>
    <div>{children}</div>
  </div>
)

# My first MDX Page
Some awesome content
```

**Screenshots**
Error I'm getting:
![image](https://user-images.githubusercontent.com/764318/45014034-7186cd00-b01d-11e8-8fab-f6059b6ffd4e.png)

**Additional context**
I'm using gatsby-mdx version 0.1.2 and Gatsby version 2 beta.

**Comment by fredrik-sogaard** [comment]
@mdx-js/mdx 0.15.0
@mdx-js/tag 0.15.0
gatsby 2.0.0-rc.6

**Comment by fredrik-sogaard** [comment]
I worked around this by not importing anything in the MDX files and instead used the `defaultLayouts` key in gatsby-config.

**Comment by ChristopherBiscardi** [comment]
@fredrik-sogaard This turns out to be an issue in [MDX itself](https://github.com/mdx-js/mdx/issues/162). It doesn't seem to be considered a bug over there, so you'd have to change the syntax to be a function as such:

```jsx
import PageLayout from '../../layouts/work';
export default ({ children, ...props }) => <PageLayout {...props}>{children}</PageLayout>

# My first MDX Page
Some awesome content
```

We also need to change our documentation to reflect the function vs import/export change.

**Comment by fredrik-sogaard** [comment]
Ah, ok. Should have investigated some more.

**Comment by ChristopherBiscardi** [comment]
Np, thanks for filing an issue :)
