### ISSUE TITLE
Referencing images in MDX files.

### ISSUE THREAD

**Issue by fredrik-sogaard** [ChristopherBiscardi/gatsby-mdx#112]
**Describe the bug**
I'm trying to reference images in MDX files in `/pages` with Markdown: `![](image-file.jpg)`. I've tried several different paths to the image, and added it to both the same directory as the MDX file, the static folder and an images folder in src.

So far I've got it to work by adding the images to `static` and reference them like so; `![](/image-file.jpg)`. This is not ideal I think.

I've tried different things in gatsby-config, and it is currently like this:
```
{
      resolve: 'gatsby-mdx',
      options: {
        defaultLayouts: {
          work: require.resolve('./src/layouts/work.js')
        }
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages/work`, // Image files are in here as well
        name: 'work'
      }
    },
    'gatsby-transformer-sharp',
    'gatsby-remark-copy-linked-files',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 1440,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent'
            }
          }
        ]
      }
```

Is there something I'm missing here?

**Comment by ChristopherBiscardi** [comment]
This works today, but only if you're not using the built-in page creator plugin that operates on src/pages to do it. That plugin doesn't create File or MDX nodes, so the gatsby-remark plugins don't have a gatsby environment and they operate on the parent File nodes (which don't currently exist in the webpack loader) in ways that we have to fake in webpack. #92 might fix this for src/pages, or you can use the [graphql approach](https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages) to creating pages and rendering MDX in the meantime.

**Comment by ChristopherBiscardi** [comment]
#92 was merged and released, you can check out the [using gatsby-remark-images](https://gatsby-mdx.netlify.com/guides/using-gatsby-remark-images) docs page.
