### ISSUE TITLE
Swap htmltojsx for a new library

### ISSUE THREAD

**Issue by simonjoom** [ChristopherBiscardi/gatsby-mdx#113]
hi christopher

I use your plugin with success, (i should to do some hack to last gatsby to make it work else i get some trouble)

but anyway i found a problem when you pass a background image with base64 in the parser:
I found the solution that the problem was from htmltojsx and is described here.
https://github.com/weflex/style-parser/issues/1

Nota htmltojsx is quite outdated and use not the last react,

Waiting answer
thanks

**Comment by ChristopherBiscardi** [comment]
Thanks for filing an issue :) 

I'm going to make this an issue about upgrading to a different library to convert html to jsx. Do you have experience with the [html-to-react](https://github.com/aknuds1/html-to-react) lib you linked? Would you suggest it as a replacement?

**Comment by ChristopherBiscardi** [comment]
As of #190 we no longer use html-to-jsx
