### ISSUE TITLE
[remark] support gatsby-remark plugins that use mutateSource()

### ISSUE THREAD

**Issue by macklinu** [ChristopherBiscardi/gatsby-mdx#118]
**Describe the bug**

I tried to integrate the [gatsby-remark-emoji](https://github.com/Rulikkk/gatsby-remark-emoji) into a gatsby-mdx project recently to replace `:hand:` emoji syntax with its resolved emoji (✋), but nothing seemed to happen when I installed and added this plugin to the gatsby-mdx `options.gatsbyRemarkPlugins` array.

I think this is related to #10 (specifically https://github.com/ChristopherBiscardi/gatsby-mdx/issues/10#issuecomment-415181601), because [gatsby-remark-emoji uses `mutateSource`](https://github.com/Rulikkk/gatsby-remark-emoji/blob/8dd4f880b54e0a83ab2dba924fee58550a570a87/index.js#L9-L22).

**To Reproduce**

(Need to push up a repo to reproduce this issue, but just jotting some things from memory right now)

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-mdx',
      options: { gatsbyRemarkPlugins: [{ resolve: 'gatsby-remark-emoji' }] },
    },
  ],
}
```

```mdx
<!-- src/pages/index.mdx -->

:hand:
```

**Expected behavior**

`:hand:` is replaced with ✋ 

**Screenshots**
N/A

**Additional context**

I noticed we have this function commented out, and figuring out a way to integrate this logic would likely solve the issue I'm reporting.

https://github.com/ChristopherBiscardi/gatsby-mdx/blob/dcbcc1d90eba444bbb981d7bd1c61fee9a6cee7a/packages/gatsby-mdx/gatsby/extend-node-type.js#L36-L63

**Comment by iansu** [comment]
I'm interested in using `gatsby-remark-emoji` with `gatsby-mdx`. Is this something I can help with?

**Comment by rawkode** [comment]
Just hit this problem too :cry:

**Comment by arnaud-deprez** [comment]
> Just hit this problem too 😢

It looks we are right on time, just hit it too 😢

**Comment by rawkode** [comment]
I got around this. Here's a link to my config:

https://github.com/rawkode/modern-life/blob/81dcc43e27f240128906adc9a8cbe51fdcdb9850/gatsby-theme-rawkode/gatsby-config.js#L73
