### ISSUE TITLE
MDX Dependencies

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#12]
Right now we depend on `@mdx-js/loader` and `@mdx-js/mdx` in the [package.json](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/package.json#L8).

I'm thinking it makes sense to require them as peer dependencies like [Gatsby does with React](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L175).

**Comment by ChristopherBiscardi** [comment]
yeah probably

**Comment by ChristopherBiscardi** [comment]
done: https://github.com/ChristopherBiscardi/gatsby-mdx/commit/ce23ec27ba6880527484e947e090f5aaff1805a2
