### ISSUE TITLE
Example component

### ISSUE THREAD

**Issue by jeroenransijn** [ChristopherBiscardi/gatsby-mdx#126]
I want to be able to render examples like in AtlasKit:
![image](https://user-images.githubusercontent.com/564463/45446034-c3b09980-b680-11e8-9119-83a864c75c61.png)

## API

Preferably it would work something like this:

```jsx
<ExampleProvider path="../example.js">
   {({ codeText, component }) => {
      // Build your own example components.
      return (
        <div>
          {component}
          <SyntaxHighlighter codeText={codeText} />
        </div>
      )
   }}
 </ExampleProvider>
```

In the above API you could build your own example and playground components based on the `ExampleProvider`. For example you could build a `Example` component that handles everything for you:

```jsx
<Example path="../example.js" />
```

**Comment by ChristopherBiscardi** [comment]
@avigoldman Can we reuse our scope handling for MDX files to do this?

**Comment by avigoldman** [comment]
If I understand the question correctly, that'd require some changes to how we pull out the scope right now. Currently we pluck the scope when the MDX node is created [extend-node-type.js#L243](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/dcbcc1d90eba444bbb981d7bd1c61fee9a6cee7a/packages/gatsby-mdx/gatsby/extend-node-type.js#L243)

It might make more sense to import the example dependencies inside the MDX file and then simply render them.

**Comment by ChristopherBiscardi** [comment]
This is possible with https://github.com/FormidableLabs/react-live
