### ISSUE TITLE
Publish gatsby-mdx to Gatsby plugin library

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#135]
Currently, you can't find this plugin through the [Gatsby plugin library](https://next.gatsbyjs.org/plugins/).

Documentation for adding it to the library: https://next.gatsbyjs.org/docs/plugin-authoring/#publishing-a-plugin-to-the-library

**Comment by avigoldman** [comment]
Closed by @CanRau in #142 🎉

**Comment by CanRau** [comment]
I guess I could've closed it with my pr right?! like `closes #135`

**Comment by ChristopherBiscardi** [comment]
@CanRau yeah that totally works. There's a few keywords that will get that done -- https://help.github.com/articles/closing-issues-using-keywords/
