### ISSUE TITLE
Global component scope?

### ISSUE THREAD

**Issue by chasemccoy** [ChristopherBiscardi/gatsby-mdx#138]
I know that I can use `MDXProvider` to replace default HTML elements with React components, but I. can't seem to figure out if it's possible to just make some components in scope globally across all MDX pages?

My use case is that I have some components (`Box`, `Text`, `Heading`, etc.) that are used so frequently on every page that's it seems unnecessary to import those each time. Is there some way to make those in scope globally, without mapping them to an HTML element?

**Comment by ChristopherBiscardi** [comment]
we could add an option to the config that was for preloaded scope shared across all MDX files. I was thinking about doing this to have a "shortcodes" replacement like:

```md
# My Video

Check out my awesome video:

<YouTube v="UgDDHi-_fyY" />
```

I imagine it'd look something like:

```js
{
  resolve: 'gatsby-mdx',
  options: {
    preloadedMDXScope: `import YouTube from 'react-youtube';
import { Text } from 'other-place';
`
`
  }
}
```

**Comment by avigoldman** [comment]
Could this be done through Webpack shimming and the `scope` option on the `MDXRenderer`?

**Comment by CanRau** [comment]
I misinterpreted `MDXProvider`s `components` prop as being this but am getting ImageGallery is not defined 🤦‍♂️

**Comment by ChristopherBiscardi** [comment]
React and MDXTag are required. In the next version of gatsby-mdx the renderer imports these and adds them to the scope automatically since they're always required.

Also yeah, if you use MDXRenderer you can provide a `scope` to do this. Maybe we don't need a separate feature for it?

**Comment by buz-zard** [comment]
Though I noticed after I pass something to `scope`, I can no longer use imports in MDX. It seems it somehow overrides the
```
component: componentWithMDXScope(
          path.resolve(__dirname, 'src/templates/PostTemplate.js'),
          node.code.scope
        ),
```

Any way to fix this?

**Comment by ChristopherBiscardi** [comment]
The `scope` completely overrides the scope. If you want to merge a calculated scope with a custom scope, you need to merge that in yourself right now. You can do this by using `gatsby-mdx/context`

```js
import { withMDXScope } from 'gatsby-mdx/context';

const MyWrappedComponent = withMDXScope(props => {
  // const combinedScope = {...props.scope, YouTube}
})
```

**Comment by buz-zard** [comment]
Thanks for the hint, it worked! My MDX template now looks like this:

```
import React from 'react';
import { graphql } from 'gatsby';
import MDXRenderer from 'gatsby-mdx/mdx-renderer';
import { withMDXScope } from 'gatsby-mdx/context';
import YouTube from 'react-youtube';
import Layout from '../components/Layout';

function PostTemplate({ data: { mdx }, pageContext, scope }) {
  return (
    <Layout {...pageContext}>
      <MDXRenderer scope={{ YouTube, ...scope }}>{mdx.code.body}</MDXRenderer>
    </Layout>
  );
}

export default withMDXScope(PostTemplate);


export const pageQuery = graphql`
  query($id: String!) {
    mdx(id: { eq: $id }) {
      id
      code {
        body
      }
    }
  }
`;
```

Maybe such example case could be added to the docs? It might useful for others.

**Comment by ChristopherBiscardi** [comment]
@buz-zard Happy to take a PR to add it to the docs :)

**Comment by ChristopherBiscardi** [comment]
This is documented now, so closing the issue.

**Comment by KyleAMathews** [comment]
I like the idea of global components a lot too. We should be able to auto add imports as well to avoid perf problems.

**Comment by ChristopherBiscardi** [comment]
ok, in that case the suggestion I made earlier should work, but I'm not sure what the obvious name to call it is.


```js
{
  resolve: 'gatsby-mdx',
  options: {
    preloadedMDXScope: `import YouTube from 'react-youtube';
import { Text } from 'other-place';
`
  }
}
```

For "remote mdx" (the kind that gets into createPages, etc) we'd add this code snippet to the scope file in the current implementation, from within `.cache` it'd be transformed by any `loaders.js()`. We'd traverse this for any imported identifiers and export them from the scope file as usual. You could theoretically write any JS you wanted in this snippet but any other valid use case of executing arbitrary code from within the scope file eludes me right now.

In the mdx-loader however, it'd get pre-pended to the full MDX file before being passed into the mdx transformation pipeline.

**Comment by johno** [comment]
I wonder if we should add a `globalImports` option to `@mdx-js/loader` that prepends whatever js is provided to it? Seems like a requested enough feature that doesn't really add any complexity. Obviously this isn't applicable to `gatsby-mdx`, it's more for those using MDX in other contexts that use the loader directly.

**Comment by johno** [comment]
Yeah, that's what I was thinking. Make sure the APIs and terminology align wherever appropriate to keep things easier to go back and forth between MDX use cases.

To throw a possible name into the hat, I kinda like something along the lines of `globalMDXScope`. I like the explicitness of `globalMDXImports`, but technically you could evaluate any JavaScript so "scope" is probably better terminology. Then, `@mdx-js/loader` could use `globalScope` as the config option.

**Comment by ChristopherBiscardi** [comment]
`globalScope` sounds good to me. Technically you can write arbitrary code there but I don't see a valid use case for doing that that isn't defining inline components (aka more scope). It's already inside of gatsby-mdx's options so we can call it `globalScope` here too.

**Comment by jlengstorf** [comment]
Could this be a hookable API?

I'm imagining theme plugins for e.g. shortcodes as the primary use case. For example, if I'm a theme author, presumably my theme has already set up MDX, so I'd want plugins to have a way to do something like this in `gatsby-node.js`:

```js
const MyCustomComponent = require('./src/components/shortcode');

exports.extendMDXScope = ({ scope }) => {
  return { ...scope, MyCustomComponent };
};
```

If we could make the scope composable somehow, that makes life really easy for plugin authors.

**Comment by johno** [comment]
This definitely could, and IMO should, be hookable. I'm currently experimenting a bit with some MDX-based Gatsby themes and was just thinking about how it'd be nice to "inject" components into the scope without having to override a layout.

I think this would work great for being able to compose components into scope that are related to a theme. For example, blog theme might want to introduce a tweet embed that can be explicitly used rather than introducing custom MD syntax:

```jsx
### Some stuff

Some more stuff, here's a related tweet:

<TwitterEmbed url="some-url" />
```

When it comes to global scope I definitely like the explicit nature of passing the component itself rather than a collection of imports, tbh. It's a subtle difference, but one that more easily pushes into the pit of success. Dealing with strings, like a collection of global imports, is much more brittle in the long run.

This also has the benefit of being more customizable down the road by implementing a new TwitterEmbed component and overriding it in userland (assuming the consuming site's hook is run last).

**Comment by ChristopherBiscardi** [comment]
Hmm, my main question is: If we do this hook for MDX, why shouldn't we do this for all plugin options?

```js
onPluginConfig({ pluginName, options }) {
  if(plugin === 'gatsby-mdx') {
    options.globalScope = { ...options.globalScope, MyThing }
  }
  return
}
```

**Comment by jlengstorf** [comment]
@ChristopherBiscardi that would make sense to me. I'd probably push for an ultra-descriptive name, though, like `beforePluginInit` or `onPluginInit`. I don't know if this would create edge cases where we'd need to allow before- and after-init flavors.

@DSchau @pieh are there hidden dragons if we made plugin initialization hookable for all of Gatsby?

**Comment by pieh** [comment]
Just so I understand - this would be way to programatically adjust other plugin's options?

As for dragons ahead:
What about scenarios where plugin deciding how to change other plugin options depend on its own options and there is additional nesting:

```js
// gatsby-plugin-A
exports.onPluginConfig = ({ plugin, options }, thisPluginOptions) => {
  if(plugin === 'gatsby-mdx') {
    options.globalScope = { 
      ...options.globalScope, 
      thisPluginOptions.useAlternativeVariant ? AlternativeMyThing : MyThing 
    }
  }
  return
}

// gatsby-plugin-B
exports.onPluginConfig = ({ plugin, options }) => {
  if(plugin === 'gatsby-plugin-A') {
    options.useAlternativeVariant = true
  }
  return
}
```

Now it depends on order, which is not great - so for this kind of API, plugins would need to declare which plugins they are interested in adjusting config and result of that declaration should be acyclic graph so it can actually be resolved. So I would actually see it more declarative like:
```js
exports.onPluginConfig = ({ changePluginConfig }, thisPluginOptions) => {
  changePluginConfig(`gatsby-mdx`, options => {
    options.globalScope = { 
      ...options.globalScope, 
      thisPluginOptions.useAlternativeVariant ? AlternativeMyThing : MyThing 
    }
    return options
  })
}
```

Another thing to remember that in case of source plugins there can be multiple instances of same source plugin - I could see some potential gotchas with that - for example using multiple themes that each use different `gatsby-source-filesystem` - it might be worth to think a bit about some convention for instance naming so this API could target specific instance of the plugin. Maybe even automatically marking which plugins are declared in what theme (if we don't do that already).

I guess it all depend on use cases for this API - I could also see this potentially being used to add completely new "remark" subplugin which open another edge case where plugin is added mid-api run.

Potentially worth to mention that we do "poor man" memoization of plugin list (that include options) in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-runner-node.js#L172-L174 on the very first gatsby-node api run (which currently is `onPreInit`, but it could change to the proposed new API) - we would need to invalidate that after option change and then update redux `flattenedPlugins` state with updated options - it will potentially work without it if we would mutate same `option` object and might be ok for "experimental" phase to skip this

**Comment by jlengstorf** [comment]
![Here be dragons.](https://36qxd1l7f7y2pa9s2h6gbwi1-wpengine.netdna-ssl.com/wp-content/uploads/2012/10/here-be-dragons.png)

So nothing to it, eh? 😂

**Comment by pieh** [comment]
Those are not especially hard things to solve. Those might not even be issues in practice. It all depend on use cases. I just wanted to mention that API design is hard :D

**Comment by ChristopherBiscardi** [comment]
`globalScope` is on master :) Not super happy with the model of using a string here and hoping we can have the same API between mdx core and gatsby-mdx in the future, but want to ship it so people can play with the concept and give feedback on the core idea.

```js
globalScope: `import { SketchPicker } from 'react-color';

export { Picker: SketchPicker };`
```

and then you can write an mdx file without importing `Picker`

```md
# some MD

<Picker />
```

**Comment by ChristopherBiscardi** [comment]
shipped

**Comment by jlengstorf** [comment]
@ChristopherBiscardi thinking about this a bit, the `export` isn't required, right? That's just to rename the component?

Something I was just thinking about is the idea that we could so something like this:

```
globalScope: {
  Button: './src/components/button.js',
  Picker: {
    path: 'react-color',
    name: '{ SketchPicker as Picker }'
  },
}
```

In the default case, we could do something like:

```
Object.entries(globalScope).map(([ key, pathOrOpts]) => {
  if (typeof pathOrOpts === 'string') {
    return `import ${key} from '${pathOrOpts}'`;
  }

  const { name, path } = pathOrOpts;

  return `import ${name} from '${path}'`;
})
```

That way common use cases are pretty straightforward: I want to make my button available on all MDX pages.

It also adds a pretty straightforward way to specify a bunch of other things:

```
globalScope: {
  icons: {
    path: 'react-icons',
    name: '{ MdHome, MdClose }'
  }
}
```

I don't know. Maybe that's too much abstraction vs. just doing:

```
globalScope: [
  `import Button from './src/components/button.js';`,
  `import { SketchPicker as Picker } from 'react-color';`,
]
```

One benefit would be that paths could be explicit: `path: path.resolve('./src...')`

Am I overthinking this? 😂

**Comment by jlengstorf** [comment]
Still thinking. 😅 

I stole an idea of yours to create a "components" shortcut:

```js
// This is a shortcut so MDX can import components without gross relative paths.
// Example: import { Figure } from '$components';
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"],
      alias: { $components: path.resolve(__dirname, "src/components") }
    }
  });
};
```

Would it be possible to bake in support for this _a la_ component ghosting?

My thinking is something like this:

1. I have `gatsby-mdx` installed
2. `gatsby-mdx` looks for a file at `./src/components/gatsby-mdx-components.js` or something — this is configurable
3. If that file exists, all components it exports are added to the global scope.

So I could just do:

```js
export Button from './button';
export Figure from './figure';
export { SketchPicker as Picker } from 'react-color';
```

This might have to get read in as a string and transformed (e.g. `export` => `import` to work without some kind of gnarly transformation), but I feel like the workflow would be _really_ nice and would feel less magical this way: "My MDX components can use whatever I export from this file."

That seems more like standard code than a string-based argument, even if it's ultimately still handled as a string-based argument. 😄
