### ISSUE TITLE
Default Layout

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#14]
Thoughts on adding in a default layout option for MDX pages to avoid importing and exporting the same layout for all pages?

**Comment by ChristopherBiscardi** [comment]
seems reasonable. We might want a post-mdx loader or to just replace the mdx/loader with our own (it doesn't do much) that detects default exports and sets one if it doesn't exist.

**Comment by avigoldman** [comment]
I'm for an additional loader, instead of replacing the mdx/loader. Seems straightfoward enough.

**Comment by ChristopherBiscardi** [comment]
Thinking that the loader should take a mapping of `internalSourceName` to `absolutePathToLayout`. Something like the following `gatsby-config` (where `name` is the `internalSourceName`).

```js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "posts",
        path: `${__dirname}/content/post/`
      }
    },
    {
      resolve: `gatsby-mdx`,
      options: {
        defaultLayouts: {
          posts: require.resolve('./src/components/blog-post.js')
        }
      }
    }
  ]
};
```

**Comment by ChristopherBiscardi** [comment]
Default layout is implemented, but you can only have one right now.

https://5b582387e39e7c789b755bc1--solicitor-seal-13462.netlify.com/2014/7/4/a-foray-into-haxl-postgresql-simple/ uses it.

**Comment by ChristopherBiscardi** [comment]
(published in 0.0.2)

**Comment by avigoldman** [comment]
What do you think the config should look like for the "main" default when the plugin has support for the different defaults? Maybe `defaultLayouts.default`?

**Comment by ChristopherBiscardi** [comment]
yeah, that's what I'm thinking, although I'm not sure we can get the internalSourceName automatically for pages/*.

**Comment by avigoldman** [comment]
I believe #36 would finish up this work.
