### ISSUE TITLE
Include JSX headings in table of contents field

### ISSUE THREAD

**Issue by chasemccoy** [ChristopherBiscardi/gatsby-mdx#140]
Right now, you can query an MDX node to get a table of contents that is built using the markdown headers in the MDX file. 

It would be really nice if this would also include headers rendered inside of JSX. I have scenarios where I want to put a header inside of a React component, but right now that will break my table of contents because `gatsby-mdx` only picks up Markdown headers.

**Comment by ChristopherBiscardi** [comment]
hmm, I suppose we could accomplish this by rendering out the MDX content in full, converting back to mdast and then running [get-table-of-content](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/utils/get-table-of-content.js) on it. Probably better than what we do today.

**Comment by avigoldman** [comment]
If we are adding the `html` field described in #139, this should be a relatively straightforward change.

**Comment by chasemccoy** [comment]
This is awesome. I know I keep saying this, but this _really is_ the last thing keeping me from shipping mdx integration with my company's new, Gatsby-built design system. Would love to see this added!

**Comment by ChristopherBiscardi** [comment]
Master now has a working `html` field so we can move on this

**Comment by chasemccoy** [comment]
@ChristopherBiscardi Trying to dig in and see if I can make this happen now that the `html` field exists. Looking at this:

https://github.com/ChristopherBiscardi/gatsby-mdx/blob/379090494586c4b25e9ec4a490dfb324f1aad97e/packages/gatsby-mdx/gatsby/extend-node-type.js#L192-L206

The `generateTOC` function expects an `mdast` object. For the sake of simplicity, is there a way to take the contents of the `html` field and convert it back into an `mdast` object so we can use that here?

**Comment by chasemccoy** [comment]
Looks like [there is a utility for going from HAST to MDAST](https://github.com/syntax-tree/hast-util-to-mdast) but I am not sure how to get the HTML string into HAST...

**Comment by ChristopherBiscardi** [comment]
You can use rehype-parse to get hast to mdast

**Comment by ChristopherBiscardi** [comment]
You can use rehype-parse to get from HTML to hast

**Comment by ChristopherBiscardi** [comment]
yeah, it's already [a dependency of mdx](https://github.com/mdx-js/mdx/blob/b4ad28a5acdc7278473cddafdf8abb63cbc9debe/packages/mdx/index.js#L1) and we're not moving away from unified anytime soon (or ever really).

**Comment by ChristopherBiscardi** [comment]
This might be possible in the future due to https://github.com/gatsbyjs/gatsby/pull/13061
