### ISSUE TITLE
gatsbyRemarkPlugins don't pass option to gatsby-remark-images

### ISSUE THREAD

**Issue by PEM--** [ChristopherBiscardi/gatsby-mdx#146]
**Describe the bug**
`gatsbyRemarkPlugins` allows re-using some `gatsby-remark-*`. Unfortunately, for the case of `gatsby-remark-images`, its `options` aren't transmitted. Only its defaults are taken into account.

**To Reproduce**
In ``:
```
  ...
  gatsbyRemarkPlugins: [
    {
      resolve: 'gatsby-remark-images',
      options: {
        maxWidth: 960,
        linkImagesToOriginal: false
      }
    },
    ...
  ]
  ...
```

**Expected behavior**
Image rendered in MDX should not be clickable and their `max-width` size should be `960px`. Instead, they are clickable and have their `max-width` at `650px` which corresponds to defaults option for `gatsby-remark-images`

**Comment by ChristopherBiscardi** [comment]
That's strange that prismjs *does* pass the options and remark-images *doesn't*. We forward the options for both in the [same way](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b558af580ee33d578f026ce1e7cf26fd83d45d4c/packages/gatsby-mdx/utils/get-source-plugins-as-remark-plugins.js#L90)

**Comment by PEM--** [comment]
Dawn, you're right. I was using an exact copy of `gatsby-remark-prismjs`'s defaults without having noticed it. None of the options are passed whatever the plugin could be. I remove the **Additional context** to avoid misleading anyone.

**Comment by ChristopherBiscardi** [comment]
@kruton I think this will be considered a bug on our end. Thanks for investigating and posting a workaround!

The one thing I'm not sure about right now is why the [remark transformer](https://github.com/gatsbyjs/gatsby/blob/92f3790641f2b46f79a422184c6e657506bce6d4/packages/gatsby-transformer-remark/src/extend-node-type.js#L93) uses `plugin.pluginOptions` and it seems to work over there. We want some level of compatibility with the remark transformer on the subject of user visible configuration and APIs, so I want to figure that out first before making the `pluginOptions` -> `options` change.

**Comment by kruton** [comment]
I think the actual place where it uses additional remark plugins is [gatsby-transformer-remark/src/extend-node-type.js line 96-97](https://github.com/gatsbyjs/gatsby/blob/6bcf191a9ed9e9d399e9ebc9753f412cefd17748/packages/gatsby-transformer-remark/src/extend-node-type.js#L96). It looks like:
```javascript
            const [parser, options] = parserPlugin
            remark = remark.use(parser, options)
```

**Comment by kruton** [comment]
Looks like it's in [Gatsby's plugin loader](https://github.com/gatsbyjs/gatsby/blob/a80b81962b8f188db7326616da8efe60dfd0030a/packages/gatsby/src/bootstrap/load-plugins/load.js#L129).

**Comment by rwieruch** [comment]
I tried to replace gatsbyRemarkPlugins with plugins, but I didn't do the trick for me 😄

**Comment by ChristopherBiscardi** [comment]
@rwieruch afaik you'd have to replace `options` with `pluginOptions` in the sub-plugin configuration :) 

```js
gatsbyRemarkPlugins: [{
  resolve: 'whatever-plugin',
  pluginOptions: {}
}]
```

**Comment by rwieruch** [comment]
@ChristopherBiscardi thank you for it! Did you release this already?  So do I assume correctly that in the next version it is as you have mentioned before?

```
gatsbyRemarkPlugins: [{
  resolve: 'whatever-plugin',
  options: {}
}]
```

**Comment by ChristopherBiscardi** [comment]
@rwieruch  It will be in 0.2.0 which I'll try to get out today, but you can test it in the `gatsby-mdx@ci` tag if you want, which should be releasing continuously from CI right now.
