### ISSUE TITLE
feed.js not included into package 0.1.4

### ISSUE THREAD

**Issue by PEM--** [ChristopherBiscardi/gatsby-mdx#147]
**Describe the bug**
When importing `gatsby-mdx/feed`, `gatsby` doesn't compile.

**To Reproduce**
As stated here: https://gatsby-mdx.netlify.com/guides/mdx-with-gatsby-plugin-feed

**Expected behavior**
This file should be exposed: `https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/feed.js`

**Screenshots**
```
> tree -L 1 node_modules/gatsby-mdx/
node_modules/gatsby-mdx/
├── #mdx-renderer.js#
├── README.md
├── component-with-mdx-scope.js
├── context.js
├── gatsby
├── gatsby-node.js
├── index.js
├── loaders
├── mdx-renderer.js
├── node_modules
├── package.json
├── tests
└── utils
```

**Comment by ChristopherBiscardi** [comment]
feed will be published when we release the breaking changes currently in master as 0.2. I'm trying to merge #123 before we do a release. Until then you can copy/paste the [feed.js](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b558af580ee33d578f026ce1e7cf26fd83d45d4c/packages/gatsby-mdx/feed.js) export and use it as an option to gatsby-plugin-feed directly.

**Comment by ChristopherBiscardi** [comment]
This went out in 0.2
