### ISSUE TITLE
HTML to MDAST

### ISSUE THREAD

**Issue by lightstrike** [ChristopherBiscardi/gatsby-mdx#148]
As part of [the effort](https://github.com/gatsbyjs/gatsby/pull/7567) to transform HTML strings from WordPress with React components, it would be really helpful to build a utility to convert HTML to MDAST. From there, a pathway to create rehype plugins or Gatsby remark plugins would open up a lot of possibilities :smile:

**Comment by ChristopherBiscardi** [comment]
@CanRau yeah, but sourcing wordpress content into the MDX pipeline as hast instead of raw markdown (skipping mdPlugins), then letting the plugins/etc run on it and replace rendering of elements with MDXProvider on the other end.
