### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `title`

### ISSUE THREAD

**Issue by johncmunson** [ChristopherBiscardi/gatsby-mdx#153]
**Describe the bug**
Even when the "Using Gatsby Remark Images" guide is followed and you are successfully using images within .mdx, there is still a console warning.

**To Reproduce**
1. `git clone https://github.com/johncmunson/gatsby-mdx-image-test`
2. `npm install`
3. `gatsby develop
4. Navigate to `http://localhost:8000/test/`
5. Open browser console to see error

**Expected behavior**
No console error

**Screenshots**
![screen shot 2018-09-25 at 2 25 07 pm](https://user-images.githubusercontent.com/19480078/46038157-f7071580-c0cf-11e8-9006-86b07e407f37.jpg)

**Comment by ChristopherBiscardi** [comment]
gatsby-remark-images does some manipulation of the title attribute, could be a weird interaction between the images plugin and the html-to-jsx plugin we have (and some mdx updates that happened recently).

**Comment by jlesquembre** [comment]
I'm getting the same error, after updating all the dependencies to the latest version. I don't think is related to the package manager (I'm using `yarn`). I also get a second error that I think is related:
![screenshot](https://user-images.githubusercontent.com/1058504/47851021-a4f49680-ddd7-11e8-8d54-4b74e75a4890.png)
From https://github.com/react-bootstrap/dom-helpers/blob/v3.3.1/src/query/scrollLeft.js

**Comment by stevetweeddale** [comment]
I'm getting this same pair of console errors as well: `Warning: Received `true` for a non-boolean attribute `title` and `GET data:image/png net::ERR_INVALID_URL` from the scrollLeft.js file.

I'm pretty new to react/gatsby, but if anyone can give me a pointer on where might be a good place to start hunting I can have a look.

**Comment by stevetweeddale** [comment]
Just for the record, I've just updated all my packages (I'm using npm) and this issue has gone away for me.
