### ISSUE TITLE
Support for images in locations other that `src/pages`

### ISSUE THREAD

**Issue by johncmunson** [ChristopherBiscardi/gatsby-mdx#154]
**Describe the bug**
The guide "Using Gatsby Remark Images" seems to only work if the images are placed inside of `src/pages`

**To Reproduce**
https://gatsby-mdx.netlify.com/guides/using-gatsby-remark-images

**Expected behavior**
If I move an image inside of `src/images`, I would expect to be able to reference it from an `.mdx` file using `![sample-image](../images/sample-image.jpg)`

**Comment by ChristopherBiscardi** [comment]
did you add a filesystem source to src/images?

**Comment by rwieruch** [comment]
I think I ran into the same thing somehow. I got [this minimal application](https://github.com/rwieruch/gatsby-mdx-blog-starter-project). The images for each blog post are in their respected blog post folders. I don't see the blur effect for the images nor seems passing options such as `linkImagesToOriginal` and `withWebp` to work:

```
    {
      resolve: `gatsby-mdx`,
      options: {
        extensions: ['.mdx', '.md'],
        gatsbyRemarkPlugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 1035,
              sizeByPixelDensity: true,
              linkImagesToOriginal: false,
              withWebp: true
            },
          },
```

Is there anything wrong with the setup in this project?

**Comment by ChristopherBiscardi** [comment]
@johncmunson since your gatsby application has it's images in an images folder I'm assuming you figured this one out and I'm going to close this. The docs use a filesystem source to source the images from src/pages but this can be pointed anywhere, like an images folder.

@rwieruch yeah, that sounds like #146, which it looks like someone posted a nice workaround for in the meantime.

**Comment by johncmunson** [comment]
If @ChristopherBiscardi or anyone else is able to recreate the issue I'm having [here](https://github.com/gatsby-mdx-starter/gatsby-mdx-starter/pull/1), then this issue may need to be reopened

**Comment by johncmunson** [comment]
Update: the fix merely involved switching package managers from npm to yarn. Not everyone uses yarn as their go to package manager, so perhaps a note should be added to the README that yarn is the recommended option (at least until the root cause of this issue is discovered. not sure if it lies in one of the modules, or within npm itself.)
