### ISSUE TITLE
Create starter for @mdx-js/mdx

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#156]
We should have a starter in the @mdx-js/mdx repo like the other platforms.

**Comment by ChristopherBiscardi** [comment]
I think they go in https://github.com/mdx-js/mdx/tree/master/examples

**Comment by johncmunson** [comment]
What are your goals for the starter? I have one here that I would love to get your feedback on.

https://github.com/gatsby-mdx-starter/gatsby-mdx-starter

https://gatsby-mdx-starter.netlify.com/

**Comment by ChristopherBiscardi** [comment]
This one is going to be very very basic. Basically nothing I think, just src/pages support and that's about it. Maybe basic image support, etc too.

**Comment by ChristopherBiscardi** [comment]
There's a basic starter available at https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic
