### ISSUE TITLE
Inconsistencies in babel config used

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#158]
**Describe the bug**
We do babel transforms that don't flow through the normal Gatsby webpack loader in the `componentWithMDXScope`. We don't pull the Gatsby babel config, so it is possible to have an error thrown about some babel config issue even everything is configured correctly.

**To Reproduce**
1. Create a template with a class that uses static properties (.i.e. `state = { initial: "state" }`
2. Create an MDX page using the template with `componentWithMDXScope`
3. The following error will surface.

```

  SyntaxError: unknown: Support for the experimental syntax '  classProperties' isn't currently enabled (197:9):
    195 |
    196 | export default class extends Com  ponent {
  > 197 |   state = {  39m
        |         ^
    198 |     initial: "state"
    199 |   };
    200 |
```

**Additional context**

This will go away in #123 since it no longer hoists the graphql queries the way we do now.

**Comment by ChristopherBiscardi** [comment]
this is super old and no longer relevant as `componentWithMDXScope` no longer exists
