### ISSUE TITLE
gatsby-mdx vs gatsby-plugin-mdx

### ISSUE THREAD

**Issue by falconmick** [ChristopherBiscardi/gatsby-mdx#163]
Hi I am just a bit confused... When I search mdx on the gatsbyjs site I get the gatsby-plugin-mdx, but your is referenced from the mdx repo and is more up to date.

Perhapse some info on why could be in the readme?

**Comment by ChristopherBiscardi** [comment]
If you look at the repo/readme for [gatsby-plugin-mdx](https://github.com/ChristopherBiscardi/gatsby-plugin-mdx) you'll see it's only for v1 and it's not being updated for gatsby v2, while this plugin is being developed with the v2 line. Use this one unless you have a specific need for the other one. We're going to rectify the naming convention with the 1.0 release of this plugin.

**Comment by falconmick** [comment]
Good to hear. This would be unbelievably helpful in the Readme.md

I'm happy to submit a PR with this information in it if you would like?
