### ISSUE TITLE
Custom plugin to change paragraph wrapping images to div or jsx not working

### ISSUE THREAD

**Issue by CanRau** [ChristopherBiscardi/gatsby-mdx#167]
My next try on switching to gatsby-mdx, I've got even closer, almost everything works great so far, except, I'm not getting this little plugin working to change the paragraph parent around images to either a div with a class or better a custom element or jsx so I could provide my component using `<mdxprovider />` but nothing is happening, no changes take place at all -.-

```
const visit = require(`unist-util-visit`)

module.exports = opts => tree =>
  visit(tree, { tagName: `p` }, node => {
    if (node.children.every(isImage)) {
      node.type = `element`
      node.tagName = `div`
    }
  })

const isImage = x => x.type === `element` && x.tagName === `img`
```
also tried `node.type = 'div'`...
added to gatsby-config like so
```
hastPlugins: [
  require(`wrap-images`),
],
```
`console.log`ging works as expected, just the renderer page is not showing any changes at all..images are still wrapped in <p/>

I also tried as `gatsbyRemarkPlugin` (before & after `gatsby-remark-images`), `mdPlugin` and tried different implementations, disabled `gatsby-remark-images` just in case, using `unist-util-visit-parents` & `unist-util-modify-children` without any luck

Maybe It's just too late I don't know but I don't get it and hope someone can point me in the right direction 🙏 

That's my version pre mdx which is messy and maybe not really the best way but works https://gitlab.com/GaiAma/gatsby-remark-wrap-images/blob/master/src/index.js (it's doing a little more)

**Comment by ChristopherBiscardi** [comment]
I recreated this in codesandbox with raw mdx-js/mdx and it seems to work. (the runtime file is just a simple change to pass along the hast plugins).

https://codesandbox.io/s/92oyyqz56p

Going further, this also works for using a custom element and replacing it using MDX components if `node.tagName` is changed to `"my-element"`.

```jsx
 <MDX
        hastPlugins={[wrapImages]}
        components={{
          "my-element": ({ children, ...props }) => <p {...props}>{children}</p>
        }}
      >
```

In MDX core rehype/hastPlugins are always applied *after* remark/mdPlugins and gatsby-mdx works the same way as a result. gatsby-remark-plugins run at the end of the rest of the remark/mdPlugins.

Here's another codesandbox showing how to detect an image as a child of the p tag that is not a direct child -- https://codesandbox.io/s/312jw0p8nm Not being a direct child is interesting because it looks like you're only looking for when every child is an `img`, but also because gatsby-remark-images outputs something like the following html, with multiple layers between the p and the img.

```html
<p>
    <a class="gatsby-resp-image-link" href="/static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-5f1b7.jpg" target="_blank" rel="noopener" style="display: block;">
        <span class="gatsby-resp-image-wrapper" style="position: relative; display: block; max-width: 1035px; margin-left: auto; margin-right: auto;">
            <span class="gatsby-resp-image-background-image" style="padding-bottom: 66.7925%; position: relative; bottom: 0px; left: 0px; background-image: url(&quot;data:image/jpeg&quot;); background-size: cover; display: block;">
                <img class="gatsby-resp-image-image" alt="puppy a" src="/static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-4d160.jpg" srcset="/static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-c1f88.jpg 259w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-cc56d.jpg 518w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-4d160.jpg 1035w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-e8059.jpg 1553w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-37021.jpg 2070w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-cd0ea.jpg 3105w,
                /static/jc-gellidon-714673-unsplash-48aad60da74580e2fdf4aa33ab950578-5f1b7.jpg 4240w" sizes="(max-width: 1035px) 100vw,
                1035px" style="width: 100%;
                height: 100%;
                margin: 0px;
                vertical-align: middle;
                position: absolute;
                top: 0px;
                left: 0px;
                box-shadow: white 0px 0px 0px 400px inset;
                ">
            </span>
        </span>
    </a>
</p>
```

**Comment by CanRau** [comment]
Thanks for your input, just tried it really quick but can't make it work..something seems to prevent the actual change, don't know what I'm missing

That's the code https://github.com/GaiAma/gaiama.org/blob/mdx/gatsby-config.js
I'm using a slightly changed [gatsby-mdx](https://github.com/GaiAma/gaiama.org/blob/mdx/packages/gatsby-mdx/utils/create-mdx-node.js#L27) which allows for different schemas, also a WIP, wanted to present it once proofed, but in this case I'm mentioning it now 😉 

As I said I tried to change the paragraph in various stages, and I think gatsby-remark-images shouldn't affect it as it's only changing the image element itself as far as I understand it

**Comment by ChristopherBiscardi** [comment]
> I think gatsby-remark-images shouldn't affect it as it's only changing the image element itself as far as I understand it

gatsby-remark-images will insert [spans](https://github.com/gatsbyjs/gatsby/blob/fc97f96c214bd83f70d3eb14a7481b4c37fed570/packages/gatsby-remark-images/src/index.js#L173), or [use \<picture>](https://github.com/gatsbyjs/gatsby/blob/fc97f96c214bd83f70d3eb14a7481b4c37fed570/packages/gatsby-remark-images/src/index.js#L147), etc so significantly changes the tags that exist between the wrapper `<p>` tag and the interior `<img>` tag.

---

I *think* I've found the issue though, at least in the master branch. The code paths diverged a bit and two of the ASTs for handling pages created by the gatsby internal page creator plugin are different. I need to do some more testing to make sure.

**Comment by CanRau** [comment]
> gatsby-remark-images will insert spans, or use `<picture>`, etc so significantly changes the tags that exist between the wrapper `<p>` tag and the interior `<img>` tag.

I know, and I might be wrong but I thought it's doing all it's changes on the image node itself, which shouldn't affect the parent right?
And that's why I mentioned the various stages I tried to apply the wrapper, because before gatsby-remark-images runs it's only images and whitespace text nodes and I thought gatsby-remark-images wouldn't mess with the parent so it should be fine..and even adding a class didn't work in neither stage…

---

Hm don't really get what you mean?! Just to make sure, the master branch of GaiAma is gatsby v1 and I refactored a lot in the mdx branch which diverged from the v2 branch…

Thanks for your enthusiasm I really appreciate the ❤️ you put in your baby 🙏

**Comment by ChristopherBiscardi** [comment]
Closing this as we prepare to merge into the gatsby repo
