### ISSUE TITLE
Frontmatter as PageContext

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#17]
What do you think of adding the frontmatter automatically as `pageContext`? That way you could use those values in the GraphQL queries or just render them out in the Layout.

In `pages/index.mdx`
```js
---
title: "My post title"
---

Welcome to my blog.


export default ({ pageContext, children }) => (
  <div>
    <h1>{pageContext.frontmatter.title}</h1>
    {children}
  </div>
)
```

**Comment by ChristopherBiscardi** [comment]
Worth looking into

**Comment by avigoldman** [comment]
We'd have to catch all MDX page creations, delete the page, and re-create it with the additional `pageContext`.

**Comment by avigoldman** [comment]
@KyleAMathews any thoughts on doing this?

**Comment by KyleAMathews** [comment]
Generally we avoid doing this as it potentially adds wasteful data to the page. Making data requirements explicit with graphql queries avoids that. But given frontmatter is human entered so will almost always be small, this could make sense. Also mdx is intended for simplified technical writing so this would also simplify things as generally you wouldn't need graphql. Just add data and use it.

**Comment by avigoldman** [comment]
Ok, sounds like we'll move forward with this!

@rchrdnsh you can add frontmatter in the 2 ways outlined in #6.

**Comment by ChristopherBiscardi** [comment]
@rchrdnsh this gatsby plugin supports a few old-school frontmatter styles as well as (arbitrary) named exports in JS files. Use which ever suits you :) both are queryable through graphql
