### ISSUE TITLE
gatsby mdx: building a blog starter - help needed

### ISSUE THREAD

**Issue by Santhosh114** [ChristopherBiscardi/gatsby-mdx#171]
**Is your feature request related to a problem? Please describe.**
I am trying to follow Biscardi's video titled "gatsby mdx: building a blog starter" but I get an error during compile time like 

```
error UNHANDLED REJECTION
  SyntaxError: Unexpected token (127:4)
  - index.js:3893 _class.raise
    [my-blog-bkup]/[@babel]/parser/lib/index.js:3893:15
```

**Describe the solution you'd like**
It would be great if the starter that was up and running during the video is made available as there are too many modifications done on index, gatsby-config, gatsby-node and blog-post to follow through a video. 

**Describe alternatives you've considered**
The only other way I see myself working around this is to drop the concept of md+jsx and go with creating react components for each of the posts which is bad I guess, please suggest an alternative if you see though, thanks.

**Comment by Santhosh114** [comment]
@ChristopherBiscardi please share with us the gatsby starter that was shown in the demo, thanks!

**Comment by ChristopherBiscardi** [comment]
That video isn't meant as a tutorial (and I don't think it even pans out as a set of followable steps), but is a copy of a livestream I did the first time I built the starter. The code from that stream is [in this commit](https://github.com/ChristopherBiscardi/gatsby-starter-blog/commit/7c106e646a8ab23eec3ea294c98bf665274c29fa) but it's slightly out of date at this point.

I'll update a starter and put a link in the README

**Comment by Santhosh114** [comment]
Thanks a ton @ChristopherBiscardi an official starter would be great to have! Thanks for this amazing project 💯

**Comment by Santhosh114** [comment]
Thanks @KagamiChan , I see your repo with md files and not component import if I am right, I have a working projects that uses mdx over remark using the above mentioned commit but the issue I am having is in the [import component](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/176) section, the module is not able to route to those pointed components. Please let me know if this features is live or if you can take a look.
