### ISSUE TITLE
mdx import returns component not found error 

### ISSUE THREAD

**Issue by Santhosh114** [ChristopherBiscardi/gatsby-mdx#176]
Import statement returns a "Component not defined" error and the following console error points to the following code block from blog-post.js:
`<MDXRenderer scope={this.props.__mdxScope}>
         {post.code.body}
 </MDXRenderer>`

<img width="1477" alt="screen shot 2018-10-12 at 4 50 21 pm" src="https://user-images.githubusercontent.com/14152628/46899242-ca7c2900-ce45-11e8-934d-3f6dd8c1da3f.png">

Please suggest me a workaround while I wait for the official starter, as I see the implementations of @johncmunson 's [starter](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/156) & @silvenon 's [site](https://github.com/silvenon/silvenon.com) very different from starter edit from [commit](https://github.com/ChristopherBiscardi/gatsby-starter-blog/commit/7c106e646a8ab23eec3ea294c98bf665274c29fa) 

Link to my [working repo](https://github.com/Santhosh114/gatsby-mdx-blog/tree/support-mdx) and the [mdx](https://github.com/Santhosh114/gatsby-mdx-blog/blob/support-mdx/content/hello-world/index.mdx) file.

**Comment by Santhosh114** [comment]
Thanks @silvenon , I think my code now isn't locating the component since JSX part is injected into blog-post.js & I am not able to find the relative folder location, I tried both
```js
import Bio from '../../src/components/Bio'          // from content/hello-world/index.mdx
```
& 
```js
import Bio from '../components/Bio'                  // from blog-post.js 
```
Console:
```js
ERROR  Failed to compile with 1 errors                                                                                                                               
This relative module was not found:

* ../components/Bio in ./.cache/gatsby-mdx/mdx-scopes-dir/5491d574bff3285ac7d9fa5ada64e929.js
✖ ｢wdm｣:
ERROR in ./.cache/gatsby-mdx/mdx-scopes-dir/5491d574bff3285ac7d9fa5ada64e929.js
Module not found: Error: Can't resolve '../components/Bio' in '/Users/Santhosh/GitHub/my-blog/.cache/gatsby-mdx/mdx-scopes-dir'
 @ ./.cache/gatsby-mdx/mdx-scopes-dir/5491d574bff3285ac7d9fa5ada64e929.js 7:0-40 11:7-10
 @ ./.cache/gatsby-mdx/mdx-wrappers-dir/fcebfaab053f4c013da0e21d6d89b462--scope-hash-5491d574bff3285ac7d9fa5ada64e929.js
 @ ./.cache/sync-requires.js
 @ ./.cache/root.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ℹ ｢wdm｣: Failed to compile.
```

**Comment by ChristopherBiscardi** [comment]
hey @Santhosh114, there were two issues in the repo. The first is that we don't support relative paths in processed MDX content (because relative paths don't make sense if the MDX content comes from a remote CMS like contentful, etc). This is a simple fix that requires an additional bit of webpack config.

```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    },
  })
}
```

and then changing the import to remove the relative path, instead importing directly from the components folder:

```js
import { Bio } from 'components/Bio'
```

The second is as @silvenon correctly [identified](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/176#issuecomment-429522045). The Bio component had a default export, but the import was looking for a named export.

```js
import Bio from 'components/Bio'
```

Here's a PR with the changes :) https://github.com/Santhosh114/gatsby-mdx-blog/pull/1

**Comment by Santhosh114** [comment]
Thanks for your time @ChristopherBiscardi  :) I assumed gatsby would support inline scripts like Jekyl did for me, mdx is a total lifesaver 🙏
