### ISSUE TITLE
Cypress not working

### ISSUE THREAD

**Issue by LekoArts** [ChristopherBiscardi/gatsby-mdx#177]
**Describe the bug**
I successfully used Cypress with a site using normal remark / MD files. When I switched over to gatsby-mdx the Cypress tests fail with this error:

```
     Uncaught SyntaxError: Unexpected token ...

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
      at Object../node_modules/gatsby-mdx/mdx-renderer.js (http://localhost:8000/commons.js:4828:1)
      at __webpack_require__ (http://localhost:8000/commons.js:725:30)
      at fn (http://localhost:8000/commons.js:102:20)
      at Module.eval (mnt/e/Lennart/Development/GitLab/theia/www/src/templates/doc.jsx:7:81)
      at eval (mnt/e/Lennart/Development/GitLab/theia/www/src/templates/doc.jsx:122:30)
      at Module../src/templates/doc.jsx (http://localhost:8000/commons.js:6442:1)
      at __webpack_require__ (http://localhost:8000/commons.js:725:30)
      at fn (http://localhost:8000/commons.js:102:20)
      at Module.eval (mnt/e/Lennart/Development/GitLab/theia/www/.cache/gatsby-mdx/mdx-wrappers-dir/d603e8620f7aab2d4c33366003a770d0--scope-hash-3010b3badc54a9dfa4a4c80e419a41b2.js:14:123)
      at eval (mnt/e/Lennart/Development/GitLab/theia/www/.cache/gatsby-mdx/mdx-wrappers-dir/d603e8620f7aab2d4c33366003a770d0--scope-hash-3010b3badc54a9dfa4a4c80e419a41b2.js:73:30)
```

**To Reproduce**
Use Cypress

**Expected behavior**
Cypress runs sucessfully

**Additional context**

This issue (https://github.com/cypress-io/cypress/issues/2516) suggests that it's the spread operator Cypress doesn't understand.

**Comment by ChristopherBiscardi** [comment]
It looks like we can set up cypress tests for free since we're open source. Perhaps we should do some simple ones for the kitchen sink example, etc.

**Comment by LeKoArts** [comment]
The Cypress Runner is free for everyone, only the dashboard is a paid feauture.

So the problem seems to be the MDXRenderer — does it get babelified for npm publish?

**Comment by LeKoArts** [comment]
So, when I ran the contents of mdx-renderer [through babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgd2DAFgWQCIA0DCE4EAdgKYkwDOcAvnAGZRFwBEAAiACYAeAtACsqAehgBDAObCuwKjGHd-YZgDdgXMlFYBuAFChIsRCjRY8AZQDGEMGTqNmINgDph1ymR4wdu3Z8PwGgxiAK4ANvCoGDi4VjZkABS6cCbReITE5JRUCQlIVNa2cAC8iLQANHDWmRTUJWWVlujAYVxQFJXOXco2NLQAlCUAfIjJKVWkcozhYXFFpQhj4xM12eVL4z1gVOvLKV3OBfEbtHobwsJVza3tJHCycMpkfNVgLWRccIob7lMA1mQAJ40UoAeQARgIyJYYM4AcCEgwZnMyP09MtfvAVGIwiEyCC4PCqM4QGIwAl4cNpmFZoUyABteEAXTRP0m8AYd1K5GQcAAYiESDDgKQEqwAPqc1idLpEyoAAwAJAgmi02hRaPLWWySFMKJ9Spy8hU4Adsbj8f08itIFlqDLnFs-qzlu0YCEoHd9ei6P1dKygA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=) and insert it into my local node_modules, the Cypress tests will work.

**Comment by LeKoArts** [comment]
Adding this to my `gatsby-node.js` solved the issue:

```JS
exports.onCreateWebpackConfig = ({ stage, actions, loaders, getConfig }) => {
  const config = getConfig();

  config.module.rules = [
    ...config.module.rules.filter(rule => String(rule.test) !== String(/\.jsx?$/)),
    {
      ...loaders.js(),
      test: /\.jsx?$/,
      exclude: modulePath => /node_modules/.test(modulePath) && !/node_modules\/gatsby-mdx/.test(modulePath),
    },
  ];

  actions.replaceWebpackConfig(config);
};
```

Documentation: https://www.gatsbyjs.org/docs/add-custom-webpack-config/#modifying-the-babel-loader

**Comment by LekoArts** [comment]
@ChristopherBiscardi The issue is still relevant, I can't get Cypress working on another project of mine (also with the above gatsby-node solution)

**Comment by LekoArts** [comment]
still relevant i think: https://github.com/LekoArts/gatsby-starter-portfolio-emma

**Comment by johno** [comment]
Will dig in then, thanks!

**Comment by ChristopherBiscardi** [comment]
A bunch has changed since January. Going to close this and if it's still an issue ask for it to be re-opened on the gatsby repo
