### ISSUE TITLE
Support sourcing pages from outside of src/pages

### ISSUE THREAD

**Issue by Vpr99** [ChristopherBiscardi/gatsby-mdx#181]
👋I'm writing a component library and would like to use a different folder structure than the one that Gatsby ships by default:

```
├ dist/          // Compiled lib
├ src/           // Source code for what will be compiled to dist/
└ docs/
  ├ pages/       // MDX files that will be compiled into the documentation
  └ templates/   // Templates for the markdown files
```

Basically, I'd like to source my pages from `docs/pages` instead of `src/pages`.

After some digging, it looks like the default page creator has been [externalized into a plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-page-creator) and I was wondering if it is possible to use this in conjunction with gatsby-mdx?

**Edit**: Looks like this is possible by following [these instructions](https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages) but I'd prefer not to have to fall back on `gatsby-source-filesystem` and `createPage` calls if there's somewhere easier to hook in to.

**Comment by ChristopherBiscardi** [comment]
Yeah, you can set up the pages plugin and it should work. If it doesn't work, file a bug here. The same code we use to support the pages plugin in src/pages should work for any page creator plugin instance although I haven't tried it myself. Though be aware that the page plugin skips gatsby node creation for the filesystem and MDX so you won't be able to query allMdx for any exports or frontmatter, etc.
