### ISSUE TITLE
markdown code blocks containing `export` get modified

### ISSUE THREAD

**Issue by danielberndt** [ChristopherBiscardi/gatsby-mdx#184]
**Describe the bug**

I've got a md snippet like this
```md
  **`index.js`**
  ```jsx
  export {default as Small} from "./Small.js"
  export {default as Big} from "./Big.js"
  `` `
```
(I added a space in the ' `` `' to not confuse github)

This markdown gets rendered like this
```
<code>
export {default as Small} from "./Small.js"
{default as Big} from "./Big.js"
</code>
```

i.e. the last `export` get's removed.

The same happens with 
```
```jsx
export { Small, Big };
`` `
```

I'm not too sure though whether this is an mdx issue or is something that happens within this library.

**Comment by danielberndt** [comment]
As a workaround it seems to work okay if I do

```md
  **`index.js`**
  ```jsx
  /**/export {default as Small} from "./Small.js"
  /**/export {default as Big} from "./Big.js"
  `` `
```

**Comment by ChristopherBiscardi** [comment]
Looks like a gatsby-mdx problem

**Comment by danielhusar** [comment]
Its also broken only for `export` on non first lines. The `export` on first line in code block is preserved.

**Comment by danielhusar** [comment]
Solution for me in meanwhile to to add zero space character before `export`.
You can grab it here: https://codepen.io/chriscoyier/pen/iLKwm

**Comment by ChristopherBiscardi** [comment]
This is being tracked by #212
