### ISSUE TITLE
In-page hash navigation does not set focus

### ISSUE THREAD

**Issue by AlmeroSteyn** [ChristopherBiscardi/gatsby-mdx#185]
**Describe the bug**
When I click an anchor that refers to a location inside the page, the destination element does not receive proper focus. Although the browser scroll position is reset properly, the destination element is not read out by screen readers as it does not receive focus correctly.

**To Reproduce**
1. Clone repository https://github.com/AlmeroSteyn/gatsby-mdx-minimal-repro
1. Go to homepage
1. Click on the link right at the top named `Skip to content`
1. Note how the container below with the text `This is some content` does not get a focus outline.
1. Now go to route `/focus` which is a straight React component without `MDX`.
1. Click on link right at the top named `Skip to content`
1. Note how the container below with text `This is some content` **DOES** get a focus outline on this page.

Both of these pages uses te same `Layout` component that contains the link and in-page navigation destination. When used in an `MDX` file it doesn't work, while using it as a straight page component does work

When I was looking into why this was happening I noticed that on the `MDX` pages the entire content is remounted even when the hash portion of the URL changes. This breaks the standard browser behaviour of setting focus to the target element.

Because focus is not set correctly, screen readers will not announce to the users that any action has been performed.

**Expected behavior**
Navigating to an element with an `id` corresponding to the `hash in the href` of the anchor should set focus on the element to allow screen reader users to also use applications built with `MDX`.

**Comment by AlmeroSteyn** [comment]
Hi. Sorry to do this, know everyone is busy, but will this issue receive attention in the near future? 

Loving the technology and using it in our documentation but as we are an accessibility company this feature is a must have. We are fixing it with quite a nasty hack, but it would be great it if could be part of the solution itself.

**Comment by AlmeroSteyn** [comment]
Thank you!

**Comment by ChristopherBiscardi** [comment]
I was able to fix this by creating a `shouldComponentUpdate` inside [`MDXTag`](https://github.com/mdx-js/mdx/blob/e6a7b03fc7df49de4e05b6ff1bf4d7b693ff39b7/packages/tag/src/mdx-tag.js) (the component that renders all mdx content. This led me to the fact that I think the `wrapper` MDX element is causing the remount.

I added the sCU call to the compiled code so that's why it looks weird here with the key/value stuff.

```js
 {
      key: 'shouldComponentUpdate',
      value: function shouldComponentUpdate(a, b) {
        console.log('scu', a, b)
        return false
      },
    },
```

A more interesting sCU that also works is

```js
 {
      key: 'shouldComponentUpdate',
      value: function shouldComponentUpdate(nextProps) {
        if (
          nextProps.name === 'wrapper' &&
          nextProps.layoutProps.location.hash !==
            this.props.layoutProps.location.hash
        ) {
          return false
        }
        return true
      },
    },
```

---

So I'm pretty confident in saying the re-mounting is happening in MDXTag when it goes to render the `'wrapper'` element.

**Comment by AlmeroSteyn** [comment]
Thanks for coming back on this. 

I was thinking along the same line and would have loved that to work for all cases. BUT...

I added the code above to my project as well and it indeed works to set focus to the container on the first attempt. But once it is written in the browser URL any subsequent clicks on the anchor has no focus effect as the `location.hash` no longer changes. Yet, normally, a browser would set focus repeatedly in such a case.

Also if the hash is in the browser URL and the page is refreshed, it also does not set focus.

I actually have no idea how one would fix this looking the `MDXTag` component. I can't think of how one could stop the update in those cases without breaking the function completely in most other valid render cases.

BUT quite clearly this issue is not part of your package so I am gonna close this and log something on the MDX codebase to see if there is any resolution possible. 

Thank you for looking at this!

**Comment by ChristopherBiscardi** [comment]
This seems to be solved by using

```js
export default Layout
```

instead of

```js
export default ({ children, ...props }) => <Layout {...props}>{children}</Layout>
```

because the second option currently results in an unstable component identity since mdx-js/mdx uses the layout inline in render.
