### ISSUE TITLE
IE11 + Edge issues with MDXRenderer

### ISSUE THREAD

**Issue by craigmcginley** [ChristopherBiscardi/gatsby-mdx#189]
**Describe the bug**
MDXRenderer is throwing errors in IE11 and Edge, related to es-7(?, one of the newer specs anyway) syntax. For some reason Gatsby's polyfill isn't handling this? Not sure what target browser support is here.

**To Reproduce**
Version 0.2.0
You can view these errors in the base [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro).
1.) Visit "page 3" which uses MDXRenderer
2.) Open the JS console and view errors

As you can see the page still renders, but I've run into an issue in my project where it appears the error crashes the script so subsequent JS fails to run.

**Comment by ChristopherBiscardi** [comment]
Looks like it's time to start having a build for MDXRenderer and put it through babel, etc.

**Comment by buz-zard** [comment]
Windows support is critical for me, so what would need to be done to have support for IE? If I had some hints I could dig into this and prepare a MR.

**Comment by ChristopherBiscardi** [comment]
@buz-zard you could run the raw source through the js loaders. I'm thinking about building this into the lib instead of shipping a compiled version of the renderer, then each person's individual site and loader setup would apply to it and compile it down to the appropriate browser support (I [don't really want to bake IE11 support in](https://twitter.com/jamiebuilds/status/1022568918949408768)). I take this approach [with themes](https://github.com/ChristopherBiscardi/gatsby-theme-examples/blob/281fd63802802aef3a57bc796e91c80c6ded49e3/themes/gatsby-theme-blog/gatsby-node.js#L96-L106) so that they don't have to ship pre-compiled code.

**Comment by buz-zard** [comment]
Well it's not IE11 only, it's also the latest Edge..
Nonetheless I tried using the actual [mdx loader](https://github.com/mdx-js/mdx/tree/master/packages/loader) for webpack, integrated it into the gatsby page by looking at this package code for references and resolved the IE & Edge issues.

I'll try to share my findings later.

**Comment by buz-zard** [comment]
I ended up just using `@mdx-js/loader` as intended via their webpack config. 
Also published a simplified package ([gatsby-transformer-mdx](https://www.npmjs.com/package/gatsby-transformer-mdx)) for mdx usage - less features than this package, but I really needed the compatibility first.

**Comment by ChristopherBiscardi** [comment]
@buz-zard I'm not sure if you're aware, but you've basically just copied out functionality that already exists in gatsby-mdx. Check out [this branch](https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic/tree/path-based) and this netlify deployment ([/blog](https://5c197a65ed8214000858cace--gatsby-starter-mdx-basic.netlify.com/blog/) or [/blog/jam-stack-ftw](https://5c197a65ed8214000858cace--gatsby-starter-mdx-basic.netlify.com/blog/jam-stack-ftw)).

The [commit in the mdx-basic repo](https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic/commit/3bfcea30c06a7910e2d16d169ceba828b28318cf) is pretty much verbatim your [example in gatsby-transformer-mdx](https://github.com/buz-zard/gatsby-mdx/blob/1b4fdbcdbe14e8e2a6d44bcbd590a65d13cd7527/demos/programmatic-mdx-pages/gatsby-node.js) (I copy/pasted gatsby-node and removed the filter from the mdx query).

gatsby-mdx supports regular compilation of MDX content in the same way core does. MDXRenderer is supposed to be used for dynamic content, like if you're sourcing content from Contentful, not really if you're sourcing exact files. If you want to avoid the MDXRenderer, you're free to do that with gatsby-mdx.

**Comment by buz-zard** [comment]
@ChristopherBiscardi it looks like it. I was having errors IE and infinite reloads in Edge that were frustrating me (spent a good week on an MVP at work 😅). I copied a bunch repos and was trying to get things to work, when it looks I should have just not used the MdxRenderer. I was under the impression that it was used everywhere.

In the end I was just confused by the docs. I'm sorry, this probably doesn't look nice on your behalf now that I look at the situation.

**Comment by ChristopherBiscardi** [comment]
nah, it's open source :) you're totally free to do whatever you want/need to get your stuff done. I just wanted to make sure you knew it could be accomplished already without a new package.

I added a note to the docs rewrite I'm going through tomorrow (#210) to flesh out the possible ways of using Gatsby+MDX so people can see what the options are and what the tradeoffs are more easily.

**Comment by ChristopherBiscardi** [comment]
the latest master of gatsby-mdx will use your js loaders to compile MDX-Renderer and other utilities. It's release as the `ci` tag right now
