### ISSUE TITLE
Is there a way to consume allMdx code data without creating pages?

### ISSUE THREAD

**Issue by chrisrzhou** [ChristopherBiscardi/gatsby-mdx#191]
Currently there is official good support to create pages in Gatsby by writing `.mdx` files in `src/pages` or programmatically creating pages.

I have a use case, where I do not want to create any pages, but would like to have access to relevant data in the `allMdx` query to create components to be used in non-page components in my codebase.

In the regular `allMarkdownRemark` query, I can make use of `html` or `rawMarkdownBody` to do something later (e.g. pass it to `react-markdown` for renderering)

However, in `allMdx`, I think I only have access to `code.body` and `code.scope`, and I'm not sure how I can pass these two variables to generate react components for rendering.  I tried looking up the codebase, and can find usage of `MDXScopeProvider` and `MDXRenderer` but I'm not sure how to put these pieces together.

Ideally, I want something like this.

```javascript
function MyComponent({data}) {
  const {body, scope} = data.allMdx.edges[0].node.code;
  /const mdxComponent = // do something with body/scope to output JSX
  return (
    <ContentContainer>
      <Card>{mdxComponent}</Card>
    </ContentContainer>
  );
  return <PageLayout header={<SurveyHeader />} content={content} />;
}

export default MyComponent;

export const pageQuery = graphql`
  {
    allMdx(
      filter: {fileAbsolutePath: {regex: "//README.md/"}}
      sort: {order: ASC, fields: [frontmatter___id]}
    ) {
      edges {
        node {
          code {
            body
            scope
          }
        }
      }
    }
  }
`;

Is this achievable somehow?

Thank you so much!

**Comment by ChristopherBiscardi** [comment]
Yes, but you have to provide the scope yourself, if you use a random component in your MDX file the renderer won't automatically know you did. `MDXRenderer` is what you're looking for.


```js
import { MDXTag } from "@mdx-js/tag";
import React from 'react';
import MDXRenderer from 'gatsby-mdx/mdx-renderer';
...
<MDXRenderer scope={{React, MDXTag}}>{node.code}</MDXRenderer>
```
