### ISSUE TITLE
MDXRenderer is incompatible with @mdx-js/mdx v16

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#192]
When we add the build process for the renderer, etc we should also update mdx-renderer to be v16 compatible. Not sure whether this will be breaking for v15 but I think its possible it won't be.

**Comment by falconmick** [comment]
haha yeah this one caught me off guard!

**Comment by ChristopherBiscardi** [comment]
it's 100% my fault too :p I wrote the diff that broke it from @mdx-js/mdx's side 😬

**Comment by ChristopherBiscardi** [comment]
#194 is the PR to watch for this

**Comment by EloD10** [comment]
I've updated from `gatsby-mdx-0.2` to `gatsby-mdx-master` and it works well. Thanks! 👍

**Comment by falconmick** [comment]
@ChristopherBiscardi  Is this able to be closed or does the latest mdx still not jell with this plugin?

**Comment by ChristopherBiscardi** [comment]
ah, nope. this is good on stable release now. thanks!
