### ISSUE TITLE
named queries are not supported

### ISSUE THREAD

**Issue by deltaskelta** [ChristopherBiscardi/gatsby-mdx#203]
**Describe the bug**

Named graphql queries seem to not be supported and cause an error...

```
  query BlogPostQuery($id: String!) {
   ...
  }
```

will cause the error...

```
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named `BlogPostQuery`. GraphQL fragments and roots must have unique names.
    t: Duplicate document named `BlogPostQuery`. GraphQL fragments and roots must have unique names.
```

if the query name is moved to an anonymous query, the problem seems to be resolved. 

**To Reproduce**

[reproduction](https://github.com/deltaskelta/deltaskelta.github.io.src/tree/gatsby-mdx-iss-203) and Steps to reproduce the behavior:

1. `yarn develop`

**Expected behavior**

named queries should work like normal queries

**Additional context**

The reason that I need a named query is that I am using `typescript` and `apollo` to automatically generate type definitions based on the gatsby schema and queries found in files.

**Comment by ChristopherBiscardi** [comment]
Correct, we create a wrapper and pull the query out into the wrapper. There can currently be multiple wrappers depending on differences in scope across mdx files. Since the query name needs to be unique, the current best way to achieve that is to not name the query since gatsby will hash it itself as a result.

The additional context here and repro case is really helpful, thanks.

**Comment by deltaskelta** [comment]
This is pretty dirty, but it works...

```
// pageQuery, etc get hoisted to here
${instance.state.exports.map(exportString => exportString.replace(/query /, 'query Wrapped'))};
```

**Comment by ChristopherBiscardi** [comment]
huh, it'd be interesting if that worked for queries without a name `query { ... }` and scope combinations that result in multiple Wrappers.

**Comment by deltaskelta** [comment]
yeah IDK about all  the possible situations as I am new to this lib, but its working for now until there is a better solution. Do you have any ideas about the way to go about making this work?

**Comment by deltaskelta** [comment]
I am still using my fork with the edit above. I have added a scope to the renderer and it is still working for now. What kind of scope combinations result in multiple wrappers?

**Comment by deltaskelta** [comment]
Does #202 being closed because of no more wrappers fix this too?

**Comment by ChristopherBiscardi** [comment]
uh, yeah actually :D I think it does. Thanks for the ping :)
