### ISSUE TITLE
Mdx pages in Edge result in reload loop

### ISSUE THREAD

**Issue by aptfx** [ChristopherBiscardi/gatsby-mdx#205]
When loading an Mdx based page in Edge the browser gets into an infinite reload loop.

**To Reproduce**

This page reproduces the issue:

https://gatsby-documentation-starter.netlify.com/components/header

**Expected behavior**

Do not reload infinitely

**Additional context**
Could it be that gatsby-mdx does interfere with gatsbys caching logic? It seems that gatsby recognizes a stale cached page by catching the 404 for non-existent chunks and then triggers a non-caching reload.

**Comment by ChristopherBiscardi** [comment]
I don't know why this would happen in Edge and not other browsers, any help you can give on debugging this would be greatly appreciated.

What versions of gatsby, mdx, etc are you using?

**Comment by aptfx** [comment]
gatsby: 2.0.55
gatsby-mdx: 0.2.9
gatsby-plugin-offline: 2.0.17
@mdx-js/mdx: 0.15.7
@mdx-js/tag: 0.16.1

**Comment by ChristopherBiscardi** [comment]
hey @aptfx can you check this with the latest release?

**Comment by aptfx** [comment]
Sorry for the late reply. I updated our system last week. The newest release did indeed fix the reload loop. One thing that is left ist that the generated scopes use object spread syntax (not supported in Edge). I can provide a fix using Object.assign if you want
