### ISSUE TITLE
Gatsby-MDX Image URL

### ISSUE THREAD

**Issue by CraftAtoms** [ChristopherBiscardi/gatsby-mdx#206]
# Description

Hello! I'm having an issue referencing image urls from my markdown files with qraphQL. 

This code will not create create the correct url path for my meta-tags in Helmet:

`
 const imageURL =
      (frontmatter.image && frontmatter.image.publicURL) 
`

### It’s creating the wrong image url

`https://reactviz.holiday/christmas-gifts//static/what-americas-want-f2b01a4ad7a392dd7c9a2c14b5fb9756.png`

### Instead of 

`https://reactviz.holiday/static/what-americas-want-f2b01a4ad7a392dd7c9a2c14b5fb9756.png`

Here is a link to the actual Repo: https://github.com/CraftAtoms/datavizAdvent/blob/master/src/templates/blog-post.js

Any advice would be greatly appreciated.

**Comment by ChristopherBiscardi** [comment]
Are you saying that remark automatically handles the construction of the URL with the pathPrefix for you but that MDX doesn't? [this](https://github.com/gatsbyjs/gatsby/blob/5a08b7640c2db2c65696be56d81afee83b2ca9ec/packages/gatsby-transformer-remark/src/extend-node-type.js#L164-L175) is the only code I see in remark for something like that, but it doesn't look like it applies to frontmatter.

It seems like you're taking an arbitrary string from the frontmatter, which you would need to add the [pathPrefix](https://www.gatsbyjs.org/docs/path-prefix/) to. You can do this yourself without mdx support for it, but I'm still curious about the above question.

**Comment by CraftAtoms** [comment]
Ah I see now, this issue has nothing to with MDX. Thank you for pointing me in the right direction Christopher!

**Comment by ChristopherBiscardi** [comment]
np, closing this then.
