### ISSUE TITLE
Editing frontmatter in `src/pages` doesn't reload page

### ISSUE THREAD

**Issue by danoc** [ChristopherBiscardi/gatsby-mdx#207]
**Describe the bug**

Hi! [This is a known issue](https://github.com/ChristopherBiscardi/gatsby-mdx/pull/56#issue-207779768), but I wanted to know if there are good workarounds. 

The best workaround I can think of is to move my files out of `src/pages/**/.mdx` and programmatically create pages in `gatsby-node.js`. I would then pass in data to `pageContext` (maybe `fileAbsolutePath`) that I can use to run a page query that fetches the frontmatter and supports HMR:

```qraphql
{
  mdx(fileAbsolutePath: {eq: $fileAbsolutePath}) {
    frontmatter {
      title
    }
  }
}
```

Is there a simpler/cleaner solution? I love that I can place `mdx` files in `src/pages` and not have to configure my `gatsby-node.js`.

Here's a possible solution: What if `fileAbsolutePath` were part of the same `pageContext` that `gatsby-mdx` uses to send the frontmatter to layouts? Perhaps I could use the `fileAbsolutePath` context to query `mdx(fileAbsolutePath: {eq: $fileAbsolutePath})` as a page query in my `gatsby-mdx` layout. Would that work without needing to configure `gatsby-node.js`?

**To Reproduce**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by ChristopherBiscardi** [comment]
The content in src/pages doesn't get created as nodes in the gatsby system (the [page creator plugin](https://github.com/gatsbyjs/gatsby/blob/5a08b7640c2db2c65696be56d81afee83b2ca9ec/packages/gatsby-plugin-page-creator/src/gatsby-node.js) acts as it's own source, bypassing the node system), so you wouldn't be able to query `mdx` for any content in src/pages without having an additional gatsby-source-filesystem in gatsby-config pointing at src/pages. (although, I think setting up the gatsby-source-filesystem like this would solve the problem in a way you want more than swapping to fully programmatically created pages).

We *might* be able to do something on the library side with [page dependencies](https://www.gatsbyjs.org/docs/page-node-dependencies/) and the [createPageDependency](https://github.com/gatsbyjs/gatsby/blob/5a08b7640c2db2c65696be56d81afee83b2ca9ec/packages/gatsby/src/redux/actions.js#L779) or [addPageDependency](https://github.com/gatsbyjs/gatsby/blob/5a08b7640c2db2c65696be56d81afee83b2ca9ec/packages/gatsby/src/redux/actions/add-page-dependency.js) calls but I haven't looked into it yet.

**Comment by danoc** [comment]
Ah, interesting.

I actually do have `gatsby-source-filesystem` pointing at `src/pages` so that `gatsby-remark-copy-linked-files` can find images in the MDX files. I'm able to query `mdx` for content in there, but the page `context` doesn't have the data I would need for the `mdx` query.

If the page context included `fileAbsolutePath` (or something that also exists in the MDX node), I could do:

```graphql
query ($fileAbsolutePath: String!) {
  mdx(fileAbsolutePath: {eq: $fileAbsolutePath}) {
    frontmatter {
      title
    }
  }
}
```

I'm not familiar with page dependencies though, so that may be a better solution. 😄

**Comment by ChristopherBiscardi** [comment]
Closing this since the context-updating for a page is a gatsby core issue and `fileAbsolutePath` is part of the Mdx node these days anyway, solving the original issue.
