### ISSUE TITLE
Use same react component to render in HTML and markdown

### ISSUE THREAD

**Issue by ar-stackrox** [ChristopherBiscardi/gatsby-mdx#211]
Hi @ChristopherBiscardi , thanks again for your amazing work! This isn't so much a feature request, but I was wondering if there was a way to allow for a react component like `<Button> hello world </button>` to render in the browser, while also passing that snippet to a code block in markdown (so you can see the real component and its code side by side, for design systems.

example - 
![image](https://user-images.githubusercontent.com/28272783/50196527-4daf7480-02f8-11e9-9ea1-a3c09a1e24a7.png)

I was thinking I could make a variable for the component markup and pass it to something like:

```
'''js
<component here />
'''
```

but I am not sure how... It would be great if I could pass any component into another wrapper component that would figure out how to display the component markup, as well as show the code in a markdown code block that would then get rendered through Prism.

Any ideas are welcome! I'm fairly new to mdx, react, and Gatsby so I have much to learn.

**Comment by ChristopherBiscardi** [comment]
you can do this with an MDXProvider that provides a `pre` or `code` component that applies a lib like [react-live](https://github.com/FormidableLabs/react-live) to the code snippet. I'm updating the docs tomorrow and will include an example of this #210

**Comment by ar-stackrox** [comment]
@ChristopherBiscardi you rock!!!
