### ISSUE TITLE
Improve default export detection

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#212]
https://github.com/mdx-js/mdx/pull/362/files

**Comment by DSchau** [comment]
Whew - this threw me for a loop.

I solved it with a hacky regex (for now):

https://github.com/DSchau/gatsby-drupal-workshop/blob/master/apps/workshop/src/components/mdx/index.js#L23-L25

**Comment by johno** [comment]
Oh yikes, yeah that's not a good time. Hoping this weekend to move export detection in MDX core to babel parsing.

**Comment by DSchau** [comment]
@johno eh, any problem can be worked around. Thanks for being so receptive! `gatsby-mdx` is the _best_.

**Comment by ChristopherBiscardi** [comment]
I believe we merged this in awhile ago and forgot to close this issue
