### ISSUE TITLE
componentWithMDXScope triggers a "non-page component" error for exported GraphQL queries

### ISSUE THREAD

**Issue by jlengstorf** [ChristopherBiscardi/gatsby-mdx#214]
**Describe the bug**
After wrapping a component with `componentWithMDXScope`, like so:

```js
createPage({
  path: '/test',
  component: componentWithMDXScope(
    path.resolve('src/templates/post.js'),
    post.childMdx.code.scope,
  ),
  context: {}
});
```

the following error appears when exporting a query from that component:

```
warning The GraphQL query in the non-page component "/path/to/site/src/templates/post.js" will not be run.
Exported queries are only executed for Page components. Instead of an exported
query, either co-locate a GraphQL fragment and compose that fragment into the
query (or other fragment) of the top-level page that renders this component, or
use a <StaticQuery> in this component. For more info on fragments and
composition, see http://graphql.org/learn/queries/#fragments and for more
information on <StaticQuery>, see https://gatsbyjs.org/docs/static-query
```

This is a false negative though, because the query _is_ executed.

This was already opened and closed in #166, and I know it's not a top priority to fix, but I think it's worth having an open issue to signal that:

1. This is a known issue
2. It does _not_ cause any harm; it's just noise
3. It will be fixed as MDX gets to a stable place

**To Reproduce**
This is present in the existing [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro):
1. Clone the repro and install deps
2. Run `yarn develop`
3. See the "non-page component" error in the console

**Expected behavior**
No errors.

**Comment by ChristopherBiscardi** [comment]
@LekoArts #202 is for `export const query` for page queries (where query can be any identifier). This warning is because we create a wrapper around pages when you use `componentWithMDXScope`. The wrapper hoists the page query, but doesn't remove it from the original page template, so this warning occurs.
