### ISSUE TITLE
Images are missing on direct page loads

### ISSUE THREAD

**Issue by jlengstorf** [ChristopherBiscardi/gatsby-mdx#215]
After building a site, directly loading an MDX page that shows an image results in a dead image.

This is an issue with `gatsby-remark-images` and MDX that somehow results in this snippet:

```
<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;max-width:1380px;margin-left:auto;margin-right:auto"><span class="gatsby-resp-image-background-image" style="padding-bottom: 50%; position: relative; bottom: 0px; left: 0px; background-image: url(&quot;data:image/jpeg;background-size:cover;display:block&quot;); opacity: 0;"></span>
```

This appears to be generated using the `fluid` helper from `gatsby-plugin-sharp`.

This _only_ happens if the page is navigated to directly; clicking from one page to another **does not** cause this issue.

The fact that this only happens on a direct page load maybe points to an issue with SSR?

**Comment by jlengstorf** [comment]
May already be solved by the latest version, per https://github.com/jlengstorf/lengstorf.com/pull/49#issuecomment-449667464

**Comment by dashed** [comment]
I'm kinda facing some weird issues, and am using `gatsby-mdx@ci`, as per https://github.com/jlengstorf/lengstorf.com/pull/54 .

For reference, my config is at https://github.com/dashed/personalsite/blob/ce53979161ceb8c9181e7051f75b691972944cdd/gatsby-config.js

------

For my setup, I'm noticing that it seems that I have to run `yarn develop`, before I can `yarn build` to generate the images properly.

**Comment by ChristopherBiscardi** [comment]
@dashed 

>  it seems that I have to run yarn develop, before I can yarn build

That is definitely odd. Can you try `rm -rf .cache` and then doing a `yarn build` and see if that helps?

**Comment by dashed** [comment]
I didn't want to spend too much time debugging this; so I ended up copying and adapting this component for my needs: https://github.com/jlengstorf/lengstorf.com/blob/b81d12d33cf346e991f5e40e4f5ae6b9f5029ace/src/components/Figure.js 

😅

**Comment by jlengstorf** [comment]
@dashed glad it was helpful!

**Comment by stevetweeddale** [comment]
Updating all my packages to the latest versions seem to have resolved this for me.

**Comment by johno** [comment]
Going to close this since it seems to be working for folks on the latest version.
