### ISSUE TITLE
createPage componentWithMDXScope with a TSX failed.

### ISSUE THREAD

**Issue by meritozh** [ChristopherBiscardi/gatsby-mdx#220]
I didn't know how to use a `.tsx` file as post template. Can anyone help me?

```
info changed file at ***/demo/posts/test.mdx
error unknown: Unexpected token, expected "," (6:24)

  4 | import MDXRenderer from "gatsby-mdx/mdx-renderer";
  5 | 
> 6 | export default ({ data }: {data: any}) => {
    |                         ^
  7 |   const post = data.mdx;
  8 |   return (
  9 |     <Layout>
```

The demo repo is here: https://github.com/meritozh/gatsby-mdx-demo

**Comment by ChristopherBiscardi** [comment]
I'm removing `componentWithMDXScope` in #221, so assume this problem will go away on master soon. When #221 is merged, it will be automatically deployed on the `ci` tag and I'd appreciate it if you wanted to try it and see if it fixes your issue :)

**Comment by meritozh** [comment]
My pleasure. I'm in vacation, will try and report tomorrow here.

**Comment by meritozh** [comment]
It works! Will close this issue after stable release.

**Comment by ChristopherBiscardi** [comment]
0.3.2 is out!
