### ISSUE TITLE
not compiling mdx files from some other folder

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ChristopherBiscardi/gatsby-mdx#223]
Hi, I'm not a react developer. So yaa bear with me a bit. Sorry

I added below code in my `gatsby-config.js`

```
{
      resolve: `gatsby-mdx`,
      options: {
        defaultLayouts: { default: path.resolve('./src/components/layout.tsx') },
      },
    }
```

Now if I keep my .mdx files in `src/pages` it works fine. But what I wanted is to keep my .mdx files in the data folder. Right now everything that's in the data directory is compiled to 

<img width="154" alt="screenshot 2019-01-01 at 5 40 48 am" src="https://user-images.githubusercontent.com/8083613/50569293-d3670180-0d87-11e9-90b0-922902063f33.png">

What I wanted was. If I keep my .mdx files is in `data/blog` it should compile to blogpost. But I sort of can't do it. There are errors on page after compilation

<img width="1245" alt="screenshot 2018-12-31 at 3 43 07 am" src="https://user-images.githubusercontent.com/8083613/50569301-f85b7480-0d87-11e9-8e04-af11110bee6e.png">

Also, there's so error in console while typing `gatsby develop`
```
 WAIT  Compiling...                                                                               03:41:55

ℹ ｢wdm｣: Compiling...
 WARNING  Compiled with 1 warnings                                                                03:41:55

 warning  in ./src/components/Layout.tsx

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/node_modules/gatsby/dist/utils/babel-loader.js!/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/src/components/Layout.tsx
    Used by 11 module(s), i. e.
    /Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/node_modules/gatsby/dist/utils/babel-loader.js!/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/src/templates/blog-post.tsx
* /Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/node_modules/gatsby/dist/utils/babel-loader.js!/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/src/components/layout.tsx
    Used by 3 module(s), i. e.
    /Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/node_modules/gatsby/dist/utils/babel-loader.js!/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/node_modules/gatsby-mdx/loaders/mdx-loader.js??ref--13-1!/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/src/pages/test.mdx

⚠ ｢wdm｣: 
ℹ ｢wdm｣: Compiled with warnings.
> 
```

Guys please suggest me something. I'm have no idea what to do right now. Thanks

**Comment by ChristopherBiscardi** [comment]
It looks like you might either have `Layout.tsx` and `layout.tsx` at this file path:

```
/Users/abhimanyuaryan/GitHub/BLOG/abhimanyuaryan.gitlab.io/src/components/Layout.tsx
```

or you're importing from `src/components/Layout` in some places and `src/components/layout` in others.


Does this repo happen to be open source so I could look at it?

**Comment by AbhimanyuAryan** [comment]
Yes there you go @ChristopherBiscardi 

https://github.com/fabien0102/gatsby-starter

**Comment by AbhimanyuAryan** [comment]
Please help me understand this. So I convert all starter blogs to MDX. MD is dead since it doesn't allow bloggers to add dynamic behaviour their website

**Comment by AbhimanyuAryan** [comment]
right now the all the blog posts are .md format in https://github.com/fabien0102/gatsby-starter/tree/master/data/blog

I need to replace them to .mdx file

**Comment by meritozh** [comment]
@AbhimanyuAryan 

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-mdx`,
      options: {
        extensions: [".mdx", ".md"]
      }
    }
  ]
};
```

**Comment by AbhimanyuAryan** [comment]
@meritozh does nothing

**Comment by ChristopherBiscardi** [comment]
@AbhimanyuAryan You seem to have provided a repo that doesn't include a reproduction of the issue you filed here. Without a reproduction case, it will be very hard to help you as when I try it I do not see your error.

The best I can do is show you [this commit which adds MDX to your starter](https://github.com/ChristopherBiscardi/gatsby-starter/commit/fcc65a9a081b26030b91de407e5b07d8be735a77)

**Comment by AbhimanyuAryan** [comment]
@ChristopherBiscardi Thanks

**Comment by AbhimanyuAryan** [comment]
@ChristopherBiscardi https://github.com/AbhimanyuAryan/gatsby-starter/commit/0de6a074fef03dce39d029ccba059f54b06a24c3

All I did was to convert .md file to .mdx and it doesn't compile to a webpage(React). That was what I was saying

**Comment by ChristopherBiscardi** [comment]
@AbhimanyuAryan the code you just linked to doesn't have gatsby-mdx [in the package.json](https://github.com/AbhimanyuAryan/gatsby-starter/blob/0de6a074fef03dce39d029ccba059f54b06a24c3/package.json) or the [gatsby-config](https://github.com/AbhimanyuAryan/gatsby-starter/blob/0de6a074fef03dce39d029ccba059f54b06a24c3/gatsby-config.js). I'm not surprised you're seeing errors without having the package installed or configured. The comment I made earlier [has the code](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/223#issuecomment-451638688) to do both of these things as well as shows how to change the remark references to mdx, etc.

**Comment by AbhimanyuAryan** [comment]
Thanks for pointing out @ChristopherBiscardi but when I do `gatsby-build` this. I get this error. 

```

The GraphQL query from /Users/abhimanyuaryan/Desktop/gatsby-starter/src/templates/blog-post.tsx failed.

Errors:
  Cannot read property 'push' of undefined

  GraphQL request (50:5)
  49:   otherPost: mdx(fields: {slug: {eq: $slug}}) {
  50:     html
          ^
  51:     excerpt

URL path:
  /blog/2017-05-02--article-2/
Context:
  {
    "slug": "/blog/2017-05-02--article-2/"
  }
Plugin:
  none
Query:
  query TemplateBlogPost(
    $slug: String!
  ) {
    site: site {
      siteMetadata {
        disqus
      }
    }
    post: markdownRemark(fields: {slug: {eq: $slug}}) {
      html
      excerpt
      timeToRead
      fields {
        slug
      }
      frontmatter {
        tags
        author {
          id
          bio
          twitter
          avatar {
            children {
              __typename
              ... on ImageSharp {
                fixed(width: 80, height: 80, quality: 100) {
                  src
                  srcSet
                }
              }
            }
          }
        }
        title
        updatedDate(formatString: "MMM D, YYYY")
        image {
          children {
            __typename
            ... on ImageSharp {
              fixed(width: 900, height: 300, quality: 100) {
                src
                srcSet
              }
            }
          }
        }
      }
    }
    otherPost: mdx(fields: {slug: {eq: $slug}}) {
      html
      excerpt
      timeToRead
      fields {
        slug
      }
      frontmatter {
        tags
        author
        title
        updatedDate(formatString: "MMM D, YYYY")
        image {
          children {
            __typename
            ... on ImageSharp {
              fixed(width: 900, height: 300, quality: 100) {
                src
                srcSet
              }
            }
          }
        }
      }
    }
    recents: allMarkdownRemark(filter: {fields: {slug: {ne: $slug}}, frontmatter: {draft: {ne: true}}, fileAbsolutePath: {regex: "/blog/"}}, sort: {order: DESC, fields: [frontmatter___updatedDate]}, limit: 4) {
      edges {
        node {
          fields {
            slug
          }
          timeToRead
          frontmatter {
            title
            image {
              children {
                __typename
                ... on ImageSharp {
                  fixed(width: 300, height: 100) {
                    src
                    srcSet
                  }
                }
              }
            }
            author {
              id
              avatar {
                children {
                  __typename
                  ... on ImageSharp {
                    fixed(width: 36, height: 36) {
                      src
                      srcSet
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

success run graphql queries — 0.652 s — 8/8 12.31 queries/second
success write out page data — 0.007 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 7.765 s

 DONE  Compiled successfully in 5716ms                                  04:16:43


You can now view gatsby-starter in the browser.

  http://localhost:8000/

```

Also adding react in page works but can't seem to increment the counter when even I click on the button https://github.com/AbhimanyuAryan/gatsby-starter/blob/master/src/components/Counter.tsx 

New Files added: components/Counter.tsx

<img width="1190" alt="screenshot 2019-01-09 at 4 16 42 am" src="https://user-images.githubusercontent.com/8083613/50863730-a6d56a00-13c5-11e9-8d31-660523ea6849.png">

**Comment by JamesMessinger** [comment]
Possibly related to Issue #250
