### ISSUE TITLE
Manipulating mdx content

### ISSUE THREAD

**Issue by snawbel** [ChristopherBiscardi/gatsby-mdx#225]
What would be the best way to manipulate MDX content, for example changing `<Foo />` to `<Bar />` or to `<Foo bar="" />`. For example in a plugin or in `createPages`. Any examples?

**Comment by ChristopherBiscardi** [comment]
What is your end goal? Could you expand on the use case? There's many ways to achieve "replace this character with another" (remark plugins, hast plugins, babel plugins, scope replacements, etc) and it would be helpful to know what you're trying to do in a real-world sense.

**Comment by ChristopherBiscardi** [comment]
you seem to have [answered your own question](#218) so going to close this
