### ISSUE TITLE
gatsby-remark-prismjs's raw HTML injection doesn't get converted to JSX

### ISSUE THREAD

**Issue by meritozh** [ChristopherBiscardi/gatsby-mdx#227]
Demo is https://github.com/meritozh/gatsby-mdx-demo

Test post is: https://github.com/meritozh/gatsby-mdx-demo/blob/cd431b07fa36bd652fa45bfb52374f4f47754f86/posts/post-test/post.mdx#L23-L39

Render result is:

![screen shot 2019-01-04 at 3 01 06 pm](https://user-images.githubusercontent.com/7543300/50676845-97ef6000-1031-11e9-8cd9-f3a199f53e51.png)

The problems are:

1. `MDXRenderer` will eat _newline_
2. Seems it cannot correctly handle `{` and `}`. If I uncomment `function test {}`, it raise an error:

![screen shot 2019-01-04 at 3 03 05 pm](https://user-images.githubusercontent.com/7543300/50676903-e69cfa00-1031-11e9-9f0e-cc93a9a1dfa2.png)

**Comment by ChristopherBiscardi** [comment]
Long story short, the problem is that gatsby-remark-prismjs is injecting raw HTML into the AST so it doesn't get converted later in the process. This is fine for remark, which just passes the html chunks through to the browser but doesn't work for MDX, which does additional processing to convert html into JSX. I'm working on updating the gatsby-remark-* plugins to inject HAST into the AST and In the meantime, you can use a custom code component [as described here](https://www.christopherbiscardi.com/post/codeblocks-mdx-and-mdx-utils) which is the approach I generally recommend when working with MDX.

**Comment by ChristopherBiscardi** [comment]
I got it working:

![image](https://user-images.githubusercontent.com/551247/50917675-fc743b80-13f2-11e9-92e3-b27bd955f30e.png)

It looks like very similar code to the code in the blog post, but a few of the `(` have been changed to `{`, which means you can either change them back to parens or use `return`.

```diff
─────────────────────────────────────────────────────────────────────────────────────────────────────
modified: src/components/code.tsx
─────────────────────────────────────────────────────────────────────────────────────────────────────
@ code.tsx:38 @ export const Code: React.FunctionComponent<ICode> = ({
          getLineProps,
          getTokenProps,
        }: IHighlight) => {
          <pre className={className} style={style}>
+return          <pre className={className} style={style}>
            {tokens.map((line, i) => {
              <div {...getLineProps({ line, key: i })}>
+      return        <div {...getLineProps({ line, key: i })}>
                {line.map((token, key) => (
                  <span {...getTokenProps({ token, key })} />
                ))}
─────────────────────────────────────────────────────────────────────────────────────────────────────
modified: src/utils/wrap-root-element.tsx
─────────────────────────────────────────────────────────────────────────────────────────────────────
@ wrap-root-element.tsx:9 @ import React from 'react'
const components = {
  pre: (preProps: React.HTMLAttributes<any>) => {
    const props = preToCodeBlock(preProps)
    console.log(props, preProps)
    if (props) {
      return <Code {...props} />
    } else {
@ wrap-root-element.tsx:23 @ type T = {
}

export const wrapRootElement = ({ element }: T) => {
  <MDXProvider components={components}>{element}</MDXProvider>
+  return  <MDXProvider components={components}>{element}</MDXProvider>
}
```

fat arrows with parens return the value

```js
() => (<div/>)
// returns <div/>
```

fat arrows with brackets don't implicity return anything, so will return `undefined` like a normal function definition if there is no return

```js
() => {<div>}
// returns undefined
```

**Comment by meritozh** [comment]
Write my own line number components, works perfect!

**Comment by detj** [comment]
Just wanted to add that the above link is broken.

[This is the replacement link that works](https://www.christopherbiscardi.com/post/codeblocks,-mdx,-and-mdx-utils)

**Comment by ChristopherBiscardi** [comment]
I've updated my blog links so both links work and the non-comma version is the default
