### ISSUE TITLE
pageContext undefined at build time

### ISSUE THREAD

**Issue by atomiks** [ChristopherBiscardi/gatsby-mdx#228]
**Describe the bug**
It works during dev, but at build time it errors out:

`WebpackError: TypeError: Cannot read property 'frontmatter' of undefined`

I'm not sure if it's a Gatsby issue or this plugin.

**To Reproduce**

https://github.com/atomiks/gatsby-mdx-issue

I'm accessing frontmatter from `.mdx` files in some components (`src/components/Layout.js` and `src/components/SEO.js`), but the `pageContext` prop appears to be undefined at build time.

`npm start`, everything's fine
`npm run build`, error occurs

**Expected behavior**
No error?

**Screenshots**

**Additional context**

**Comment by ChristopherBiscardi** [comment]
This actually isn't an mdx issue, it's failing on the 404 page:

```js
import React from 'react'

import Layout from '../components/Layout'
import SEO from '../components/SEO'

const NotFoundPage = () => (
  <Layout>
    <SEO title="404: Not found" />
    <h1>NOT FOUND</h1>
    <p>You just hit a route that doesn&#39;t exist... the sadness.</p>
  </Layout>
)

export default NotFoundPage
```

You would need to pass the pageContext through to the `Layout` component from the 404 pages's props.

```
import React from 'react'

import Layout from '../components/Layout'
import SEO from '../components/SEO'

const NotFoundPage = ({ pageContext }) => (
  <Layout pageContext={pageContext}>
    <SEO title="404: Not found" />
    <h1>NOT FOUND</h1>
    <p>You just hit a route that doesn&#39;t exist... the sadness.</p>
  </Layout>
)

export default NotFoundPage
```

Also note that the frontmatter is undefined because there is no frontmatter in the 404.js file (because it's not an mdx file, so doesn't get processed as one)

**Comment by atomiks** [comment]
Completely forgot about the 404, thank you
