### ISSUE TITLE
allMdx query html field throws "not defined" error for imported JSX components in mdx file

### ISSUE THREAD

**Issue by joelhooks** [ChristopherBiscardi/gatsby-mdx#229]
**Describe the bug**
When I have imports in mdx and try to query `allMdx` for the `html` field in `gatsby-plugin-feed` it throws an error that the component cannot be found.

```markdown
slug: 2018-in-review
date: 2019-01-04
title: '2018 in Review'
description: 'If there is one thing I learned in 2018, it is to stop setting goals and start working on systems.'
categories: ['JFDI']
keywords: ['planning', 'systems']
featured: false
published: true
---

import Test from 'components/Test'

<Test />
```

```bash
 Error: Test is not defined
  GraphQL request (11:23)
  10:                       excerpt(pruneLength: 250)
  11:                       html
                            ^
  12:                       fields {
```

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/joelhooks/joelhooks-com/tree/rss-broken) and Steps to reproduce the behavior:
1. `gatsby build`

**Expected behavior**
the `html` shouldn't break and should render as expected with any JSX components

**Comment by ChristopherBiscardi** [comment]
hah, what great timing. I just pushed working code for this to master.

**Comment by joelhooks** [comment]
Well, I didn't get the error about the missing component, but it has some complaints about `__WEBPACK_EXTERNAL_MODULE_react__` not being defined. 

@emotion/core is in the stack, so likely unrelated to this issue.

It also gives the same error on build with or without the JSX in my markdown.

```
success Building static HTML for pages — 2.839 s — 51/51 57.99 pages/second
[ 'ReferenceError: __WEBPACK_EXTERNAL_MODULE_react__ is not defined\n    at Object.react (evalmachine.<anonymous>:2744:18)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at Module../node_modules/@emotion/core/dist/core.esm.js (evalmachine.<anonymous>:560:63)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at Module../node_modules/gatsby-mdx/utils/wrap-root-render-html-entry.js (evalmachine.<anonymous>:2651:71)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at evalmachine.<anonymous>:84:18\n    at evalmachine.<anonymous>:87:10\n    at Script.runInContext (vm.js:107:20)\n    at Script.runInNewContext (vm.js:113:17)' ]
error UNHANDLED EXCEPTION


  Error: no such file or directory

  - MemoryFileSystem.js:114 MemoryFileSystem.readFileSync
    [joelhooks-com]/[memory-fs]/lib/MemoryFileSystem.js:114:10

  - render-html.js:54 compiler.run
    [joelhooks-com]/[gatsby-mdx]/utils/render-html.js:54:26

  - Compiler.js:210 finalCallback
    [joelhooks-com]/[webpack]/lib/Compiler.js:210:39

  - Compiler.js:259 hooks.done.callAsync.err
    [joelhooks-com]/[webpack]/lib/Compiler.js:259:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [joelhooks-com]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:257 emitRecords.err
    [joelhooks-com]/[webpack]/lib/Compiler.js:257:22

  - Compiler.js:371 Compiler.emitRecords
    [joelhooks-com]/[webpack]/lib/Compiler.js:371:39

  - Compiler.js:251 emitAssets.err
    [joelhooks-com]/[webpack]/lib/Compiler.js:251:10

  - Compiler.js:357 hooks.afterEmit.callAsync.err
    [joelhooks-com]/[webpack]/lib/Compiler.js:357:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [joelhooks-com]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:354 asyncLib.forEach.err
    [joelhooks-com]/[webpack]/lib/Compiler.js:354:27

  - async.js:2825
    [joelhooks-com]/[neo-async]/async.js:2825:7

  - async.js:2861 done
    [joelhooks-com]/[neo-async]/async.js:2861:11

  - async.js:2813
    [joelhooks-com]/[neo-async]/async.js:2813:7

  - MemoryFileSystem.js:328 MemoryFileSystem.writeFile
    [joelhooks-com]/[memory-fs]/lib/MemoryFileSystem.js:328:9

  - Compiler.js:338 writeOut
    [joelhooks-com]/[webpack]/lib/Compiler.js:338:29

  - Compiler.js:348 asyncLib.forEach
    [joelhooks-com]/[webpack]/lib/Compiler.js:348:7

  - async.js:2416 baseEach
    [joelhooks-com]/[neo-async]/async.js:2416:9

  - async.js:2850 Object.each
    [joelhooks-com]/[neo-async]/async.js:2850:9

  - Compiler.js:311 emitFiles
    [joelhooks-com]/[webpack]/lib/Compiler.js:311:13
```

**Comment by btables** [comment]
@ChristopherBiscardi Could we not use imported jsx components until gatsby-mdx@0.3.3-ci.244 ?

I am facing the issue where if I have just an .mdx file in src/pages/ it works completely fine importing my components. However if I build my pages up using gatsby-node and a template I get the not defined error.

**Comment by ChristopherBiscardi** [comment]
@btables I pulled your example and it worked for me. 

![image](https://user-images.githubusercontent.com/551247/50740619-e58cd980-11a5-11e9-9224-1918ef528cff.png)

You could not use *relative* paths in MDX that was rendered from GraphQL queries until recently (ie: MDX content that required using `MDXRenderer`). Support went out in the most recent stable release `0.3.2` and was merged as of https://github.com/ChristopherBiscardi/gatsby-mdx/commit/a94786bf07072fc18c9db995173249c3e0ff3934. Relative paths have always worked in `src/pages`.

**Comment by btables** [comment]
@ChristopherBiscardi Thanks for the speedy reply! You pulled it without making any changes or did you bump up the version?  So I can use it the way I was using it in 0.3.2? 

Strange.. when I try upgrading to 0.3.2 (or any newer version for that matter), gatsby develop yields a very long and confusing (to me) error :

Error: ./node_modules/gatsby-mdx/loaders/mdx-scopes.js
  Module not found: Error: Can't resolve 'C:Users
  tablesDesktopmdx-issuegatsby-mdx-issue-react-undefined.cachegatsby-mdxmdx-scopes-dicd190d04cf5fa8ed9cc7cc3be786ee0.js' in 'C:\Users\btables\Desktop\mdx-issue\gatsby-mdx-issue-react-undefined'


Am I missing something obvious :) ?

**Comment by ChristopherBiscardi** [comment]
@btables OH you're on windows? I started a new issue to look into this: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/231

**Comment by lankybutmacho** [comment]
Hi, I'm having this issue as well (and not on Windows). Here's a [minimal repro](https://github.com/lankybutmacho/gatsby-mdx-minimal-repro/tree/allmdx-html-field), the only change I made was updating gatsby-mdx to 0.3.2.

The `allMdx` query errors on `page-3.mdx`:

![screen shot 2019-01-06 at 6 49 13 pm](https://user-images.githubusercontent.com/619997/50743287-f2c8b900-11e3-11e9-8dcf-4aff4dbc8083.png)

**Comment by ChristopherBiscardi** [comment]
@lankybutmacho You'd need to upgrade to `gatsby-mdx@0.3.3-ci.244` or later to experience this error. The `html` field *was* broken in 0.3.2 because of the new scoping changes, but that particular issue has been fixed on master and released as `gatsby-mdx@0.3.3-ci.244`

**Comment by lankybutmacho** [comment]
Ah got it, I misunderstood your earlier comment. Thanks!

**Comment by joelhooks** [comment]
The original issue no longer occurs, though I am still very broken at this version, but for a different reason. To that end, I'm closing this issue and will file another as needed.
