### ISSUE TITLE
allMdx query doesn't work out of the box with the gatsby-starter-mdx-basic template

### ISSUE THREAD

**Issue by lankybutmacho** [ChristopherBiscardi/gatsby-mdx#230]
**Describe the bug**

I created a fresh site from the gatsby-starter-mdx-basic template. Having made no changes and just run `gatsby develop`, I can see the generated pages at `localhost:8000`, but when I try to run the sample GraphQL query from https://gatsby-mdx.netlify.com/guides/querying-mdx-content-via-graphql, I get the error 'Cannot query field "allMdx" on type "Query".'

FWIW, when I fork `gatsby-mdx-minimal-repro`, I do not see this issue.

Am I missing something obvious?

**To Reproduce**

1. `npx gatsby new my-mdx-starter https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic`
2. `cd my-mdx-starter/`
3. `gatsby develop`
4. Open http://localhost:8000/___graphql and run the query:
```
query MDXQuery {
  allMdx {
    edges {
      node {
        parent {
          ... on File {
            name
            absolutePath
            relativePath
          }
        }
        timeToRead
        frontmatter {
          title
        }
        exports {
          author
        }
      }
    }
  }
}
```

**Expected behavior**

The `allMdx` query would return all mdx nodes

**Screenshots**

<img width="1087" alt="screen shot 2019-01-05 at 11 39 44 am" src="https://user-images.githubusercontent.com/619997/50726688-a6e01c00-10de-11e9-9ac6-25a76260d768.png">

**Comment by ChristopherBiscardi** [comment]
Yeah mdx-basic doesn't include a filesystem source pointed at the MDX files, so you need to add one to the gatsby-config. Perhaps we should have one by default

**Comment by lankybutmacho** [comment]
Ahhh, should have thought of that. Thanks! Yeah having a default or maybe just a note in the docs would be great.
