### ISSUE TITLE
new mdx scopes and windows paths

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#231]
**Describe the bug**

```
Error: ./node_modules/gatsby-mdx/loaders/mdx-scopes.js
Module not found: Error: Can't resolve 'C:Users
tablesDesktopmdx-issuegatsby-mdx-issue-react-undefined.cachegatsby-mdxmdx-scopes-dicd190d04cf5fa8ed9cc7cc3be786ee0.js' in 'C:\Users\btables\Desktop\mdx-issue\gatsby-mdx-issue-react-undefined'
```

**To Reproduce**

Any programmatic MDX (not `src/pages`) after the new mdx scopes was merged (0.3.2 would do it)

**Expected behavior**

Build doesn't fail on windows

**Additional context**
https://github.com/ChristopherBiscardi/gatsby-mdx/issues/229#issuecomment-451769495

**Comment by ChristopherBiscardi** [comment]
I don't have a windows box so don't know how to check this, but I think it's due to the way we handle paths in the `mdx-scopes` loader.

Specifically, this might not work? https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/loaders/mdx-scopes.js#L5-L6

```
  const files = fs.readdirSync("./.cache/gatsby-mdx/mdx-scopes-dir");
  const abs = path.resolve("./.cache/gatsby-mdx/mdx-scopes-dir");
```

**Comment by btables** [comment]
Not sure how much I can help since I'm not too familiar with whats going on :). By the way, I did switch to UNIX and was able to run it fine. 

If it helps at all, on Windows this is what I see is returned by the files.map

`const scope_0 = require('C:\Users\btables\Desktop\mdx-issue\gatsby-mdx-issue-react-undefined\.cache\gatsby-mdx\mdx-scopes-dir\bcd190d04cf5fa8ed9cc7cc3be786ee0.js').default;export default {
...scope_0
}`

Anything else I can look into?

**Comment by ChristopherBiscardi** [comment]
> Just switched over to UNIX and it seems to be returning the exact same thing.

whelp I'm not sure then. It looks like you have one MDX file being processed, can you post that MDX file?

And also can you post the error message from unix just for completeness?

**Comment by btables** [comment]
Sorry! I meant the files.map prints an identical string! I'm not seeing any errors on UNIX

**Comment by ChristopherBiscardi** [comment]
@btables ah, gotcha! Can you paste the contents of that scope file then from windows? The one at

```
C:\Users\btables\Desktop\mdx-issue\gatsby-mdx-issue-react-undefined\.cache\gatsby-mdx\mdx-scopes-dir\bcd190d04cf5fa8ed9cc7cc3be786ee0.js
```

**Comment by btables** [comment]
`import Header from 'components/header';
import React from 'react';
import { MDXTag } from '@mdx-js/tag';
export default {
  Header,
  React,
  MDXTag
};`
