### ISSUE TITLE
Upgrading to from 0.2.0 to 0.3.2 crashes the Gatsby build

### ISSUE THREAD

**Issue by AlmeroSteyn** [ChristopherBiscardi/gatsby-mdx#233]
**Describe the bug**
If I upgrade `gatsby-mdx` from `v0.2.0` to `v0.3.2` the previously working site no longer builds and I get error:

```
Error: ./node_modules/gatsby-mdx/loaders/mdx-scopes.js 1:89
  Module parse failed: Octal literal in strict mode (1:89)
  You may need an appropriate loader to handle this file type.
  > const scope_0 = require('C:\dev\tenon\tenon-www-redesign\.cache\gatsby-mdx\mdx-scopes-dir\3010b3badc54a9dfa4a4c80e419a41b2.js').default;export default {
  |   ...scope_0
  | }
   @ ./node_modules/gatsby-mdx/wrap-root-element.js 3:0-50 8:16-29
   @ ./node_modules/gatsby-mdx/gatsby-ssr.js
   @ ./.cache/api-runner-ssr.js
   @ ./.cache/develop-static-entry.js
```

I consulted the `Changelog` file but this release has not been documented yet in terms of breaking changes.

**To Reproduce**
It is hard for me to reproduce this in a minimal repo as the minimal repo will already work and I don't know how to break it again.

I am running the latest versions of `Gatsby` and `Mdx`.

My config file is:

```
module.exports = {
  siteMetadata: {
    title: "xxx",
    description: "xxx."
  },
  plugins: [
    {
      resolve: `gatsby-source-datocms`,
      options: {
        // You can find your read-only API token under the Settings > API tokens
        // section of your administrative area:
        apiToken: process.env.DATO_API_TOKEN,

        // If you are working on development/staging environment, you might want to
        // preview the latest version of records instead of the published one:
        previewMode: false,
      },
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-layout',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'xxx',
        short_name: 'xxx',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/favicon.png', // This path is relative to the root of the site.
      },
    },
    'gatsby-plugin-offline',
    'gatsby-mdx',
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        includePaths: ['node_modules'],
      },
    },
  ],
}

```

**Comment by AlmeroSteyn** [comment]
I have pushed the repo to GitHub. 

https://github.com/AlmeroSteyn/dato-cms-blog

If I run `yarn` on this, followed by `yarn develop` I get:

```
  Error: ./node_modules/gatsby-mdx/loaders/mdx-scopes.js 1:87
  Module parse failed: Octal literal in strict mode (1:87)
  You may need an appropriate loader to handle this file type.
  > const scope_0 = require('C:\dev\personal\dato-cms-blog\.cache\gatsby-mdx\mdx-scopes-dir\3010b3badc54a9dfa4a4c80e419a41b2.js').default;
  | const scope_1 = require('C:\dev\personal\dato-cms-blog\.cache\gatsby-mdx\mdx-scopes-dir\e43fb7ea8e5c973fc291302acf6043f3.js').default;export default {
  |   ...scope_0,
   @ ./node_modules/gatsby-mdx/wrap-root-element.js 3:0-50 8:16-29
   @ ./node_modules/gatsby-mdx/gatsby-ssr.js
   @ ./.cache/api-runner-ssr.js
   @ ./.cache/develop-static-entry.js
```

This code is completely unchanged from your examples directory.

If I downgrade the plugin to `0.2.0` the dev server does start. The pages themselves gives errors then but the build error goes away.

**Comment by ChristopherBiscardi** [comment]
hmm, I think this is #231 so going to merge it in with that one as a dupe.

>   Module parse failed: Octal literal in strict mode (1:87)

That's bizarre and I've never seen it before.

> If I downgrade the plugin to 0.2.0 the dev server does start. The pages themselves gives errors then but the build error goes away.

0.2 to 0.3.2 is "breaking" in the sense that internally they work completely differently for scope related purposes, so the dev server working on one and not on the other doesn't provide a lot of info. It's not supposed to be breaking on a user level, but I don't have a windows box to test on right now so it's hard for me to replicate this particular issue :/

Any suggestions of OSS CI providers that run windows tests? we clearly need them.

**Comment by AlmeroSteyn** [comment]
@ChristopherBiscardi Yeah I agree it seems to be related. I saw the open issue too late. It seems to fail in the same place. 

As for Windows testing, I see that Travis now has a Windows environment but it is early days so dunno if it is enough: https://docs.travis-ci.com/user/reference/windows/
