### ISSUE TITLE
Add `Component` field to MDX GraphQL Schema

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#234]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that we need to tell people to use MDXRenderer. Like componentWithMDXScope before it, `MDXRenderer` should be removed from the public API.

**Describe the solution you'd like**
I'd like to hitch a ride on Gatsby's query AST parsing to wrap any MDX content that comes back in an MDXRenderer. This way users can just drop mdx in as a child

```js
const MyPageTemplate = ({ data }) => (
  <div>
    <h1>SomeStuff</h1>
    {data.mdx.Component}
  </div>
)
```

or as a component that accepts the same props as MDXRenderer

```js
const MyPageTemplate = ({ data }) => {
  <div>
    <h1>SomeStuff</h1>
    <data.mdx.Component scope={}/>
  </div>
)
```

**Describe alternatives you've considered**

* People keep using MDXRenderer. It's maybe not actually that big a deal and more explicit.

**Additional context**
I don't think anyone else has return a component from gatsby's graphql layer yet. TBD on how effective it is.

**Comment by hagnerd** [comment]
This looks really cool. I don't think it's a major inconvenience to have to wrap in MDXRenderer, but I wouldn't complain about not having to use it. 

I feel like it would depend on how hard it is to implement, and what the unseen costs of an alternative, when compared to just having to wrap in MDXRenderer.

**Comment by hagnerd** [comment]
I'd be curious to hear more when/if you have time to think about it. Maybe explore it on a Twitch stream?

**Comment by ChristopherBiscardi** [comment]
Closing this as we look to migrate to the gatsby repo
