### ISSUE TITLE
gatsbyRemarkPlugins not used in `timeToRead` resolver

### ISSUE THREAD

**Issue by stephanschubert** [ChristopherBiscardi/gatsby-mdx#242]
**Describe the bug**

The `gatsbyRemarkPlugins` aren't used while [processing the AST in `extend-node-type.js`](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/c9439bec7c1849587232a744c614def8a0007373/packages/gatsby-mdx/extend-node-type.js#L48-L52)

**To Reproduce**

A minimal repo is hard to come up with at the moment but I will describe it as best as I can. 

* Using KaTeX in one of my `.md` files: `$E=mc^2$`

* Noticed an error while trying to query `timeToRead`:

The `textAst` looks like this at that point:

```
    {
      "type": "paragraph",
      "children": [
        {
          "type": "inlineMath",
          "value": "E=mc^2",
          "data": {
            "hName": "span",
            "hProperties": {
              "className": "inlineMath"
            },
            "hChildren": [
              {
                "type": "text",
                "value": "E=mc^2"
              }
            ]
          },
...
```

But `gatsbyRemarkPlugins` contains:

```
[ { resolve: 'gatsby-remark-autolink-headers' },
  { resolve: 'gatsby-remark-external-links' },
  { resolve: 'gatsby-remark-copy-linked-files' },
  { resolve: 'gatsby-remark-smartypants' },
  { resolve: 'gatsby-remark-katex' },
...
```

Rendering the `.md` file works because it uses the plugins but querying `timeToRead` fails here with:

```
Errors:
  Missing compiler for node of type `inlineMath`: `[object Object]`

  GraphQL request (9:5)
   8:     }
   9:     timeToRead
          ^
```
It seems the [resolver's processing pipeline](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/c9439bec7c1849587232a744c614def8a0007373/packages/gatsby-mdx/extend-node-type.js#L48-L52) is missing the plugins?

**Expected behavior**

`timeToRead` should not throw an error.

**Comment by ChristopherBiscardi** [comment]
my best guess for a minimal repro for this is using the `remark-math` plugin, which katex uses to insert the `inlineMath` node type (iirc).

in any case, we should be *at minimum* skipping over nodes we don't recognize, although it would be nice to include it in the output too.
