### ISSUE TITLE
Using custom component with gatsby-remark-images

### ISSUE THREAD

**Issue by deltaskelta** [ChristopherBiscardi/gatsby-mdx#251]
**Is your feature request related to a problem? Please describe.**

I am trying to use gatsby-remark-images with MDX and I am not sure how to go about giving an image a component.

```
<LeftImg>
![go exercise images](./media/go-exercise-images-1.png)
</LeftImg>
```

This images renders centered when I take away the `<LeftImg>` component, but it just renders the markdown text as a child when it is present. I would like to be able to give the images a custom component for alignment. I know remark images lets you define one style for images, but I would like multiple options.

**Describe the solution you'd like**

There may already be a way to accomplish this that I am unaware of

**Comment by ChristopherBiscardi** [comment]
you might be able to achieve this with a newline insertion

```
<LeftImg>

![go exercise images](./media/go-exercise-images-1.png)

</LeftImg>
```

The reason this works like this but not without the newlines is because of a bug in MDX upstream.

**Comment by deltaskelta** [comment]
hmm yeah this kind of works... it wraps it in a `<p>` but my initial try didn't work too well. Here is what it looks like with a 5px black border...

![screen shot 2019-01-14 at 2 02 05 pm](https://user-images.githubusercontent.com/9424192/51097138-2c617b80-1805-11e9-84b2-fd86d86e1894.png)

Theres probably a solution in here somewhere though, I will play with it more. Do you have the mdx issue that references this on hand?

**Comment by ChristopherBiscardi** [comment]
I think https://github.com/mdx-js/mdx/issues/340 is the same bug (which means https://github.com/ChristopherBiscardi/gatsby-mdx/issues/222 is too) and https://github.com/mdx-js/mdx/issues/241 is a related issue.

**Comment by ChristopherBiscardi** [comment]
you could do two things here that I can think of to sort of patch the issue

1) write a remark plugin that removes the `<p>` if the child is `img` and use it before `gatsby-remark-images`
2) override the rendering of `<p>` using `MDXProvider` and if the child looks like the output of `gatsby-remark-images`, render the children directly instead.

**Comment by deltaskelta** [comment]
good idea, I'll try to add a check to my `p` overrides when I have a chance

**Comment by johno** [comment]
Btw, I have a plugin, [remark-unwrap-images](https://github.com/johno/remark-unwrap-images) that handles removing the wrapping paragraph around image nodes.

**Comment by deltaskelta** [comment]
in my case I took the fix you mentioned and fixed the rest with css. I was using `float: left` with no set width which was defaulting to 0 width and messing up the border.

I'm not sure whether to close this or not as there is still an issue. Please do whatever you see fit

**Comment by thundernixon** [comment]
@johno sorry, it's a bit unclear to me ... would using that `<p>` wrapper-removing plugin be a patch for this issue? That is, would it allow me to successfully write markdown as referenced in the initial post of this thread?

```
<LeftImg>
![go exercise images](./media/go-exercise-images-1.png)
</LeftImg>
```

**Comment by ChristopherBiscardi** [comment]
@thundernixon yes, but you have to write it with the newlines because of a bug in mdx core.

```
<LeftImg>

![go exercise images](./media/go-exercise-images-1.png)

</LeftImg>
```

**Comment by thundernixon** [comment]
@ChristopherBiscardi okay, thanks for clarifying that! 

Shoot, I don't think I have the technical capabilities right now to PR a solution to this in mdx core, but hopefully this is fixed at some point. I'm considering getting non-webdevs to write in markdown for a site, and I bet this might cause more than a few issues... I'll keep an eye out for an update from core!

**Comment by deltaskelta** [comment]
@thundernixon FWIW when I run into a problem like this I have found in the past that there is usually a better way to go about it with MDX and components. For example, this is how I handle my images now. Non devs should be able to do this if they can handle markdown

https://github.com/ChristopherBiscardi/gatsby-mdx/issues/252

**Comment by johno** [comment]
Going to go ahead and close this because @deltaskelta has written up the "MDX way" of achieving this functionality. We will also be adding a short guide as part of gatsbyjs/gatsby#11361

**Comment by thundernixon** [comment]
@deltaskelta sorry for my late response, but thanks so much for showing another approach!

To be honest, that seems more error-prone / difficult to me, at least in terms of a blog-like article. If I'm understanding your approach correctly, it requires images to be referenced in a different location from where they're used, and this separates them from the content (e.g. captions, other text, etc). I would be easy for an author to get confused about which image is `<Image5/>` vs `<Image6/>`, etc.

**Comment by deltaskelta** [comment]
yeah the image indexing is a downside, but I found it to be acceptable when compared with the alternatives. All of the images are right in the frontmatter so I just have to go back up to see which one is which sometimes.

**Comment by thundernixon** [comment]
It's a smart solution, and probably great for your use case! UX-wise for my purposes on a portfolio / blog with collaborators, it's not *that bad*, but I'd say it's not yet the ideal solution. 

To me, MDX promises the ease and speed of writing markdown, plus the powerful components of react. So, having images referenced just where they're used is closer to that, I think.

**Comment by ChristopherBiscardi** [comment]
The ideal situation is likely using [static queries with variables](https://github.com/gatsbyjs/gatsby/issues/10482) paired with a custom component so you can end up with `<Image src="somewhere.png"/>` that uses a static query internally or is transformed by a plugin (babel, etc) into the static query itself. No read on when that will happen though. Would be happy to see someone work on it :)
