### ISSUE TITLE
A better way to handle images

### ISSUE THREAD

**Issue by deltaskelta** [ChristopherBiscardi/gatsby-mdx#252]
**Is your feature request related to a problem? Please describe.**

I have been playing around with a solution to #205 and I think there is probably just an all around better way to handle images with MDX here. I have something that I think "should" work but it is not working for me yet. There may be a better way to accomplish this.

I want to be able to:

1. colocate my images with my mdx files so I don't have to put them in static
2. use custom components to render the images in MDX files so that I can take advantage of `gatsby-image` and `gatsby-plugin-sharp`

I was thinking to do this...

put images array in the frontmatter

```
---
title: foo
images: 
  - ./img.png
  - ./img2.png
---
```

in the template graphql query, it already knows they are image files, so I can query `childImageSharp`

```
      ...
      frontmatter {
        title
        images {
          childImageSharp {
            fluid {
              base64
              tracedSVG
              aspectRatio
              src
              srcSet
              srcWebp
              srcSetWebp
              sizes
              originalImg
              originalName
              presentationWidth
              presentationHeight
            }
          }
        }
      }
      ...
```

then in the page template component I can take the array of images and make something to give to `MDXRenderer`

```
  const imgs: { [k: string]: React.ReactNode } = {};
  if (images) {
    images.forEach((image, i) => {
      const { childImageSharp } = safe(image);
      const { fluid } = safe(childImageSharp);

      imgs[`Image${i}`] = () => <Img fluid={fluid} />;
    });
  }
```

and then in the `MDXRenderer` they can be passed in...

```
<div className={classes.postBody}>
  <MDXRenderer scope={{ ...imgs }}>{body}</MDXRenderer>
</div>
```

and then in the MDX file the components could be called...

```
## blah blah 

<Image0 />
```

I think this should work, but I am getting the error below

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Component`
```

Is there a simpler way to accomplish what I am trying to do or to make this work?

**Comment by deltaskelta** [comment]
It actually does work. I was just importing from `gatsby-image` wrong.... :)

The first part of the question still stands though. Is this really a better way to handle images, and is there a better way to accomplish this?

**Comment by deltaskelta** [comment]
I can't quite figure out how to access the props in MDX... what is the correct way to do that?

**Comment by ChristopherBiscardi** [comment]
https://www.christopherbiscardi.com/post/accessing-props-in-mdx

**Comment by deltaskelta** [comment]
I wrote a small guide about how to do this with links to my own repo https://deltaskelta.github.io/blog/using-gatsby-images-with-gatsby-mdx/

**Comment by deltaskelta** [comment]
I just wanted to add to this that I've updated my post because passing props in to `MDXRenderer` is actually a much better way because passing scopes shouldn't be done anymore (according to the current docs)

if the images are passed to the renderer as props, I can call them in a post like this...

```
<props.imgs.Img1 width="100%" align="left" />
```

**Comment by KyleAMathews** [comment]
BTW, generally you want to use one of the query fragments for gatsby-image as you're querying for extra fields now — which means more processing time for images https://www.gatsbyjs.org/packages/gatsby-image/?=gatsby-image#fragments

**Comment by deltaskelta** [comment]
Thanks for the tip. I have since discovered those. I'll edit my post for others that find it
