### ISSUE TITLE
Feed generation needs optimization

### ISSUE THREAD

**Issue by stephanschubert** [ChristopherBiscardi/gatsby-mdx#255]
Feed generation with just ~20 posts using 2 simple components (one outputs some text, the other a special link) fails with an out-of-memory error.

```
<--- Last few GCs --->

[15151:0x102801600]   136983 ms: Mark-sweep 1148.3 (1439.2) -> 1136.2 (1433.2) MB, 1199.0 / 0.9 ms  (average mu = 0.186, current mu = 0.043) allocation failure scavenge might not succeed
[15151:0x102801600]   137037 ms: Scavenge 1149.9 (1433.2) -> 1141.8 (1433.7) MB, 6.8 / 0.0 ms  (average mu = 0.186, current mu = 0.043) allocation failure
[15151:0x102801600]   137138 ms: Scavenge 1157.8 (1437.6) -> 1150.7 (1444.6) MB, 9.4 / 0.0 ms  (average mu = 0.186, current mu = 0.043) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3d7ae16041bd]
Security context: 0x34cc5141e6c9 <JSObject>
    1: update [0x34cc0a99e829] [internal/crypto/hash.js:62] [bytecode=0x34cc88161581 offset=106](this=0x34ccf56e0939 <Hash map = 0x34ccebe14421>,data=0x34ccf56e11f1 <String[1001]: ../../node_modules/ramda/src/adjust.js../../node_modules/ramda/src/adjust.jsundefined../../node_modules/ramda/src/adjust.jsnullnulltrue264,306../../node_modules/ramda/src/all.jsund...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

This is probably caused by using a webpack instance per post to render the HTML?

**Comment by ChristopherBiscardi** [comment]
woof yeah, that's bad. It works on my ~80ish post blog so curious as to why it's failing for you. 

There's an issue #235 that is related to keeping the webpack objects in memory which could be related here.

**Comment by stephanschubert** [comment]
Unfortunately I can't reproduce it at the moment. I watched the process taking up to 1.6 GB of memory while running `npm run build`. My guess is that I hadn't that much left yesterday.

```
du -hs content/posts/**/*.md | wc -l
      33
```

N.B: Only 33 small posts (none file takes up more than 4k on disk).

Leave it open as a reminder to optimize or close it?

**Comment by ChristopherBiscardi** [comment]
I mean, it *should* be optimized, but if it's not actually causing memory based failures we can wait a bit to optimize it and focus on docs and features. Since `html` is really only used for gatsby-plugin-feed right now this won't show up in development.

Since this issue will be found if anyone searches for it I'm going to close it. We already have #235 to track FS changes which should help with perf.

Please ping me if it happens again though. We can re-open and deal with it if it does.
