### ISSUE TITLE
Image in "Using Gatsby Remark images" documentation is broken

### ISSUE THREAD

**Issue by danoc** [ChristopherBiscardi/gatsby-mdx#258]
**Describe the bug**
The example image on this page does not load:
https://gatsby-mdx.netlify.com/guides/using-gatsby-remark-images

**To Reproduce**
1. Visit: https://gatsby-mdx.netlify.com/guides/using-gatsby-remark-images
2. See image at bottom.

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
I'm experiencing a similar issue in a project that uses `gatsby-mdx`.

Currently debugging this and I've noticed a few things so far:

* The images appear if I run Gatsby build twice. In my case, this happens because `gatsby-remark-copy-linked-files` doesn't see the images on the first pass.
* Unsure if this is an issue in `gatsby`, `gatsby-remark-copy-linked-files`, or `gatsby-mdx`.

I'll continue looking into this and update here.

**Comment by danoc** [comment]
Still unsure what is causing this. 

I've confirmed that running `rm -rf .cache public && yarn build` in the [`gatsby-mdx` docs](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/master/examples/docs) fails. It does work if I run it twice (`rm -rf .cache public && yarn build && yarn build`).

Won't be able to look into this much longer. For now my workaround is to simply run the command twice:

![Screenshot of workaround](https://user-images.githubusercontent.com/916038/51275308-6c03a100-1986-11e9-8916-fd827a7dbcb3.png)

**Comment by ChristopherBiscardi** [comment]
might be related to https://github.com/ChristopherBiscardi/gatsby-mdx/issues/257

**Comment by danoc** [comment]
Confirmed that it's the same issue. Will close this one. 💯
