### ISSUE TITLE
mdx v0.15.0-1 requires obj-rest spread

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#27]
Need to have a good way of adding `@babel/plugin-proposal-object-rest-spread` to the babel loader chain due to the new props passing

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/search?q=onCreateBabelConfig&unscoped_q=onCreateBabelConfig

Though the API _might_ change slightly with https://github.com/gatsbyjs/gatsby/issues/4689

**Comment by ChristopherBiscardi** [comment]
fixed in https://github.com/ChristopherBiscardi/gatsby-mdx/commit/73d756ed9fa52d04529f3fa33b74235bb9eaaf74
