### ISSUE TITLE
Site breaks completely in IE/Edge

### ISSUE THREAD

**Issue by pascal-kubrick** [ChristopherBiscardi/gatsby-mdx#277]
**Describe the bug**

MDX pages created using 'createPages' break the site completely (blank screen) in both IE and Edge (latest).

If you omit createPages entirely and let the pages generate via the defaultLayouts option it seems to work fine.

The error returned in the console is the following: `SCRIPT1028: Expected identifier, string or number`

**Edit**; seems to be the related to https://github.com/ChristopherBiscardi/gatsby-mdx/issues/205#issuecomment-455886949

**To Reproduce**

Add the following to gatsby-node.js

`
const Promise = require('bluebird');
const path = require('path');

const { createFilePath } = require('gatsby-source-filesystem');

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions;
  // add slugs to all pages
  if (node.internal.type === 'Mdx') {
    const slug = createFilePath({ node, getNode, basePath: 'pages' });
    createNodeField({
      node,
      name: 'slug',
      value: slug,
    });
  }
};

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;

  return new Promise((resolve, reject) => {
    graphql('
      {
        allMdx {
          edges {
            node {
              fields {
                slug
              }
            }
          }
        }
      }
    ').then(result => {
      result.data.allMdx.edges.forEach(({ node }) => {
        createPage({
          path: node.fields.slug,
          component: path.resolve('./src/components/MDXLayout/index.js'),
          context: { slug: node.fields.slug },
        });
      });

      resolve();
    });
  });
};
`

**Comment by ChristopherBiscardi** [comment]
PR was merged. You can use the `ci` tag until there's an official release
