### ISSUE TITLE
MDX parser interprets "\n" in a string literal in a code block as a real new line in the code block.

### ISSUE THREAD

**Issue by WeZZard** [ChristopherBiscardi/gatsby-mdx#278]
**Describe the bug**
The MDX parser interprets "\n" in a string literal in a code block as a real new line in the code block.

**To Reproduce**
1. Write down a C string literal in a code block in an MDX document which contains "\n".
2. Use gatsby-mdx to render this document.
3. Fetch the code field of the MDX document with GraphQL.
3. The "\n" in the string literal in the code block was interpreted as a real new line in the code block.

**Expected behavior**
"\n" in string literal was interpreted as a "\n" in string literal.

**Comment by meritozh** [comment]
Do you use `prism-react-renderer` or `gatsby-remark-prism`? Consider #ga

**Comment by WeZZard** [comment]
Yes. I saw the solution and followed the step. But it always interprets "\n" in a string literal in a code block as a real new line. (Not eats new lines in a code block.)

**Comment by meritozh** [comment]
Yes, I have same issue😂. I must escape `\` myself.

**Comment by ChristopherBiscardi** [comment]
This is an interesting issue in core because of the way MDX transforms to template literals for content. It's being worked on but doesn't have a solution yet. [Here's a test](https://github.com/mdx-js/mdx/pull/366) that needs to pass if you're interested in solving it for the community at large :)

**Comment by meritozh** [comment]
@WeZZard Why use react katex component?

**Comment by WeZZard** [comment]
Because then I can wrap KaTex content with css module styled component and things go less dirty.

**Comment by ChristopherBiscardi** [comment]
This should be fixed in `@mdx-js/mdx@0.19`
