### ISSUE TITLE
gatsby-remark-custom-blocks throw  missing required "blocks" option

### ISSUE THREAD

**Issue by meritozh** [ChristopherBiscardi/gatsby-mdx#282]
**Describe the bug**
`options` passed to `gatsby-remark-custom-blocks` plugin is `nil`.

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro) and Steps to reproduce the behavior:

[issue demo commit](https://github.com/meritozh/gatsby-mdx-demo/commit/172fb55d5383c4c3842f615b68e8194ac43e3160)

https://github.com/gatsbyjs/gatsby/blob/45f4a23c00bd5ce4d1ddb68d6d16e22a06726767/packages/gatsby-remark-custom-blocks/src/index.js#L6

This line, raise error because `options` is nil.

**Expected behavior**

No error.

**Comment by meritozh** [comment]
I must use `pluginOptions` instead of `options`, but as https://github.com/ChristopherBiscardi/gatsby-mdx/issues/146#issuecomment-426714152 say, `options` should be work.

**Comment by ChristopherBiscardi** [comment]
Seems like we should ensure the plugins all take `options`. Going to re-open this until I get a chance to look into it.

**Comment by johno** [comment]
We're going to go ahead and close this because custom blocks should typically be replaced with a component in an MDX file.
