### ISSUE TITLE
hot update fails when using default layout

### ISSUE THREAD

**Issue by detj** [ChristopherBiscardi/gatsby-mdx#284]
**Describe the bug**
While using `options.defaultLayouts.default` layout option, react hot update fails with the following error.

```
VM3243:7 Uncaught ReferenceError: react__WEBPACK_IMPORTED_MODULE_0___default is not defined
    at Layout (eval at __reactstandin__regenerateByEval (index.mdx:48), <anonymous>:7:3)
    at ProxyFacade (react-hot-loader.development.js:793)
    at mountIndeterminateComponent (react-dom.development.js:14811)
    at beginWork (react-dom.development.js:15316)
    at performUnitOfWork (react-dom.development.js:18150)
    at workLoop (react-dom.development.js:18190)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:17437)
    at renderRoot (react-dom.development.js:18309)
    at performWorkOnRoot (react-dom.development.js:19165)
    at performWork (react-dom.development.js:19077)
    at performSyncWork (react-dom.development.js:19051)
    at requestWork (react-dom.development.js:18920)
    at scheduleWork (react-dom.development.js:18729)
    at Object.enqueueForceUpdate (react-dom.development.js:12496)
    at ExportedComponent../node_modules/react/cjs/react.development.js.Component.forceUpdate (react.development.js:393)
    at react-hot-loader.development.js:2411
    at Array.forEach (<anonymous>)
    at react-hot-loader.development.js:2410
Layout @ VM3243:7
Layout @ react-hot-loader.development.js:793
mountIndeterminateComponent @ react-dom.development.js:14811
beginWork @ react-dom.development.js:15316
performUnitOfWork @ react-dom.development.js:18150
workLoop @ react-dom.development.js:18190
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:17437
renderRoot @ react-dom.development.js:18309
performWorkOnRoot @ react-dom.development.js:19165
performWork @ react-dom.development.js:19077
performSyncWork @ react-dom.development.js:19051
requestWork @ react-dom.development.js:18920
scheduleWork @ react-dom.development.js:18729
enqueueForceUpdate @ react-dom.development.js:12496
./node_modules/react/cjs/react.development.js.Component.forceUpdate @ react.development.js:393
(anonymous) @ react-hot-loader.development.js:2411
(anonymous) @ react-hot-loader.development.js:2410
setTimeout (async)
updateInstances @ react-hot-loader.development.js:2403
(anonymous) @ react-hot-loader.development.js:2427
hotSetStatus @ bootstrap:217
hotApply @ bootstrap:599
cb @ process-update.js:66
(anonymous) @ process-update.js:82
Promise.then (async)
check @ process-update.js:81
./node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:42
processMessage @ client.js?path=/__webpack_hmr&reload=true&overlay=false:268
handleMessage @ client.js?path=/__webpack_hmr&reload=true&overlay=false:136
handleMessage @ client.js?path=/__webpack_hmr&reload=true&overlay=false:99
18:10:56.750 index.js:2177 The above error occurred in the <Layout> component:
    in Layout (created by MDXTag)
    in MDXTag (created by Context.Consumer)
    in Component (at pages/index.mdx:22)
    in MDXContent (created by HotExportedMDXContent)
    in AppContainer (created by HotExportedMDXContent)
    in HotExportedMDXContent (created by PageRenderer)
    in PageRenderer (created by JSONStore)
    in JSONStore (created by EnsureResources)
    in ScrollContext (created by EnsureResources)
    in RouteUpdates (created by EnsureResources)
    in EnsureResources (created by RouteHandler)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Root)
    in Root
    in MDXScopeProvider
    in _default

React will try to recreate this component tree from scratch using the error boundary you provided, MDXContent.
```

**To Reproduce**
Here's the link to my [`gatsby-mdx-minimal-repro`](https://github.com/detj/gatsby-mdx-minimal-repro/tree/hot-reload-issue). Branch name is `hot-reload-issue`.

To see the hot reload update failing, follow these steps
1. Run `npm run develop`
2. Open http://localhost:8000 in your browser
3. Open `src/components/layout.js`
4. Change the color in line no 20 from `green` to `red`
5. Hot module update error shows up in your browser

**Expected behavior**
Hot module update should have worked without any errors

**Screenshots**
<img width="1876" alt="screenshot 2019-02-04 20 22 21" src="https://user-images.githubusercontent.com/280236/52215709-a774f980-28ba-11e9-86d5-e99ea4ab9029.png">

**Additional context**
Don't have any contextual information to add. Please leave a comment if you have anything specific in mind. I'll be happy to help.

**Comment by detj** [comment]
@ChristopherBiscardi can you confirm if this is really a bug or am I missing something ?

**Comment by szarouski** [comment]
I'm not sure if my issue is exactly the same, but I also see that hot reload fails when you try to rename import. In order to reproduce:

- git clone https://github.com/LekoArts/gatsby-starter-minimal-blog
- cd gatsby-starter-minimal-blog
- npm i (or yarn)
- gatsby develop -p 8000
- open http://localhost:8000/use-component-in-mdx it will load as normal
- In https://github.com/LekoArts/gatsby-starter-minimal-blog/blob/master/blog/2018-01-03/index.mdx#L8 rename SpotifyPlayer to SpotifyPlayer1 everywhere
- observe ReferenceError: SpotifyPlayer1 is not defined

Looking forward for any suggestions. Restarting develop fixes things until new import, but this process is taking a while unfortunately.

Thanks

**Comment by ChristopherBiscardi** [comment]
@detj yeah, I'd consider any hot-reload issue like this to be a bug even though I believe you can refresh the page and it will show up fine. Help in fixing it is appreciated.

@szarouski Renaming imports sound like a problem with the `onCreateNode` implementation or more likely a cached value in the [mdx-scopes loader return value](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/0033bdfbe7c4f8b7fefbed71de4fa80f6d4678bf/packages/gatsby-mdx/wrap-root-element.js#L6). Either way, it's a different issue than the defaultLayouts/hot-reload issue mentioned here. I created a new issue for you at https://github.com/ChristopherBiscardi/gatsby-mdx/issues/291

**Comment by detj** [comment]
@ChristopherBiscardi Yes, refreshing the pages works for now. Will see if I can dig into this issue further.

**Comment by janosh** [comment]
Also ran into this issue except that in my case refreshing didn't help. Whatever component I imported couldn't be referenced even after recompiling the site. Had to remove the default layout as a workaround.
