### ISSUE TITLE
MDXProvider components ignored with wrapRootElement

### ISSUE THREAD

**Issue by n-batalha** [ChristopherBiscardi/gatsby-mdx#292]
**Describe the bug**
When setting the `components` of `MDXProvider` used in `wrapRootElement` (ssr/browser) these appear to be ignored. You can see this on the online demo as detailed below.

**To Reproduce**
In the [kitchen-sync example](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/master/examples/kitchen-sink):

* clone master, `cd examples/kitchen-sink && yarn && yarn develop`
* note that [h1 is modified in the root wrapper to be added a text "Provided: "](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/kitchen-sink/root-wrapper.js#L11)
* note that the root wrapper is used in [gatsby-browser](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/kitchen-sink/gatsby-browser.js) and [gatsby-ssr](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/kitchen-sink/gatsby-ssr.js)
* see the basic-md h1 header is unchanged. [this seems currently online](https://gatsby-mdx-kitchen-sink.netlify.com/basic-md/)

I find that reverting to `gatsby-mdx@0.3.6` "solves" the issue.

**Expected behavior**
html tags are changed according to `components`.

**Comment by ChristopherBiscardi** [comment]
Thanks for bringing this up. The kitchen-sink `wrapRootElement` is *outside* the gatsby-mdx plugin `wrapRootElement`. Not sure what the bet way to solve this is going to be :/

![image](https://user-images.githubusercontent.com/551247/53322207-93a42e00-388f-11e9-8d85-463318bf960d.png)

**Comment by ChristopherBiscardi** [comment]
v1.0 of mdx-js/mdx will include merging the MDXProvider by default, which solves this issue. In the meantime, components can be overridden by placing an MDXProvider lower in the tree, such as in wrapPageElement or a specific layout, etc.

**Comment by ChristopherBiscardi** [comment]
fixed in 0.4.2 of gatsby-mdx
