### ISSUE TITLE
[bug]: gatsby-plugin-emotion crashes dev server with html field

### ISSUE THREAD

**Issue by DSchau** [ChristopherBiscardi/gatsby-mdx#295]
## Description

Using gatsby-mdx in conjunction with gatsby-plugin-emotion makes the `html` field throw an error, when requested via GraphQL.

Specifically, it throws:

```
ReferenceError: document is not defined
    at createCache (evalmachine.<anonymous>:1148:38)
    at Module../node_modules/@emotion/core/dist/core.browser.esm.js (evalmachine.<anonymous>:1293:149)
    at __webpack_require__ (evalmachine.<anonymous>:724:30)
    at fn (evalmachine.<anonymous>:101:20)
    at Module.<anonymous> (evalmachine.<anonymous>:4586:117)
    at Module../node_modules/gatsby-mdx/utils/wrap-root-render-html-entry.js (evalmachine.<anonymous>:4633:30)
    at __webpack_require__ (evalmachine.<anonymous>:724:30)
    at evalmachine.<anonymous>:791:100
    at evalmachine.<anonymous>:794:10
    at Script.runInContext (vm.js:134:20)
```

When attempting to build with this field requested, the error is more confusing:

```
error gatsby-node.js returned an error


  Error: Cannot read property 'push' of undefined
  
  - defaultMergedResolver.js:15 defaultMergedResolver
    [mdx-html-issue]/[graphql-tools]/dist/stitching/defaultMergedResolver.js:15:36
  
  - mergeSchemas.js:214 field.resolve
    [mdx-html-issue]/[graphql-tools]/dist/stitching/mergeSchemas.js:214:24
```

## Reproduction

1. [`git clone git@github.com:DSchau/mdx-html-issue.git`](https://github.com/DSchau/mdx-html-issue)
1. `yarn start`
1. Open up `http://localhost:8000/___graphql` and use the following query
    ```graphql
    {
      mdx(fields:{
        slug:{
          eq:"/hello/"
        }
      }) {
        html
      }
    }
    ```
1. The dev server will crash and the error will be logged to the console

## Expected Behavior

The dev server will not crash

This is in regards to some recent weirdness that @kentcdodds experienced with his Gatsby re-write of his blog. See kentcdodds/kentcdodds.com#36 for a similar issue, although I think that may be OOMing with the overhead of compiling for _each_ request to html.

**Comment by DSchau** [comment]
I'll take a deeper look at this, just wanted to get something up for now.

I think the OOM issues are pretty interesting on @kentcdodds site above, too.

**Comment by mmmaaatttttt** [comment]
Hey @DSchau! Does changing the field to `code.body` help? (see #250)

**Comment by DSchau** [comment]
Not really! The use case for this is exactly what Chris specified in the linked issue—namely RSS feeds.

Thank you though!!

**Comment by ChristopherBiscardi** [comment]
hmm, so I can replicate this error in GraphiQL for my own site (which also uses gatsby-mdx+emotion), but the RSS feed for my build succeeds as well, as you can see here: https://www.christopherbiscardi.com/rss.xml

**Comment by ChristopherBiscardi** [comment]
(The OOM issues are also very interesting and is likely related to many webpack processes being spun up for the `html` field. Not sure the best way to solve that yet.)

**Comment by DSchau** [comment]
@ChristopherBiscardi yeah definitely. Should I open up a separate issue for that since it's different enough? Or is this issue fine?

**Comment by ChristopherBiscardi** [comment]
@DSchau yes please, open a new one. I think I have an idea to fix (think dataloader + multiple webpack entries) it so would would like to track it separately.

**Comment by johngrasty** [comment]
@ChristopherBiscardi  I can confirm that I also see this issue on your `gatsby-mdx-minimal-repo` with does not include emotion.

**Comment by z0al** [comment]
> hmm, so I can replicate this error in GraphiQL for my own site (which also uses gatsby-mdx+emotion), but the RSS feed for my build succeeds as well, as you can see here: https://www.christopherbiscardi.com/rss.xml

@ChristopherBiscardi  Maybe unrelated, but your RSS feeds need a fix. All `<content:encoded>` tags have the same (broken) body:

```xml
<content:encoded>
<style data-emotion-css="1v0t7aq">*{margin:0;padding:0;box-sizing:border-box;}body{background:#2E3440;}</style><div></div>
</content:encoded>
```

**Comment by ChristopherBiscardi** [comment]
@z0al possibly related. this section of code is particularly tricky. Need to find a way to simplify it if possible.

**Comment by ChristopherBiscardi** [comment]
This is fixed now as far as I'm aware. It works on the original site now (here's the PR -- https://github.com/ChristopherBiscardi/kentcdodds.com/pull/1)

**Comment by ChristopherBiscardi** [comment]
You have to be on MDX 1.0 and gatsby-mdx 0.6 for this to work btw
