### ISSUE TITLE
Should we use babel-loader or loaders.js()?

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#3]
Right now the plugin is using `babel-loader` in the webpack config. Should it use `loaders.js()`?

**Comment by ChristopherBiscardi** [comment]
I [swapped to loaders.js()](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/71a920b2f3bc1f242bda439124a82d34e02e5e3b/packages/gatsby-mdx/gatsby-node.js#L68) because babel-loader needed configuration and loaders.js did not (presumably because it's already configured)

**Comment by KyleAMathews** [comment]
Yeah, that way you just inherit the default or site Babel config.
