### ISSUE TITLE
MDXRenderer breaks in IE11

### ISSUE THREAD

**Issue by AlmeroSteyn** [ChristopherBiscardi/gatsby-mdx#301]
**Describe the bug**
When using `MDXRenderer` to render precompiled MDX, it breaks in IE11.

I am aware of #189 but this is still happening with the latest version of `0.3.x` and that issue moved towards standard MDX rendering instead of `MDXRenderer`.

**To Reproduce**
This already occurs on the  [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro). When you run this in IE and go to page 3, IE11 gives a syntax error and crashes.

I have even tried to use `gatsby-plugin-compile-es6-packages` to precompile `gatsby-mdx` but it seems to make no difference.

If I am missing something to get this fixed with the latest `ci` version please let me know.

**Expected behavior**
It should be backwards compatible with IE11

**Comment by AlmeroSteyn** [comment]
Further info.

It seems to break on this time in `MDXRenderer`:

```
    const fn = new Function("_fn", ...keys, `${children}`);

**Comment by AlmeroSteyn** [comment]
Further info.

I am pretty sure now that it is the transpile of the MDX.

I assume it could be fixed in this line in `mdx-loader` : 

```
    const result = babel.transform(code, {
      configFile: false,
      plugins: [
        require("@babel/plugin-syntax-jsx"),
        require("@babel/plugin-syntax-object-rest-spread"),
        require("../utils/babel-plugin-html-attr-to-jsx-attr")
      ]
    });
```

But for the life of me I cannot find the right config to make this happen. Am I on the right track?

**Comment by ChristopherBiscardi** [comment]
> When you run this in IE and go to page 3, IE11 gives a syntax error and crashes.

what is the output of the syntax error?

Generally, gatsby-mdx's files and the [MDX output from mdx-loader](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/25cce51f41677fde33a525fe4af6599ed292ad22/packages/gatsby-mdx/gatsby/create-webpack-config.js#L57) is set up to use the babel config the site supplies, so my guess would be that the site's babel config isn't IE11 compatible. It's hard to say without seeing the actual error though.

**Comment by AlmeroSteyn** [comment]
Thanks for responding!

The reason I said `syntax error` is because that is all it gives, being IE11.

I initially assumed that the correct `.babelrc` is loaded in Gatsby. And I still think that should have worked. But I did try to override the Babel config as shown here: https://www.gatsbyjs.org/docs/babel/

However, even targeting IE11 specifically does not work.

I bumped the version of the minimal repo to the ones I am currently using and pushed it here: https://github.com/AlmeroSteyn/gatsby-mdx-minimal-repro

If I run this in develop mode and I browse to `/page-3-generated-url/` I get the following in IE. The console shows a number of error. However they are not too descriptive:

![image](https://user-images.githubusercontent.com/5063473/53637295-0ceea880-3c23-11e9-92ab-3dc203656e07.png)

![image](https://user-images.githubusercontent.com/5063473/53637305-12e48980-3c23-11e9-9da5-f73071019e56.png)

The stacktrace is:

```
"SyntaxError: Syntax error\n   at _construct (http://localhost:8000/commons.js:3609:7)\n   at _construct (http://localhost:8000/commons.js:3615:3)\n   at Anonymous function (http://localhost:8000/commons.js:10974:3)\n   at ProxyFacade (http://localhost:8000/commons.js:42810:7)\n   at renderWithHooks (http://localhost:8000/commons.js:27993:3)\n   at mountIndeterminateComponent (http://localhost:8000/commons.js:29970:5)\n   at beginWork (http://localhost:8000/commons.js:30575:9)\n   at performUnitOfWork (http://localhost:8000/commons.js:34262:5)\n   at workLoop (http://localhost:8000/commons.js:34302:7)\n   at renderRoot (http://localhost:8000/commons.js:34385:7)\n   at performWorkOnRoot (http://localhost:8000/commons.js:35292:7)\n   at performWork (http://localhost:8000/commons.js:35204:7)\n   at performSyncWork (http://localhost:8000/commons.js:35178:3)\n   at requestWork (http://localhost:8000/commons.js:35047:5)\n   at scheduleWork (http://localhost:8000/commons.js:34861:5)\n   at scheduleRootUpdate (http://localhost:8000/commons.js:35522:3)\n   at updateContainerAtExpirationTime (http://localhost:8000/commons.js:35550:3)\n   at updateContainer (http://localhost:8000/commons.js:35607:3)\n   at ReactRoot.prototype.render (http://localhost:8000/commons.js:35903:3)\n   at Anonymous function (http://localhost:8000/commons.js:36040:9)\n   at unbatchedUpdates (http://localhost:8000/commons.js:35409:3)\n   at legacyRenderSubtreeIntoContainer (http://localhost:8000/commons.js:36036:5)\n   at ReactDOM.render (http://localhost:8000/commons.js:36105:5)\n   at Anonymous function (http://localhost:8000/commons.js:1024:7)"
```

It actually breaks on the following line of `MDXRenderer`:

```
const fn = new Function("_fn", ...keys, `${children}`);
```

In the transpiled code the actual failure happens in the following function:

```
function _construct(Parent, args, Class) {
  if (isNativeReflectConstruct()) {
    module.exports = _construct = Reflect.construct;
  } else {
    module.exports = _construct = function _construct(Parent, args, Class) {
      var a = [null];
      a.push.apply(a, args);
      var Constructor = Function.bind.apply(Parent, a);
      var instance = new Constructor();
      if (Class) setPrototypeOf(instance, Class.prototype);
      return instance;
    };
  }

  return _construct.apply(null, arguments);
}

```

Once the `new Constructor()` is called it breaks.

All attempts in changing the Babel config has failed so far.

In production the code also crashed IE.

We currently have a live site that needs to function in IE and isn't so any help from you to get this fixed will really be appreciated.

**Comment by ChristopherBiscardi** [comment]
It looks like the introduction of https://github.com/mdx-js/mdx/blob/589f29355c61e7eba316b31119b1ecee0687248e/packages/mdx/mdx-hast-to-jsx.js#L135 in mdx-js/mdx resulted in this output for MDX content:

function _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; } function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; } const layoutProps = {}; return class MDXContent extends React.Component { constructor(props) { super(props); this.layout = (_ref) => { let { children } = _ref, props = _objectWithoutProperties(_ref, ["children"]); return React.createElement(Layout, props, children); }; } render() { const _this$props = this.props, { components } = _this$props, props = _objectWithoutProperties(_this$props, ["components"]); return React.createElement(MDXTag, { name: "wrapper", Layout: this.layout, layoutProps: Object.assign({}, layoutProps, props), components: components }, React.createElement(MDXTag, { name: "h1", components: components }, `Hi from the third page`), React.createElement(MDXTag, { name: "p", components: components }, `Welcome to page 3. This page is generated through createPages`), React.createElement(Link, { to: "/" }, "Go back to the homepage"), React.createElement(Link, { to: "/page-2/" }, "Go to page 2")); } } MDXContent.isMDXComponent = true;


Note that the introduction of `MDXContent.isMDXComponent = true` comes without a semicolon, so breaks in IE11.

**Comment by ChristopherBiscardi** [comment]
also seeing that `class` isn't compiled by default, which breaks in IE11

**Comment by AlmeroSteyn** [comment]
Thanks for checking!

Is there a workaround I could do to get our site working in IE at the moment?

**Comment by ChristopherBiscardi** [comment]
yeah, but you'd have to not use the MDXRenderer (either createPages with the MDX file as the component or use the src/pages support). 

The real fix is going to be adding compilation to the babel transform in `gen-mdx`. It's [similar code](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/25cce51f41677fde33a525fe4af6599ed292ad22/packages/gatsby-mdx/utils/gen-mdx.js#L108-L112) to the one you pointed out in `mdx-loader`, but complicated by the face that it's returning a function body, which is why we're replacing the [`export default` with `return`](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/25cce51f41677fde33a525fe4af6599ed292ad22/packages/gatsby-mdx/utils/gen-mdx.js#L129). I'd 100% accept a PR to fix this, ideally by applying the user's babel config like we do elsewhere, but also in the meantime I'd accept a minimal addition (if just adding the class transform works, for example).

**Comment by dominicfallows** [comment]
Would adding `@babel/preset-env` to the array of presets at https://github.com/ChristopherBiscardi/gatsby-mdx/blob/25cce51f41677fde33a525fe4af6599ed292ad22/packages/gatsby-mdx/utils/gen-mdx.js#L111 do it?

Just trying to understand to see if I can help at all

**Comment by AlmeroSteyn** [comment]
@dominicfallows yeah it does. Just did that in PR #306 earlier :)

**Comment by crazypixel** [comment]
@ChristopherBiscardi 
still breaks in IE11. 
how can I fix this? using mdxRenderer and when im using React components everything crashes.
