### ISSUE TITLE
[bug]: HMR performance is a bit slower than ideal

### ISSUE THREAD

**Issue by DSchau** [ChristopherBiscardi/gatsby-mdx#302]
## Description

HMR with a site of reasonable size (e.g. 100+ mdx files, images, etc.) seems to be significantly delayed, especially when compared to something like gatsby-transformer-remark--which is admittedly doing quite a bit less.

If a picture says 1000 words, then a video says a whole hell of a lot. See below 👇

## Reproduction

It's not a _minimal repo_ but it's minimal and real-world enough that it will be helpful to use.

[Kentcdodds.com](https://github.com/kentcdodds/kentcdodds.com)

1. Clone, install, etc.
1. Run `yarn dev`
1. Edit a file, e.g. `content/blog/2018-in-review/index.md`
1. Wait ~5 seconds for the change to appear
    - Note: there's an unrelated Gatsby regression with an over-eager warning; we'll fix

## Expected Behavior

Content should reload in a reasonable timespan, e.g. ~1 second or so on most machines.

## Additional Context

It's possible some low-hanging fruit (e.g. caching, general performance optimizations, etc.) will pay off huge dividends in this, and some small, easy fixes should pay off handsomely.

## Video

[Google Drive Link](https://drive.google.com/file/d/1tanl-UUTf_CSQ7rC8nadJ1jZIMgibkaW/view?usp=sharing)

(let me know if the above doesn't work for whatever reason)

cc @kentcdodds

**Comment by ChristopherBiscardi** [comment]
I fixed the HMR issue by adding some caching in a livestream. Video here for anyone interested: https://youtu.be/Nz0UXVvqP2Q?t=854

We brought kent's site down from 20s+ to ~3s for HMR speed.

fix is out in `0.4.4`
