### ISSUE TITLE
New lines disappear from code-blocks using gatsby-remark-prismjs

### ISSUE THREAD

**Issue by phenax** [ChristopherBiscardi/gatsby-mdx#305]
**Describe the bug**
I am using gatsby-mdx with gatsby-remark-prismjs. The syntax highlighting works this way but for some reason, the entire code appears in one line.

**To Reproduce**
My config for mdx and remark looks something like this.
```js
  {
      resolve: 'gatsby-mdx',
      options: {
        extensions: ['.mdx', '.md'],
        frontmatter: true,
        defaultLayout: require.resolve('./src/blog-layout.tsx'),
        gatsbyRemarkPlugins: [
          {
            resolve: 'gatsby-remark-prismjs',
            options: {
              inlineCodeMarker: '=>',
              showLineNumbers: true,
            },
          },
        ],
      },
    },
```

Here's the project I'm facing this issue in -> https://github.com/phenax/phenax.github.io

**Expected behavior**
Expected the newlines to be maintained as coded in the codeblock.

**Screenshots**
What I wrote
![screenshot from 2019-03-03 12-56-23](https://user-images.githubusercontent.com/11407672/53692357-56bac880-3db4-11e9-87b1-2d9ac0b4a507.png)

What I got
![screenshot from 2019-03-03 12-55-57](https://user-images.githubusercontent.com/11407672/53692360-6508e480-3db4-11e9-9f2f-84549593168e.png)

**Comment by ChristopherBiscardi** [comment]
hey, thanks for filing an issue! We just changed a lot of the escaping code for codeblocks between v0.17 and v0.20 of @mdx-js/mdx. Can you upgrade and let me know if that helps? the current version is `0.20.1`

**Comment by phenax** [comment]
Hey @ChristopherBiscardi, Updating @mdx-js/mdx to 0.20.1 did the trick! Thanks!

**Comment by Beingbook** [comment]
@ChristopherBiscardi This looks happened again.

my deps are
```
"gatsby-mdx": "^0.6.2",
"@mdx-js/tag": "^0.20.3",
"@mdx-js/mdx": "^1.0.4",
```

demo: https://blog.beingbook.dev/posts/initial-post
code: https://github.com/Beingbook/blog/blob/master/src/posts/initial-post.mdx

I inserted `{'\n'}` to make new line. but it doesn't make sense.

**Comment by Beingbook** [comment]
I also tried to solve this with `"@mdx-js/tag": "^1.0.0-alpha.6"` but it doesn't work

**Comment by johno** [comment]
Hey @Beingbook `@mdx-js/tag` has been dropped in v1 in favor of `@mdx-js/react`. [See the migration guide](https://mdxjs.com/migrating/v1/#%EF%B8%8F-breaking-changes).

**Comment by Beingbook** [comment]
@johno // oops. Actually, I'm already using `@mdx-js/react`. https://github.com/Beingbook/blog/blob/master/src/components/ArticleLayout.tsx

**Comment by johno** [comment]
Okay, cool. Thanks. We'll look into it!

**Comment by ChristopherBiscardi** [comment]
This [is fixed](https://github.com/mdx-js/mdx/pull/533) in `@mdx-js/mdx@1.0.7`
