### ISSUE TITLE
With defaultLayouts, what are the advantages? 

### ISSUE THREAD

**Issue by kuworking** [ChristopherBiscardi/gatsby-mdx#309]
_As far as I think to know_, there are 2 ways (I'd say) to create `mdx-based` pages:  

- **The classical way**
With the plugin having parsed all `.mdx` files adding the `allMdx` nodes to `graphQL`, I can programmatically create a page for each node with `gatsby-node.js` where I'd run there a general query to know the number of items I have, and in the `template` I'd run a specific query for the page being created

- **The plugin way (I think)**
Where each `.mdx` file is indeed a page, rendered as a page, where I can use a template as specified in `gatsby-config -> defaultLayouts`. There I can only run `static queries`, but I don't even need them since the file **is** already the article, I have already everything there

In my view, the plugin way is the spectacular thing here because it simplifies the whole process

The problem is that I lose the access to specific `graphQL` queries. Why do I want this? In my case, to get access to the `words` and the `time-to-read` fields that the plugin nicely calculates

To do so, I have to static-query for all MDX nodes, and then find mine and go along. I can see though that this will be a bottleneck once I have my hundreds of thousands of posts published (not really). There I would benefit of being able to query just for the article of the file

What are your thoughts?

**Comment by ChristopherBiscardi** [comment]
First, a couple notes:

* you can make GraphQL queries from your MDX file in src/pages
* there is no way to specify a single query for an entire set of `.mdx` files in `src/pages`, although it has been discussed in #213 

using the`src/pages` support is a nice way to start using MDX and perhaps we should do the work described in #213, but also the more functionality we add like that the further we get from "the gatsby way" which means people have to learn special MDX APIs to do things Gatsby already does. The "classical way", as you call it, supports literally everything Gatsby can do by default while the "src/pages" way will only ever support a subset.

**Comment by kuworking** [comment]
I agree that the "classical way" is superior to "src/pages"

I guess this is a tendency towards simplification. Before I needed `gatsby-node` to parse all `.md` files from a folder in order to modify them (at my taste) and create pages from them. But now with `.mdx` files I can directly add styled components there, I can do anything so it's no longer necessary for me to modify them (which is fantastic). And then, I've wondered why do I need the `gatsby-node` boilerplate to create pages after all? With the template in the plugin is enough

As you say, one reason to use `gatsby-node` would be to provide specific queries to each page, which now it is not possible with only the template. But likely a #213 default query with the option of filtering by the name of the respective file would make it :)

_*should I close the issue?_

**Comment by ChristopherBiscardi** [comment]
If the .mdx files in `src/pages` works for your use case, then by all means feel free to use it! It will always be a subset of the functionality possible with `createPages`, so keep that in mind if you end up feeling friction later on as you try to "do more" with your pages. It may make sense to switch at that future point.

The other thing that `createPages` works well with (and `src/pages` can work less well with) is [Gatsby themes](https://www.gatsbyjs.org/blog/2019-03-11-gatsby-themes-roadmap/) because you can customize the handling, templates, etc resulting in only needing a directory of markdown files to build a site.

Since we have #213 to follow up, I'll close this. Thanks for the question :)
