### ISSUE TITLE
`gatsby-remark-copy-linked-files` no longer has `html` nodes to visit

### ISSUE THREAD

**Issue by danoc** [ChristopherBiscardi/gatsby-mdx#311]
**Describe the bug**

Hi! The bug is that `gatsby-remark-copy-linked-files` can no longer find some linked files within `.mdx` documents. Markdown format links (`[https://example.com](foo)`) and images (`![foo](./bar.png)`) still work but HTML tags (`<img />` and `<a>`) do not.

This is happening because there was a change in `@mdx-js/mdx` (or further downstream?) that changed the AST. Nodes that were previously `type: html` are now recognized as `type: jsx`.

`gatsy-remark-copy-linked-files` skips over the JSX node and doesn't find the linked files. Previously, the plugin worked because [it visits `html` nodes](https://github.com/gatsbyjs/gatsby/blob/3834b2bce5edc60cd5386561498ca29f028c1d30/packages/gatsby-remark-copy-linked-files/src/index.js#L206).

I'm 95% sure that this was introduced between versions `0.16.8` and `0.20.1` of `@mdx-js/mdx`. I've dug into this for a while but am having trouble pin-pointing a specific commit. 

This is a downstream issue, but I'm filing it here since it's specific to MDX usage within Gatsby.

**To Reproduce**

This is not super minimal, but you can reproduce by checking out this commit (https://github.com/thumbtack/thumbprint/pull/154/commits/d1632c318ee6156fed289637d73d15c0282ef138) and running `yarn && cd www && yarn build && yarn gatsby serve`. Then, visit http://localhost:9000/components/modal-default/usage/ and notice that the image 404s.

I can make a smaller reproduction if needed. 😄 

**Expected behavior**
Expect images to load.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ChristopherBiscardi** [comment]
> Nodes that were previously type: html are now recognized as type: jsx.

https://github.com/mdx-js/mdx/pull/429#issuecomment-468859464 might be the PR you're looking for related to this issue. Notably, [this line](https://github.com/mdx-js/mdx/pull/429/files#diff-ff62a009e9c994d68c5fbf3e46288807R64) moved from "after md plugins" to "before md plugins". Which points us to (yet another) interesting problem with gatsby-remark plugins :/

From the position of MDX, the input from the user is `jsx` (not `html`), so the nodes were previously mis-classified, but the above PR means we don't get the accidental compatibility with gatsby-remark plugins that operate on `html` nodes.

So, how do we "re-use" gatsby-remark plugins that operate on `html` to operate on `jsx` input? The real solution is probably to add `jsx` node operation upstream in gatsby-remark-copy-linked-files, so something like:

```js
visit(markdownAST, `jsx`, node => {
  
})
```

That puts us dangerously close at needing an extra plugin for each gatsby-remark plugin that operates on `html` nodes though :/

**Comment by danoc** [comment]
> So, how do we "re-use" gatsby-remark plugins that operate on `html` to operate on `jsx` input? The real solution is probably to add `jsx` node operation upstream in gatsby-remark-copy-linked-files, so something like:

Yeah, I agree with this. Do you think I should file this as an issue in the Gatsby codebase?

**Comment by ChristopherBiscardi** [comment]
@danoc yes, I believe it should be an issue on the gatsby repo. Ping me in it and I can add context if necessary

**Comment by danoc** [comment]
Ok great, just made it. I'll close this one in the meantime. 🙇
