### ISSUE TITLE
expose ast to graphql

### ISSUE THREAD

**Issue by leonardodino** [ChristopherBiscardi/gatsby-mdx#313]
**Is your feature request related to a problem? Please describe.**
I'm dealing with some document's that have some kind of rich data embedded. 

They all use React components for formatting, etc. I would like to extract the data being passed during the gatsby build, for use in indexes, feeds, and other means of aggregating them.

Having the AST without having to parse the document again would save time, and avoid a potential mismatch between the different parsing configuration.

**Describe the solution you'd like:**
Would be awesome to have mdxast/mdast exposed on the graphql, or some other means (on my case it would be useful either in the `onCreateNode` or `createPages` via graphql).

**Describe alternatives you've considered**
vendoring/copy-pasting the parsing code into my project :/

**Additional context**
N/A

**Comment by ChristopherBiscardi** [comment]
yeah I think we should do this. Would accept a PR for it.

We're actually mostly set up for it. See [here](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/f85179eefc7af40edb65a72100315741c22542eb/packages/gatsby-mdx/utils/gen-mdx.js#L59) where we need to store the generated ASTs and [this file](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/f85179eefc7af40edb65a72100315741c22542eb/packages/gatsby-mdx/gatsby/extend-node-type.js) where we need to add the ASTs to the graphql schema.

**Comment by Kadrei** [comment]
I am currently looking into it and got some `graphQL` output by simply adding:

```
      mdxAst: {
        type: GraphQLJSON,
        async resolve(mdxNode) {
          const { mdast } = await processMDX({ node: mdxNode });
          return mdast;
        },
      },
```

to `extend-node-type.js`.

Sadly I have not enough knowledge to understand why we need to touch `gen-mdx.js` like you proposed.

Maybe you can explain the need further?

**Comment by ChristopherBiscardi** [comment]
@Kadrei looks like that PR would be enough these days. What are you using the mdast for?

**Comment by Kadrei** [comment]
@ChristopherBiscardi I am in the process on adapting https://github.com/sarasate/gate to be used with mdx to enable more dynamic content. While checking the code of that project I found that they use `htmlAst` from `remark` at least and came to the conclusion that this functionality might not be possible with gatsby-mdx. While checking again it might just be that it is only used for mapping to custom elements (which is supported by gatsby-mdx already). I hadn't had time to check this further but it is possible I do not need that feature at all.
But will still open the PR tomorrow as it seems others might need it.

**Comment by ChristopherBiscardi** [comment]
mdast is now exposed in #387
