### ISSUE TITLE
Working LiveCode Example using children as code 

### ISSUE THREAD

**Issue by jcameronjeff** [ChristopherBiscardi/gatsby-mdx#315]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jcameronjeff** [comment]
Can't for the life of me get my programmatically generated pages to use the code component I assign in my Layout.js, or in rootWrapper.js.  Tried every which way based on the docs. The closest I've gotten is getting [object, object] instead of children code. 

![Screen Shot 2019-03-20 at 11 13 17 AM](https://user-images.githubusercontent.com/32875696/54695989-5be07d00-4b01-11e9-9cc2-ffddb81e1fb8.png)
![Screen Shot 2019-03-20 at 11 14 28 AM](https://user-images.githubusercontent.com/32875696/54696092-93e7c000-4b01-11e9-9375-8c96c0411a4a.png)
 
![Screen Shot 2019-03-20 at 11 13 30 AM](https://user-images.githubusercontent.com/32875696/54696112-9ea25500-4b01-11e9-9ba3-40e5ebbf79e6.png)

**Comment by shripadk** [comment]
@jcameronjeff Just wrap your code that needs to show up in the `<LiveEditor>` within ``` blocks instead of wrapping it within `<code>` like so:

    ```jsx
     <div>hi guys!</div>
    ```

You can also pass custom props! I use it when I need to, for instance, conditionally render the Editor. Previously I was using `globalScope`: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/239 but until it lands in 1.0 I have decided to follow this route (as I am already using react-live). You can use custom props to only render LivePreview where required like so:

    ```jsx hideLiveEditor=true
    <div>With custom props</div>
    ```

This shows up as `{ hideLiveEditor: true }` in `MyCodeComponent` props.

Hope this helps! :smile:

**Comment by johno** [comment]
Thanks for the assist @shripadk! Here are a few more resources to help achieve what you're looking for:

- 📚 https://mdxjs.com/guides/live-code
- 📹 https://egghead.io/lessons/react-create-a-live-code-component-with-gatsby-mdx-and-react-live?pl=building-websites-with-mdx-and-gatsby-161e9529
