### ISSUE TITLE
Creating mdx node in bootstrap sequence

### ISSUE THREAD

**Issue by raphadeluca** [ChristopherBiscardi/gatsby-mdx#33]
Is there a way to create a mdx node from a text being imported during the bootstrap sequence from another source than the local files (from a CMS or firebase)? 
To produce a md node from outside, I can do: 
```javascript
exports.onCreateNode = ({ node, actions}) => {
  const { createNode } = actions;
  if (node.internal.type === `Chapter`) {
    createNode({
      id: `md-${node.id}`,
      parent: node.id,
      children: [],
      internal: {
        type: `${node.internal.type}Markdown`,
        mediaType: `text/markdown`,
        content: node.name,
        contentDigest: node.internal.contentDigest
      }
    })
  }
}
```
This way I create an allChapterMarkdown node. Is there a similar way to create a kind of allChapterMdx?
The goal is being able to write mdx content  in a file stored in a database or in a CMS markdown editor that will be processed as a mdx file in Gatsby.

Thanks

**Comment by ChristopherBiscardi** [comment]
hmm, This definitely sounds like something we'll have to support.

Right now, it seems like the best option is to offer something like this:

```js
exports.onCreateNode = ({ node, actions}) => {
  const { createNode } = actions;
  if (node.internal.type === `Chapter`) {
    createNode(makeMdxNode({ node, rawMdxContent: node.content }))
  }
}
```

Then we can use the same node structure as we use internally in both places without consumers having to worry about manually constructing it. `makeMdxNode` would write out an mdx file from the API call into the cache and offer the path in the `fileAbsolutePath` field of the graphql schema, so you can pass that into `createPage` as normal and also resolve the appropriate `require`s in the mdx file.

---

the key missing piece from `gatsby-mdx`'s perspective is an easy way to write out the file into the cache, which looks like it can be pulled out of [gatsby-source-filesystem](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js) and generalized.

**Comment by raphadeluca** [comment]
That sounds great! I am on the right way if i implement the `makeMdxNode` function using the [gatsby-mdx/packages/gatsby-mdx/on-create-node.js](url) logic?

**Comment by ChristopherBiscardi** [comment]
yeah totally. that'll give you the right node structure. The only other part should be choosing where to write out the files (probably into the cache, like the filesystem source does for remote content). In gatsby-mdx we'll abstract that logic to be used in the `on-create-node` file and also offered as the `makeMdxNode` export.

**Comment by raphadeluca** [comment]
It will be a very useful functionality! I will give a try on my side, see if we can use `createRemoteFileNode` and `createNodeField`  in conjunction with mdx's on-create-node.

**Comment by ChristopherBiscardi** [comment]
@raphadeluca We now have this as of 0.0.11 using the [transformers](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b1ec4c8375276b9da847cc8b05f18d41d1dceb2e/examples/using-contentful/gatsby-config.js#L22-L28). In this example, we take a contentful data type and turn it into an mdx node:

```js
{
  resolve: `gatsby-mdx`,
  options: {
    transformers: {
      ContentfulBlogPost: ({ node, getNode }) => {
        const { title } = node
        const mdxContent = getNode(node.mdxContent___NODE)
        return { meta: { title }, content: mdxContent.mdxContent }
      },
    },
}
```


Note that you'll have to use the graphql method of querying and displaying MDX, which is shown in the [using-contentful](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/using-contentful/gatsby-node.js#L17-L29) example but isn't documented in the README yet.

You'll use `componentWithMDXScope` in the createPage call.

```js
createPage({
  path: post.node.fields.slug,
  component: componentWithMDXScope(
    blogPost,
    post.node.code.scope,
    __dirname
  ),
  context: {},
})
```

and `MDXRenderer` to [render the mdx content](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/cbbe5c01e0dffc882b95ae6113a51f3874412473/examples/using-contentful/src/templates/contentful-post.js#L35-L37)

```jsx
<MDXRenderer scope={this.props.__mdxScope}>
  {post.code.body}
</MDXRenderer>
```

**Comment by loremipson** [comment]
@ChristopherBiscardi it doesn't look like this is the way to handle this anymore. The contentful example no longer has `transformers` in the options object. Looking through it, I haven't been able to find where the mdx is actually sourced remotely from contentful. Is that no longer happening?

**Comment by ChristopherBiscardi** [comment]
@loremipson this happens automatically now. You should be able to get the mdx node as a child of the relevant contentful type (like in the query below). This is how gatsby is set up for transformers to work, so we got rid of the old manual transformers functionality. It should also be accessible from `allMdx` as usual.

```graphql
  allContentfulThing{
    edges{
      node{
        title
        childContentfulThingContentTextNode{
          childMdx{
            frontmatter{
              title
            }
          }
        }
      }
    }
  }
```

Here's a tweet that shows both methods: 

https://twitter.com/chrisbiscardi/status/1042130354042093568

**Comment by loremipson** [comment]
Ah, cool!

It looks like it's safe to assume that this is just a feature of contentful integration for now? I'm actually trying to source MDX from wordpress' `content` on my end.

I have a really messy solution in place for this right now, but I'm running into problems with the async side of gatsby's build. And this solution seems far more elegant than what I've got.

**Comment by ChristopherBiscardi** [comment]
ah if you're trying to do wordpress, can you either comment on #148 with what you're doing, where you're hitting problems, etc? or file a new issue if you feel like #148 doesn't apply?
