### ISSUE TITLE
Support Markdown in nested HTML

### ISSUE THREAD

**Issue by morloy** [ChristopherBiscardi/gatsby-mdx#330]
**Is your feature request related to a problem? Please describe.**
Currently, `gatsby-mdx` crashes on Markdown in nested HTML.
Example:
```
<div>

* list

</div>
```
Works.

```
<div>
  <div>

  * list

  </div>
</div>
```
Crashes! Resulting in something like:
```
error UNHANDLED REJECTION


  SyntaxError: unknown: Expected corresponding JSX closing tag for <MDXTag> (30:0)
    28 | <MDXTag name="li" components={components} parentName="ul">
    29 | <MDXTag name="p" components={components} parentName="li">{`list`}</MDXTag>
  > 30 | </div>
       | ^
    31 | </MDXTag>
    32 | </MDXTag>
    33 | </div>
```

**Describe alternatives you've considered**
Don’t use Markdown in nested HTML, but use HTML for the entire section.

**Comment by morloy** [comment]
Noticed that this is also an issue in https://github.com/mdx-js/mdx/issues/486

**Comment by ChristopherBiscardi** [comment]
@morloy yep, also I'd try the 1.0 which has some changes when filing an issue there.
