### ISSUE TITLE
graphql will throw error when some field is null

### ISSUE THREAD

**Issue by wulucxy** [ChristopherBiscardi/gatsby-mdx#340]
**Describe the bug**
I have some mdx file frontmatters：

```
---
title: markdown 拓展
root: "/docs"
order: 6
parents: ["开发指南"]
prev: 基本配置
---
```

and the graphql things is like this:

```
query {
    allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___order] }, limit: 1000) {
      edges {
        node {
          fields {
            slug
          }
          frontmatter {
            title
            prev
            next
          }
        }
      }
    }
    allMdx {
      edges {
        node {
          fields {
            slug
          }
          frontmatter {
            title
            prev
            next
          }
        }
      }
    }
  }
`)
```

then graphql will throw an error because the frontmatter do't have `next` field，which is reasonable，because it is the last doc。

and I see `allMarkdownRemark` is compatible with null。

**Expected behavior**

just gave me null when the leaf node is null。

**Screenshots**

![image](https://user-images.githubusercontent.com/5326403/55375469-d87e4d00-553e-11e9-988a-64e280447a26.png)

**Comment by wulucxy** [comment]
another problem is：
if I have some `mdx` files，it's ok。when I removed all the `mdx` file，then `allMdx` becomes `null`，`graphql` will also throw error out。

so，what's the right solution to handle the annoying null problem？

**Comment by ChristopherBiscardi** [comment]
@wulucxy the error you posted implies that *none* of your markdown files have `next` defined in the frontmatter. If this is the case, that is how gatsby works today without using the new schema customization APIs. It's not an MDX bug but rather because the graphql types are inferred in Gatsby's node system, you have to define `next` in *some* frontmatter somewhere for it to be seen by Gatsby's system. Since the frontmatter you've included in this issue is missing the `next` field, I'd add it in.

**Comment by wulucxy** [comment]
@ChristopherBiscardi but I have only one `mdx` file。so，what's the solution is `gatsby` ？

you can‘t do this, right？

```
---
title: markdown 拓展
root: "/docs"
order: 6
parents: ["开发指南"]
prev: 基本配置
next: undefined  # I hate this 😂😂
---
```

**Comment by ChristopherBiscardi** [comment]
@wulucxy 

There's a few solutions.

The "truest" solution is going to be the new schema customization ([blog post here](https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/)). Where you create a type beforehand and translate the Mdx node into your type. This way it will have all of the values in your frontmatter, etc when you go to query whether a specific node has them or not.

Without the schema customization you could also choose to use [`createNodeField`](https://www.gatsbyjs.org/docs/actions/#createNodeField) and query `fields.next` instead. Typically `createNodeField` is used in the `onCreateNode` lifecycle, so it would look something like this:

```js
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions;

  if (node.internal.type === `Mdx`) {
    const { frontmatter } = node;
    createNodeField({
      name: `next`,
      node,
      value: frontmatter.next
    });
  }
};
```
