### ISSUE TITLE
change plugin name to `gatsby-plugin-mdx` for consistent

### ISSUE THREAD

**Issue by nhducit** [ChristopherBiscardi/gatsby-mdx#35]
Hi @ChristopherBiscardi @avigoldman, I'm the author of https://github.com/nhducit/gatsby-plugin-mdx/, as we discussed on Twitter. I would like to transfer `gatsby-plugin-mdx` to you to make this plugin consist with gatsby plugin naming convention. After transfer package name, please publish a copy of my plugin to avoid breaking current `gatsby-plugin-mdx` user.

what do you think?

**Comment by nhducit** [comment]
As per Twitter, happy to take this on. Do you want to transfer the git repo to me and the npm package to either me or avigoldman?

Sure. let's do it

**Comment by nhducit** [comment]
Shit. I accidentally removed myself as npm package maintainer after inviting you as maintainer. I hope you have write access to this package already

**Comment by ChristopherBiscardi** [comment]
As far as I can tell, everything went according to plan :) thanks

![screen shot 2018-07-29 at 2 39 53 am](https://user-images.githubusercontent.com/551247/43364934-28944d86-92d9-11e8-8401-c6977c4bad7f.png)
![screen shot 2018-07-29 at 2 42 34 am](https://user-images.githubusercontent.com/551247/43364935-28aa17a6-92d9-11e8-810c-0bdf3cb801cd.png)

**Comment by ChristopherBiscardi** [comment]
Gonna close this and start doing some issue cleanup on the other repo since everything looks good on the publishing side of things :) Thanks again @nhducit
