### ISSUE TITLE
plugin only works with gatsby-mdx v0.4.3

### ISSUE THREAD

**Issue by meritozh** [ChristopherBiscardi/gatsby-mdx#350]
**Describe the bug**

Only works with gatsby-mdx@v0.4.3, I cannot update my deps : (

**To Reproduce**

[reproduce repo](https://github.com/meritozh/gatsby-mdx-minimal-repro/commit/75e41253988e333c85db77ef77c0afc3b884b0e5)

I must fix the version. If I use `>0.4.3`, the `{id="title"}` will be showed, If I use `0.5.x`, it will raise an `forEach undefined` error.

**Comment by wesbos** [comment]
0.4.5 also has a race condition regression, so best to pin to 0.4.3. Unfortunately I get hundreds of warnings in the console with this version. They are working on back porting a fix and are aware of the issue

**Comment by peduarte** [comment]
Thanks @wesbos and @meritozh 

I've pinned it to `0.4.3` now 👍
