### ISSUE TITLE
Large assets not available in public folder

### ISSUE THREAD

**Issue by spences10** [ChristopherBiscardi/gatsby-mdx#355]
**Describe the bug**

Larger images and .gif's are not displaying in dev or after being built

**To Reproduce**

Look at branch: https://github.com/spences10/blog.scottspence.me/tree/renovate/mdx-monorepo

**Expected behavior**

Asserts to be available but they are not :'(

**Screenshots**

![gif](https://user-images.githubusercontent.com/234708/56076574-03806080-5dcb-11e9-894a-6d6eedba5b4c.gif)

The first gif is large ~5mb, the second one is 409kb

**Additional context**

I have it working on gatsby-mdx 0.5.2, anything after that doesn't seem to work

**Comment by spences10** [comment]
This appears to be fixed now @ChristopherBiscardi 

I used 0.6.2 this morning and didn't have any issues: https://github.com/spences10/blog.scottspence.me/pull/1290/files

Happy to close if no one else is having the same issue.

Thanks

**Comment by ChristopherBiscardi** [comment]
Dope! Thanks for the update :)
