### ISSUE TITLE
Adding a custom Babel config to Gatsby project causes a syntax error `default "use strict"`

### ISSUE THREAD

**Issue by silvenon** [ChristopherBiscardi/gatsby-mdx#359]
**Describe the bug**
When adding a minimal [custom Babel configuration](https://www.gatsbyjs.org/docs/babel/) to the Gatsby project, compiled MDX content contains the following line:

```js
default "use strict";
```

which causes an error.

<details>
<summary>Example error</summary>
<pre>
<code>index.js:2177 The above error occurred in the <use strict> component:
    in use strict (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent (created by PageRenderer)
    in PageRenderer (created by JSONStore)
    in JSONStore (created by EnsureResources)
    in ScrollContext (created by EnsureResources)
    in RouteUpdates (created by EnsureResources)
    in EnsureResources (created by RouteHandler)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Root)
    in Root
    in a (created by Component)
    in MDXScopeProvider (created by Component)
    in Component (created by Component)
    in Component
    in _default</code>
</pre>
</details>

**To Reproduce**
Add a `babel.config.js` file to the Gatsby project:

```
module.exports = {
  presets: ['babel-preset-gatsby'],
}
```

Create a MDX page file and navigate to it to see the error. To see the compiled output you need to query `mdx`/`allMdx` and inspect `code.body`.

**Expected behavior**
Not to contain that line.

**Additional context**
- gatsby-mdx: v0.6.2

<details>
<summary>Complete compiled MDX content</summary>
<pre><code>function _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }

function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }

/* @jsx mdx */
var meta = {
  title: "Hello World!"
};
var _frontmatter = {};

var makeShortcode = function makeShortcode(name) {
  return function MDXDefaultShortcode(props) {
    console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope");
    return mdx("div", props);
  };
};

var layoutProps = {
  meta: meta,
  _frontmatter: _frontmatter
};
var MDXLayout = "wrapper";
default "use strict";

function MDXContent(_ref) {
  var components = _ref.components,
      props = _objectWithoutProperties(_ref, ["components"]);

  return React.createElement(MDXLayout, Object.assign({}, layoutProps, props, {
    components: components,
    mdxType: "MDXLayout"
  }), React.createElement("p", null, "Hello world!"));
}

MDXContent.isMDXComponent = true;</code></pre>
</details>

**Comment by johno** [comment]
@silvenon Thanks for opening! This should now be fixed in 1.0.5 (of MDX core).

**Comment by ChristopherBiscardi** [comment]
@silvenon I believe the [fix for this](https://github.com/mdx-js/mdx/commit/5259a47066d63a7bcbdb8ed2b7d3a9c7cf5ea887) went out in `@mdx-js/mdx` 1.0.5. Can you upgrade and check it out?

**Comment by ChristopherBiscardi** [comment]
Going to close this as 1.0.5 has the fix. Happy to re-open if that turns out to not be the case

**Comment by silvenon** [comment]
Confirmed, it works!
