### ISSUE TITLE
"Invalid DOM property `class`. Did you mean `className`?"

### ISSUE THREAD

**Issue by LekoArts** [ChristopherBiscardi/gatsby-mdx#360]
**Describe the bug**

I use `gatsby-remark-autolink-headers` in this repository:
https://github.com/LekoArts/gatsby-starter-minimal-blog

It throws this error:

```
Invalid DOM property `class`. Did you mean `className`?
    in a (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in h3 (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in wrapper (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in MDXContent (created by MDXRenderer)
    in MDXRenderer (created by Post)
    in div (created by Context.Consumer)
```

**Additional context**

As per Slack convo:

> you have an `h3` somewhere that is using `class` as a prop because of a remark plugin

The h3 is here for example: https://github.com/LekoArts/gatsby-starter-minimal-blog/blob/master/blog/2018-01-05/index.mdx

**Comment by johno** [comment]
Thanks for opening this issue! This is now fixed in the latest versions of MDX core:

```
 @mdx-js/mdx    ^1.0.5  →  ^1.0.10
 @mdx-js/react  ^1.0.2  →  ^1.0.6
```
