### ISSUE TITLE
Named capture groups not supported (latest Firefox and < Node 10)

### ISSUE THREAD

**Issue by dmetivier** [ChristopherBiscardi/gatsby-mdx#366]
## Describe the bug
A syntax of named capture groups is being used in `mdx-utils` that is not widely supported. Babel isn't doing much for me using their plugin for named capture groups either 🤷‍♂️

Specifically in `mdx-utils` - `index.js`:

```js
const matches = className.match(/language-(?<lang>.*)/);
```

Any way we could run babel on this file and publish to fix firefox and builders using node?

## Materials
* https://github.com/tc39/proposal-regexp-named-groups
* https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex
* https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/#node.js-version

## Notes
I could be a total `derp` trying to get babel working with Gatsby because I've never had to worry about it. I have a `.babelrc` file with these settings:

```json
{
  "presets": [
    "babel-preset-gatsby"
  ],
  "plugins": [
    "@babel/plugin-transform-named-capturing-groups-regex"
  ]
}
```

Still no luck.

**Comment by johno** [comment]
Somewhat related (we recently had to remove the dot all regex syntax from MDX core to ensure it works inside FF as well): https://github.com/mdx-js/mdx/pull/532

**Comment by dmetivier** [comment]
@johno Would it be preferable to destructure the match instead of use a capture group for now? At least until Firefox catches up and builders start using Node 10+...

In `mdx-utils` index.js...

Current:
```js
const [matches] = className.match(/language-(?<lang>.*)/);

return {
  codeString: codeString.trim(),
  className,
  language:
    matches && matches.groups && matches.groups.lang
      ? matches.groups.lang
      : "",
  ...props
};
```

New (works well for me):
```js
const [,match] = className.match(/language-(.*)/);

return {
  codeString: codeString.trim(),
  className,
  language:
    match ? match : "",
  ...props
};
```

**Comment by johno** [comment]
Yeah, AFAICT this would work well since there will never be more than one language from a code block. Though I think we'll want to use the more verbose regex here as well (`[\0-\uFFFF]`) so that folks don't have to use the babel polyfill.

**Comment by dmetivier** [comment]
Would `[a-zA-Z]*` not yield the same/better result? Unless they'd have to use a polyfill for that too...

**Comment by ChristopherBiscardi** [comment]
`[a-zA-Z]*` wouldn't work because we can't guarantee that someone isn't passing in a custom lang like:

    ```js-something

We have to scoop everything up until the next whitespace afaik

**Comment by dmetivier** [comment]
@ChristopherBiscardi That's very true. `/language-([\0-\uFFFF]*)/` works just fine for me in my testing. Safe to say we could have something like this implemented?

```js
const [,match] = className.match(/language-([\0-\uFFFF]*)/);

return {
  codeString: codeString.trim(),
  className,
  language:
    match ? match : "",
  ...props
};
```

**Comment by ChristopherBiscardi** [comment]
lgtm, would accept a PR

**Comment by dmetivier** [comment]
Changes merged ❤️
