### ISSUE TITLE
Import errors in MDX remain after fix + recompile (until .cache is cleared)

### ISSUE THREAD

**Issue by nevik** [ChristopherBiscardi/gatsby-mdx#370]
**Describe the bug**
When there is an error importing a component in MDX (outside `src/`), the error wrongly remains even after fixing the import and re-starting the Gatsby dev server.
Deleting `.cache` fixes the problem.

Note: I did not try if this happens also for MDX inside `src/` (I'm not using any MDX inside my `src/`).

**To Reproduce**
Find a repro repo [here](https://github.com/nevik/gatsby-mdx-import-error-cache-repro).
1. Edit `content/posts/blog-1.mdx` and break the import on [line 6](https://github.com/nevik/gatsby-mdx-import-error-cache-repro/blame/master/content/posts/blog-1.mdx#L6), e.g. change it to `import Image from './src/components/image'`
2. Run `yarn start` (or `gatsby develop`) --> Gatsby bootstrap works, but compilation (correctly) fails with: 
    ```
    Error: ./.cache/caches/gatsby-mdx/mdx-scopes-dir/8a28a7dacedab88dc0461cf661436f4c.js
    Module not found: Error: Can't resolve '../../../../content/posts/src/components/image' in '<repopath>/.cache/caches/gatsby-mdx/mdx-scopes-dir'
    resolve '../../../../content/posts/src/components/image' in '<repopath>/.cache/caches/gatsby-mdx/mdx-scopes-dir'
    ( and more )
    ```
3. Fix the import in `content/posts/blog-1.mdx`
4. Run `yarn start` (or `gatsby develop`) again

**Expected behavior**
Compilation should work.

**Actual behavior**
The build still fails with an error referring to the wrong import path (which is no longer in the input file).

Full error output (paths sanitized):
```
Error: ./.cache/caches/gatsby-mdx/mdx-scopes-dir/8a28a7dacedab88dc0461cf661436f4c.js
Module not found: Error: Can't resolve '../../../../content/posts/src/components/image' in '<repopath>/.cache/caches/gatsby-mdx/mdx-scopes-dir'
resolve '../../../../content/posts/src/components/image' in '<repopath>/.cache/caches/gatsby-mdx/mdx-scopes-dir'
  using description file: <repopath>/package.json (relative path: ./.cache/caches/gatsby-mdx/mdx-scopes-dir)
    using description file: <repopath>/package.json (relative path: ./content/posts/src/components/image)
      no extension
        <repopath>/content/posts/src/components/image doesn't exist
      .mjs
        <repopath>/content/posts/src/components/image.mjs doesn't exist
      .js
        <repopath>/content/posts/src/components/image.js doesn't exist
      .jsx
        <repopath>/content/posts/src/components/image.jsx doesn't exist
      .wasm
        <repopath>/content/posts/src/components/image.wasm doesn't exist
      .json
        <repopath>/content/posts/src/components/image.json doesn't exist
      .mdx
        <repopath>/content/posts/src/components/image.mdx doesn't exist
      as directory
        <repopath>/content/posts/src/components/image doesn't exist
[<repopath>/content/posts/src/components/image]
[<repopath>/content/posts/src/components/image.mjs]
[<repopath>/content/posts/src/components/image.js]
[<repopath>/content/posts/src/components/image.jsx]
[<repopath>/content/posts/src/components/image.wasm]
[<repopath>/content/posts/src/components/image.json]
[<repopath>/content/posts/src/components/image.mdx]
 @ ./.cache/caches/gatsby-mdx/mdx-scopes-dir/8a28a7dacedab88dc0461cf661436f4c.js 2:0-67 6:9-14
 @ ./node_modules/gatsby-mdx/loaders/mdx-scopes.js
 @ ./node_modules/gatsby-mdx/wrap-root-element.js
 @ ./node_modules/gatsby-mdx/gatsby-ssr.js
 @ ./.cache/api-runner-ssr.js
 @ ./.cache/develop-static-entry.js
```

**Additional context**
After deleting `.cache/`, the build works again -> looks like the cache doesn't get properly updated after changing content files?

**Comment by ChristopherBiscardi** [comment]
yeah the scope processing works but isn't very smart in the `develop` use case so it's easy to end up with extra scope laying around until you `rm -rf .cache`. We should probably do something more interesting like keep processing the scope in `onCreateNode` but only write it out in a later lifecycle so that iterating over all Mdx nodes is fast and up to date.

**Comment by patrickarlt** [comment]
> .
> 
> Note: I did not try if this happens also for MDX inside `src/` (I'm not using any MDX inside my `src/`).

I also ran into the original issue @nevik posted and tried the above just to see if it worked. It doesn't. Gatsby just seems to hang and I end up with a blank pages. `rm -rf .cache && gatsby develop` seems to fix it.

@ChristopherBiscardi I found this while evaluating Gatsby + MDX for a new documentation system I'm working on for technical docs. Being able to import other shared MDX files would be a major requirement. Would making a minimal reproduction repo help you? I would be happy to set one up.

**Comment by tonnyavery** [comment]
Can confirm the issue.
Reproduced it by removing one component and changing the import in my mdx.
Restarting `gatsby develop` failed with reference to the old removed component inside .cache folder

Workedaround by adding this to my package.json scripts:
```
"develop": "rm -rf .cache/caches/gatsby-plugin-mdx && gatsby develop",
```

**Comment by janosh** [comment]
Also running into this. Since this project has moved to [`gatsby-plugin-mdx`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx), should I open a new issue there?
