### ISSUE TITLE
MDXProvider not using code component for inline code

### ISSUE THREAD

**Issue by deltaskelta** [ChristopherBiscardi/gatsby-mdx#371]
**Describe the bug**

`MDXProvider` used the provided component for block level code (triple backticked) but not for inline code (single backticked)

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro) and Steps to reproduce the behavior:
1. use the kitchen sink example
2. use components for MDXProvider

```
export default class RootWrapper extends React.Component {
  render() {
    const { children } = this.props;
    return (
      <MDXProvider
        components={{
          h1: ({ children, ...props }) => (
            <h1 {...props}>Provided: {children}</h1>
          ),
          pre: props => {
            console.log("pre");
            return <span style={{ backgroundColor: "green" }} {...props} />;
          },
          code: props => {
            console.log("code");
            return <span style={{ backgroundColor: "blue" }} {...props} />;
          },
          wrapper: "section"
        }}
      >
        {children}
      </MDXProvider>
    );
  }
}
```
3. make one of the mdx pages have a single backticked code and triple backticked code.
4. See that only triple backticked code uses a component and single backticked code uses a regular `<code>` tag

**Expected behavior**

I wold expect single backticked code to use a component as well

**Screenshots**

![Screen Shot 2019-04-20 at 9 13 15 PM](https://user-images.githubusercontent.com/9424192/56457119-34572b80-63b1-11e9-9de1-61cc267edcaa.png)

**Comment by johno** [comment]
In order to differentiate between the code inside pre tags and inline code there's a special `inlineCode` node type which you'll need to use here.

Ref: https://mdxjs.com/getting-started#table-of-components

**Comment by johno** [comment]
🤦‍♂️ It's labeled wrong in the official docs. Fixing now.
