### ISSUE TITLE
[1.0] defaultLayouts needs to become defaultWrappers

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#375]
MDX 1.0 unified layouts and wrappers to be wrappers.

**Comment by polarathene** [comment]
When using defaultLayout, I imported MDX content into a MDX document, afaik this type of embedding is meant to be a feature but I'm not sure why you'd want to apply the layout to these embeds? 

As a result console spat out a bunch of errors about elements like header and footer being in <p> tags, and sure enough the embedded MDX document had also embedded the header and footer from the layout.

If the purpose of setting a default layout is to not need to handle it explicitly within the MDX doc itself, do you need to accept this tradeoff with embeds?

**Comment by ChristopherBiscardi** [comment]
@polarathene You need to make a new issue. This issue is unrelated to what you're asking.

**Comment by ChristopherBiscardi** [comment]
moved to https://github.com/gatsbyjs/gatsby/issues/16848
