### ISSUE TITLE
Invalid prop supplied to React.Fragment

### ISSUE THREAD

**Issue by itwasmattgregg** [ChristopherBiscardi/gatsby-mdx#378]
I'm getting this error in the browser console when navigating to a post rendered with MDXRenderer:

```
index.js:2177 Warning: Invalid prop `_frontmatter` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in MDXContent (created by MDXRenderer)
    in MDXRenderer (at blog-post.jsx:64)
```

It seems to render on the page ok thought so not really sure at all what is going on.

**Comment by ChristopherBiscardi** [comment]
MDX 1.0 changed the default `wrapper` to be `React.Fragment` and *also* merged defaultLayouts with `wrapper`s so they are the same thing now. The warning can be solved by using `MDXProvider` to only pass `children` through to the fragment.

```js
// gatsby-browser.js
import React from "react"
import { MDXProvider } from "@mdx-js/react"

const components = {
	wrapper: ({children}) => <>{children}</>
}
export const wrapRootElement = ({ element }) => {
  return (
    <MDXProvider components={components}>
      {element}
    </MDXProvider>
  )
}
```

* [Here's a video](https://egghead.io/lessons/react-replace-the-mdx-content-wrapper-with-an-mdxprovider-in-gatsby-mdx?pl=building-websites-with-mdx-and-gatsby-161e9529) explaining how to do it.
* [Here's a working repo](https://github.com/ChristopherBiscardi/eggheadio-code-examples/blob/master/replacing-the-mdx-content-wrapper-element-with-gatsby-mdx/gatsby-browser.js) with the changes you'll need to make.

---

Although you're probably just on an old version of mdx and [should upgrade to at least 1.0.6](https://github.com/mdx-js/mdx/commit/5c7e8e154bd97c7e1068f803b177efb3180afb14)
