### ISSUE TITLE
Importing a style applies to all files not just that import the stylesheet

### ISSUE THREAD

**Issue by tareefdev** [ChristopherBiscardi/gatsby-mdx#384]
Using gatsby with gatsby-mdx plugin I tried to import a CSS file inside an MDX file.
I thought the rules will just apply on that file content, but it applies to all other files too.

**To Reproduce**
- Add a new css file with: `p {color: red}` rule.
- Import the file into `page-2.mdx`
- Develop the site. All `<p>` in all pages are red now.

**Expected behavior**
Just `<p>` within `page-2.mdx` should be red.

So, does this the intended behavior or I missed something?

**Comment by ChristopherBiscardi** [comment]
I'm not sure I understand why the expectation would be that styles would only apply to the MDX file if you're targeting all `p` tags across the entire site in the stylesheet.

**Comment by tareefdev** [comment]
I just thought that importing CSS rules inside an individual file will allow me to make the site load them just for that page. This approach has two benefits:

- Write CSS rules quickly without needing to add wrapper <div>'s with classes and ids to my pages.
- The site will load less CSS size for each page.

So is there another method to make things work in this way?

**Comment by ChristopherBiscardi** [comment]
> So is there another method to make things work in this way?

I'd use emotion to author my components, which would only load the css necessary for a given rendered component on a given page by default.

> I just thought that importing CSS rules inside an individual file will allow me to make the site load them just for that page

I haven't looked deeply into the css webpack loader in awhile, but my impression from past usage is that you end up with a single concatenated css file output from importing files like this. There is no "auto-scoping" unless you're using the css-modules option to css-loader, and even then the classname compilation wouldn't apply to tag selectors like `p`, only classes.

You could probably write some code to make something like this work, but it's definitely outside the scope of MDX and this repo and it sounds like you'd be better off using an existing solution like emotion, etc.

**Comment by tareefdev** [comment]
Thanks for your helping.

**Comment by polarathene** [comment]
@tareefdev style all p elements of a wrapper/parent element specific to that page. Either via styled component like emotion/styled-components/etc, or classname/id. You could also override the p element for the page to be rendered with a custom react P element/component instead, which could just be a regular p with a style classname?
