### ISSUE TITLE
Add empty lines within variables of a Component

### ISSUE THREAD

**Issue by kuworking** [ChristopherBiscardi/gatsby-mdx#391]
*gatsby 2.3.31
*gatsby-mdx 0.6.2

Within a `mdx` file I'm using a component that requires a variable, such as that

```js
<Component js="" />
```

But, what I think to see is that if that variable has empty lines, it gets parsed as if it was normal text

So if I have

```js
<Component js="
const myObject = { name: 'blah'}

for (const property in myObject)
  if (myObject.hasOwnProperty(property))
    console.log(myObject[property])

for (const entry of Object.entries(myObject))
  console.log(entry)

for (const [key, value] of Object.entries(myObject))
  console.log(key+' '+value)
" />
```

It works, but the `new lines` are gone and the code doesn't work (it is a long line)

And if I try like this

```js
<Component js={`
const myObject = { name: 'blah'}

for (const property in myObject)
  if (myObject.hasOwnProperty(property))
    console.log(myObject[property])

for (const entry of Object.entries(myObject))
  console.log(entry)

for (const [key, value] of Object.entries(myObject))
  console.log(key+' '+value)
`} />
```

Then I have an error because `mdx` seems to try wrapping the empty lines within `<p></p>` tags

What could I do?

*Right now I'm just using `//` as the new lines, but it is ugly

```js
<Component js={`
const myObject = { name: 'blah'}
//
for (const property in myObject)
  if (myObject.hasOwnProperty(property))
    console.log(myObject[property])
//
for (const entry of Object.entries(myObject))
  console.log(entry)
//
for (const [key, value] of Object.entries(myObject))
  console.log(key+' '+value)
`} />
```

**Comment by ChristopherBiscardi** [comment]
You should repost this issue over at [@mdx-js/mdx](https://github.com/mdx-js/mdx/issues/new) as it is related to how MDX works and not a gatsby-mdx issue.
