### ISSUE TITLE
Release next mdx-utils version

### ISSUE THREAD

**Issue by jlesquembre** [ChristopherBiscardi/gatsby-mdx#402]
Thanks for this project, I really like to be able to write MDX with gatsby. 

I've been bitten by #373 , it is a nasty bug and the error message is confusing. It's fixed in master, but unfortunately not released on npm yet.

Could you create a new release?

**Comment by axe312ger** [comment]
@jlesquembre its not that hard to release it scoped under your name on npm, in case you run into this again with other packages :)

I published it for you as `@axe312/mdx-utils@0.1.2` till @ChristopherBiscardi gets time to publish

have fun

**Comment by jlesquembre** [comment]
@axe312ger I didn't think about that solution, thanks :)

**Comment by axe312ger** [comment]
So it does work? didnt test it :D

**Comment by jlesquembre** [comment]
Unfortunately it didn't work.
On one hand, I think you publish private package, I can't find `@axe312/mdx-utils` on npm.
On the other hand, I publish my own version at https://www.npmjs.com/package/@jlesquembre/mdx-utils, but I get this error:
```
Module not found: Error: Can't resolve 'mdx-utils' 
```

It makes sense, since now the package is called `@axe312/mdx-utils`, not `mdx-utils`

**Comment by axe312ger** [comment]
yeah just change your imports/requires, worked for me with `@axe312/gatsby-mdx`

**Comment by ChristopherBiscardi** [comment]
thanks @axe312ger I've been really busy getting gatsby-mdx merged into the Gatsby repo -- https://github.com/gatsbyjs/gatsby/pull/14657

mdx-utils@0.2.0 is now published.

**Comment by jlesquembre** [comment]
@ChristopherBiscardi thanks a lot for your work
