### ISSUE TITLE
Extra backslash sometimes inserted when using $ in text

### ISSUE THREAD

**Issue by lourd** [ChristopherBiscardi/gatsby-mdx#405]
I noticed that on some parts of my portfolio site (made with gatsby and gatsby-mdx), there are extra backslashes being inserted in some places where dollar signs are used. For example:

- Go to https://descioli.design/grove and Find for `\$` — there are 6 occurrences on the page. There are 12 usages of `$`, though — not every $ is preceded by a backslash.
- The MDX source for that page is [here](https://github.com/lourd/descioli-design/blob/master/content/stories/grove/grove.mdx). Note: no backslashes.
- The rendering of the page is [here](https://github.com/lourd/descioli-design/blob/master/src/components/Story.tsx#L161-L191). Pretty standard AFAIK.

It only started happening when I switched from Remark to MDX. I didn't notice it when I did the initial switch.

### Environment

*   macOS and ubuntu, latest version
*   @mdx-js/mdx@1.0.20, gatsby-mdx@0.6.3
*   node@10.1.0, yarn@1.13.0

### Steps to reproduce

Clone my portfolio repo, https://github.com/lourd/descioli-design, and run it. No additional configuration needed.

### Expected behaviour

No extra backslashes.

### Actual behaviour

Extra backslashes

---
This is a duplicate of https://github.com/mdx-js/mdx/issues/606. I wasn't sure if it should be filed there or here.

**Comment by johno** [comment]
Hmm, it looks like the source MDX itself contains "\$" which is why it's ending up in the rendered page AFAICT.

**Comment by lourd** [comment]
The issue isn't the dollar signs showing up, it's the mysterious extra backslashes before the dollar sign. The backslashes aren't present in the source. They are present in the rendered version.

**Comment by lourd** [comment]
Your comment made me go and re-inspect the source just to make sure I wasn't missing something obvious... and I was 🤦‍♂

The `\$` was only visible when looking at the [raw version](https://raw.githubusercontent.com/lourd/descioli-design/b723706e1d21d9cf3acb984d592e30789be89c7b/content/stories/grove/grove.mdx) of the source. And I hadn't bothered to look at it in my editor, just on GitHub.

The slashes were automatically inserted Prettier. I'd set it up to run on pre-commit and missed the fact that it was also formatting .mdx files. Sorry to waste your time.
