### ISSUE TITLE
npm / Gatsby search using old Readme stating "gatsby-mdx is the official integration"

### ISSUE THREAD

**Issue by karlhorky** [ChristopherBiscardi/gatsby-mdx#413]
**Describe the bug**

The npm and Gatsby search are showing the old readme content, with a phrase stating "gatsby-mdx is the official integration", which is not true anymore:

https://www.npmjs.com/package/gatsby-mdx
https://www.gatsbyjs.org/packages/gatsby-mdx/

I guess the readme content should match the current readme (https://github.com/ChristopherBiscardi/gatsby-mdx/blob/161c084282834cc2cbd864d09617c10d869d0022/README.md).

**To Reproduce**

Visit the links above to see the message.

**Expected behavior**

Consistent readmes.

**Screenshots**

<img width="611" alt="Screen Shot 2019-07-15 at 10 53 12" src="https://user-images.githubusercontent.com/1935696/61205118-80cfb000-a6ef-11e9-8e4f-b9ffcd02922b.png">

**Additional context**

Related issue in `gatsbyjs/gatsby`: https://github.com/gatsbyjs/gatsby/issues/15651

Mention by @amberleyromo: https://github.com/gatsbyjs/gatsby/pull/15559#issuecomment-510714244

**Comment by ChristopherBiscardi** [comment]
Can't change the README without doing a release. Since people are still using the old gatsby-mdx releases in production, what I'll probably do is release a gatsby-mdx 1.0 and deprecate it immediately with a message pointing to the gatsby-plugin-mdx package.

Planning this for after I write and release the 1.0 blog post.

**Comment by Graham42** [comment]
Just spent several hours going down the wrong path here and couldn't figure out why I couldn't get it to work. Would really appreciate a deprecated notice on the existing version.

**Comment by ChristopherBiscardi** [comment]
![image](https://user-images.githubusercontent.com/551247/61917132-720fa700-af00-11e9-814c-c4a63471c025.png)

**Comment by karlhorky** [comment]
Cool thanks @ChristopherBiscardi !

**Comment by karlhorky** [comment]
Thanks!

I guess what's remaining now from the description is the Gatsby search (https://www.gatsbyjs.org/packages/gatsby-mdx/):

![Screen Shot 2019-07-25 at 20 59 30](https://user-images.githubusercontent.com/1935696/61925044-4c45ca80-af1f-11e9-94af-6b3d92f2bf8d.png)

I suppose that will come with the blog post.

**Comment by ChristopherBiscardi** [comment]
That's done by algolia and grabs the README from the released package so not sure there's anything we can do about it here

**Comment by karlhorky** [comment]
Hm, I thought I was reading somewhere in the issues here that there is a way to evict plugins from the index (or at least mark them as deprecated)...

Maybe I can find that still...

**Comment by karlhorky** [comment]
Can't find the issue at the moment, maybe @marcysutton or @DSchau or @jlengstorf can help here?

To the point: How can we remove `gatsby-mdx` from the Algolia search index (or mark it as deprecated)? It's been already marked as deprecated on npm.
