### ISSUE TITLE
change-case in gatsby-mdx not listed in dependencies

### ISSUE THREAD

**Issue by samdenty** [ChristopherBiscardi/gatsby-mdx#414]
https://github.com/ChristopherBiscardi/gatsby-mdx/blob/f29ae7f3c04555fde9c11c0c80e9f652e7bde64d/packages/gatsby-mdx/utils/babel-plugin-html-attr-to-jsx-attr.js#L1

**Comment by maggo** [comment]
`gatsby-mdx` is [part of the official repo](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx) now. You can remove the `gatsby-mdx` dependency and install the new plugin, then replace it in your config and it will just work!
