### ISSUE TITLE
Issue with code blocks containing parenthesis and brackets

### ISSUE THREAD

**Issue by julianguyen** [ChristopherBiscardi/gatsby-mdx#415]
I'm encountering the following issue when parsing a Markdown file that contains

```
<code>form-{a random number}</code>
```

I get the error:

> SyntaxError: unknown: Unexpected token, expected "{"

I'm confused cause shouldn't it be stringifying the contents of `<code>` instead of trying to evaluate it as code?

I'm using:
```
"@mdx-js/mdx": "^1.1.5",
"@mdx-js/react": "^1.1.5",
"gatsby-source-filesystem": "^2.1.8",
"gatsby-plugin-mdx": "^1.0.22",
"gatsby-transformer-mdx": "^1.1.2"
```

**Comment by ChristopherBiscardi** [comment]
> I'm confused cause shouldn't it be stringifying the contents of \<code\> instead of trying to evaluate it as code?

`code` is a jsx tag and `{` is jsx syntax for interpolating a value. 

You're looking for backticks, which are markdown syntax for inline code.

```
`form-{a random number}`
```
