### ISSUE TITLE
`wordCount` conflicts with `gatsby-transformer-remark`

### ISSUE THREAD

**Issue by danoc** [ChristopherBiscardi/gatsby-mdx#44]
Hi! When using both `gatsby-mdx` and `gatsby-transformer-remark`, I get the following error when I create a `foo.mdx` file outside of the `src/pages` directory. Oddly, the error doesn't appear if the MDX file is within `src/pages`.

```
$ gatsby develop --port 8090
success open and validate gatsby-config — 0.007 s
success load plugins — 0.183 s
success onPreInit — 0.487 s
success delete html and css files from previous builds — 0.649 s
success initialize cache — 0.012 s
success copy gatsby files — 0.035 s
success onPreBootstrap — 0.001 s
success source and transform nodes — 10.113 s
error UNHANDLED REJECTION


  Error: Schema must contain unique named types but contains multiple types named "wordCount  ".

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach
```

While this isn't the fix, commenting out these lines makes the error go away:

https://github.com/ChristopherBiscardi/gatsby-mdx/blob/5a2635dd63b205b4a4ca3749216804e512067197/packages/gatsby-mdx/extend-node-type.js#L111-L150

The error also goes away if I turn off `gatsby-transformer-remark`.

Are these two libraries supposed to be able to co-exist? I'm diving into this a little more to see why it works if the MDX file is within `src/pages`.

**Comment by danoc** [comment]
I think it works for files within `src/pages` because `extend-node-type.js` doesn't get run on those.

**Comment by ChristopherBiscardi** [comment]
Can you paste your gatsby-config? They should be able to coexist in the same project as long as they aren’t running on the same files.

**Comment by ChristopherBiscardi** [comment]
Hmm actually thinking about this it’s an unfortunate naming collision in the GraphQL types namespace. Will have to think of best way to resolve it. Easiest way would be for us to rename wordCount to wordCounts, mdxWordCount or something.

**Comment by danoc** [comment]
Hi @ChristopherBiscardi, here it is:

```
module.exports = {
    siteMetadata: {
        title: '',
        description: '',
    },
    plugins: [
        'gatsby-plugin-netlify',
        'gatsby-plugin-react-helmet',
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                name: 'packages',
                path: `${__dirname}/../packages/`,
            },
        },
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                name: 'kits',
                path: `${__dirname}/src/kits/`,
            },
        },
        {
            resolve: 'gatsby-plugin-sass',
            options: {
                // Allows SCSS files within `packages` to find their imports.
                includePaths: ['../'],
            },
        },
        'gatsby-transformer-thumbprint-components', // internal plugins
        'gatsby-transformer-thumbprint-tokens', // internal plugins
        'gatsby-transformer-thumbprint-icons', // internal plugins
        'gatsby-transformer-thumbprint-atomic', // internal plugins
        'gatsby-transformer-react-docgen',
        {
            resolve: 'gatsby-transformer-remark',
            options: {
                plugins: [
                    'gatsby-remark-autolink-headers',
                    'gatsby-remark-smartypants',
                    'gatsby-remark-prismjs',
                ],
            },
        },
        {
            resolve: 'gatsby-mdx',
            options: {
                defaultLayouts: {
                    packages: require.resolve('./src/components/component.jsx'),
                },
            },
        },
        {
            resolve: 'gatsby-plugin-google-analytics',
            options: {
                trackingId: 'UA-6981433-9',
            },
        },
        'gatsby-plugin-lodash',
    ],
};
```

Does this only affect `wordCount` because it's the only one that has a `new GraphQLObjectType`?

**Comment by ChristopherBiscardi** [comment]
Fixed by rename in 0.0.7. field is now `wordCounts`. It's a breaking change but we're still in breaking change territory so I just did it.

**Comment by ChristopherBiscardi** [comment]
thanks for the report!!

**Comment by danoc** [comment]
Great, thanks @ChristopherBiscardi! I've been having a great time playing with this plugin. 🎉

**Comment by ChristopherBiscardi** [comment]
awesome to hear! Let us know if you run into any other issues or think of any new use cases :)
