### ISSUE TITLE
how to access html output?

### ISSUE THREAD

**Issue by geddski** [ChristopherBiscardi/gatsby-mdx#47]
I'm attempting to switch my gatsby site from remark over to gatsby-mdx. I'm calling `createPage()` in my `gatsby-node` file. With remark I would access the parsed markdown via the `html` property. What is the equivalent method via gatsby-mdx? 

```js
// gatsby-node.js
createPage({
    path: node.fields.slug,
    component: path.resolve(`./src/templates/blog-post.js`),
    context: { absPath: node.absolutePath, slug: node.fields.slug },
})
```

```js
// blog-post.js
// here's what I was doing with remark

export default ({ data }) => {
  const post = data.markdownRemark
  return <div dangerouslySetInnerHTML={{ __html: post.html }} />
}
```

**Comment by ChristopherBiscardi** [comment]
To retain the dynamic nature of mdx (that is, allowing all of the nice importing/jsx/etc), either follow the instructions in the [programmatically creating pages](https://github.com/ChristopherBiscardi/gatsby-mdx#programmatically-creating-pages) section of the README, or the more complete example of the [kitchen-sink](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/6afd3377c55ccae82eb5cb3f05b33c1dd1a2dfca/examples/kitchen-sink/gatsby-node.js) 

```js
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return new Promise((resolve, reject) => {
    resolve(
      graphql(
        `
          {
            allMdx {
              edges {
                node {
                  fileAbsolutePath
                  fileNode {
                    name
                  }
                }
              }
            }
          }
        `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors);
          reject(result.errors);
        }

        // Create blog posts pages.
        result.data.allMdx.edges.forEach(({ node }) => {
          createPage({
            path: `/posts/${node.fileNode.name}`,
            component: node.fileAbsolutePath,
            context: { }
          });
        });
      })
    );
  });
};
```

You can use a `defaultLayout` to wrap it in the blog-post template in gatsby-config.js

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-mdx`,
      options: {
        decks: [],
        defaultLayouts: {
          posts: require.resolve("./src/templates/blog-post.js"),
          default: require.resolve("./src/components/default-page-layout.js"),
        }
      }
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "posts",
        path: `${__dirname}/content/`
      }
    },
  ]
};
```

your default layout then needs to handle children

```js
import React, { Component } from "react";

export default class DefaultPageLayout extends Component {
  render() {
    return (
      <div>
        <h1>The Default Post Layout</h1>
        <div>{this.props.children}</div>
      </div>
    );
  }
}
```

**Comment by ChristopherBiscardi** [comment]
Happy to reopen if you do indeed want html output instead of the full power of mdx. I'd appreciate an explanation of the use case as well :)

**Comment by geddski** [comment]
@ChristopherBiscardi thanks for the help. I had gotten pretty close to that setup when I followed the gatsby-mdx readme. But I thought I had done something wrong because my post's frontmatter is getting treated as content rather than meta data. 

Also I'm not sure how to make a GraphQL query available to my blog-posts layout like they do in the Gatsby docs. Usually you do something like this:

```js
export const query = graphql`
  query($slug: String!) {
    mdx(fields: { slug: { eq: $slug } }) {
      frontmatter {
        title
      }
    }
  }
`
```

and the results become available in the layout component's props.

**Comment by geddski** [comment]
As for my use case, it's a blog where the posts are written in markdown, which I want to contain some interactive React components. Very similar to your live code editor example actually.

**Comment by geddski** [comment]
BTW I made a separate issue for the frontmatter bug. #49

**Comment by geddski** [comment]
@ChristopherBiscardi alright I know what's going on now. The [Gatsby tutorial](https://next.gatsbyjs.org/tutorial/part-seven/) has you `createPages` where the component is one of you JS files (e.g. blog-post.js)

```js
component: path.resolve(`./src/templates/blog-post.js`),
```

That makes that `blog-post` component the **Page** in Gatsby, so it can do special top-level things like dynamic queries.

Gatsby-mdx on the other hand calls `createPage` and makes the markdown file itself the component, which then imports a layout to use and can perform the top-level query.

I much prefer the `blog-post` component as the Page. That lets me keep the query out of my markdown, and avoid repeating that same query in each blog post. Any way this could be possible and still use mdx?

**Comment by ChristopherBiscardi** [comment]
yeah, that came up with the mdx-deck work too. The thing here is that "Layouts" are an mdx thing while some kind of "Wrapper" is more of a gatsby thing and the two aren't a 1-to-1 match right now (and I'm not sure they should be). I'm thinking about implementing a "wrapper" type in addition to the default layouts, more info in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/50

Also shipped the frontmatter fix, thanks.

**Comment by chrisdhanaraj** [comment]
@ChristopherBiscardi I know this is a super old issue, but just wanted to pop up with a reason for the HTML output. 

I was attempting to mimic some of the functionality of GitBook - primarily that you can pass in a SUMMARY.md file to build out a table of contents. I was parsing the HTML output prior looking for headings and lists to build a tree, which doesn't seem possible anymore (the `html` always returns null now, it used to return value)

**Comment by ChristopherBiscardi** [comment]
@chrisdhanaraj I'd open a new issue for this. 

Does the `tableOfContents` field work for you?
