### ISSUE TITLE
frontmatter treated as content when no exports

### ISSUE THREAD

**Issue by geddski** [ChristopherBiscardi/gatsby-mdx#49]
This markdown file will get treated normally:

```md
---
title: "MDX Rocks"
date: "2017-08-10"
---

export default ({ children }) => (
  <div>
    <h1>My Layout</h1>
    <div>{children}</div>
  </div>
)

## My MDX

Some dope content.
```

![image](https://user-images.githubusercontent.com/515722/43755948-a1cfec30-99cf-11e8-8588-18d508db9d1c.png)

If the exports are removed then this same document gets its frontmatter included in its rendered content:

```md
---
title: "MDX Rocks"
date: "2017-08-10"
---

## My MDX

Some dope content.
```

![image](https://user-images.githubusercontent.com/515722/43755989-ce745b68-99cf-11e8-93d0-42e4c62d6210.png)

**Comment by ChristopherBiscardi** [comment]
Should be fixed in 0.0.9.

Thanks for the report!
