### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#5]
# Desired Functionality
The user should be able to configure the mdx loader (#2) and add any additional extensions they want to use for MDX files.

```js
module.exports = {
  siteMetadata: {
    title: `my great site`
  },
  plugins: [
    `gatsby-plugin-emotion`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-mdx`,
      options: {
        extension: ['.mdx', '.md']
      }
    },
  ]
};
```

**Comment by ChristopherBiscardi** [comment]
configuration options are implemented. the extensions list is not.

**Comment by avigoldman** [comment]
PR #16 for adding in the extensions option.
