### ISSUE TITLE
Document MDX page queries

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#51]
like in the kitchen sink [example](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/kitchen-sink/src/pages/basic-page-query.mdx)

**Comment by danoc** [comment]
@ChristopherBiscardi — is there a way to do those queries in the layout referenced within the config?

```
{
    resolve: 'gatsby-mdx',
    options: {
        defaultLayouts: {
            default: require.resolve(
                './src/components/thumbprint-components/layout/index.jsx',
            ),
        },
    },
},
```

This is my `createPage` within `gatsby-node.js`:

```
createPage({
    path,
    component: mdxNode.fileAbsolutePath,
    context: {
        // ...
    },
});
```

Ideally, I'd be able to keep the `.mdx` files simple and handle the data fetching elsewhere. Seems like `defaultLayouts.default` is limited to `StaticQuery`.

**Comment by ChristopherBiscardi** [comment]
Yeah, with #55 looking really good we’ll probably move to suggesting that approach and the component will hoist page queries.

The layouts are an mdx thing and they aren’t layouts that quite match the gatsby way of pulling GraphQL queries out. We either need to hoist queries defined in layouts or move to something else.

**Comment by AndersDJohnson** [comment]
I too want to be able to use a default layout component that exports a GraphQL query that can use `context` data from `createPage` as query variables.

**Comment by JamesMessinger** [comment]
@ChristopherBiscardi  - #55 has been merged, so should this work now?  I'm still unable to to export a query from the layout component.  The exported query is completely ignored and never runs, so the `data` parameter is `undefined`.

**gatsby-config.js**
```javascript
module.exports = {
  siteMetadata {
    title: "My Website"
  },
  plugins: [
    {
      resolve: "gatsby-mdx",
      options: {
        defaultLayouts: {
          default: require.resolve("./src/templates/my-template.jsx"),
        }
      }
    }
  ]
}
```

**my-template.jsx**
```jsx
import { graphql } from "gatsby";
import * as React from "react";

export default ({ data, children }) => (
  <div>
    <header>
      <h1>{data.site.siteMetadata.title}</h1>
    </header>
    <main>
      {children}
    </main>
  </div>
)

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```

**Comment by ChristopherBiscardi** [comment]
@JamesMessinger At this point the official position is if you need a `pageQuery` to use it in an MDX file directly in src/pages OR use gatsby's page template support. You can use `StaticQuery` anywhere already, which is what your example here should be since it doesn't use context vars.

Gatsby does not look anywhere but the "page component" for a page query, so there is no way to add it to a nested component like an MDX layout without gatsby core support.

**Comment by johno** [comment]
Documented in:

- https://gatsby-mdx.netlify.com/guides/writing-pages-in-mdx
- gatsbyjs/gatsby/pull/11361
