### ISSUE TITLE
allMdx() not appearing in graphIQL

### ISSUE THREAD

**Issue by nkuehn** [ChristopherBiscardi/gatsby-mdx#53]
Hi, 

I have set up a minimal MDX support in a gatsby2 ("next") now, just one .mdx page under `src/pages/` and it renders as intended. 
But I can't query it on graphQL so I'm kind of stuck e.g. to get the TOC built.   "allMdx" is simply not appearing in graphIQL  on localhost:8000/___graphql  .  

No errors on console. 

gatsby-config.js plugins section: 
```
  ....
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-mdx`,
      options: {
        extensions: [".mdx"],
        defaultLayouts: {
          default: require.resolve("./src/components/layout.js")
        }
      }
    }
   ....
```
any idea where I could start finding the problem? 

gatsby-mdx version is  "0.0.9",  gatsby is 2.0.0-beta.83

**Comment by ChristopherBiscardi** [comment]
Hey :)

`allMdx` needs MDX nodes to have been created to show up in the GraphQL schema. Pages which use the [page-creator](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-page-creator) plugin (which is what gatsby uses by default for `src/pages`) don't show up in the graphql schema as mdx nodes, but rather site nodes under `allSitePage` field unfortunately. If you want them to show up as MDX nodes, you either have to point a `gatsby-source-filesystem` at the pages dir or move the mdx files to another dir and point the filesystem source there like in the [programmatically creating pages](https://github.com/ChristopherBiscardi/gatsby-mdx#programmatically-creating-pages) section of the README.

**Comment by nkuehn** [comment]
Hi Christopher, thanks for the quick answer.   
just adding a `gatsby-source-filesystem` to `src/pages` worked perfectly. 

Working with the page-creator in `src/pages` is the much more intutive way for content authors that are not developers of the site at the same time than programmatically creating pages. They can "just" create folder structures of mdx files as they like the site URLs to appear.
