### ISSUE TITLE
race condition?

### ISSUE THREAD

**Issue by geddski** [ChristopherBiscardi/gatsby-mdx#57]
Frequently I'll save a markdown file, Gatsby will pick up the changes and trigger HMR, then the browser throws this error:

![image](https://user-images.githubusercontent.com/515722/43996047-bdd310c8-9d77-11e8-8f3f-d64abf9dadf7.png)

To get rid of it I have to restart Gatsby, and change the markdown file so it doesn't cache, and the error often goes away. But then it happens again sometimes. 

It sounds like a race condition in the GraphQL to me, but I'm not sure what could be causing it.

My markdown file query looks like this:

```md
export const query = graphql`
  query($slug: String!) {
    mdx(fields: { slug: { eq: $slug } }) {
      frontmatter {
        title
      }
    }
  }
`
```

and my Theme looks like this:

```js
export default props => {
  const post = props.data.mdx.frontmatter

  return (
    <MDXProvider
      components={{
        pre: Code,
      }}
    >
      <Layout post={post}>
        <div className="post">
          <h1>{post.title}</h1>
          {props.children}
        </div>
      </Layout>
    </MDXProvider>
  )
}
```

Any ideas what could make `props.data.mdx` null sometimes?

**Comment by KyleAMathews** [comment]
This is a Gatsby problem and yeah, it's kinda common and super annoying. It is a race condition and we have a good sense of how to solve it just are prioritizing getting out before tackling it.

**Comment by geddski** [comment]
Ok good to know! I'll close this issue then.
