### ISSUE TITLE
_frontmatter included in Layout prop on default export after mdx compilation

### ISSUE THREAD

**Issue by MiKatre** [ChristopherBiscardi/gatsby-mdx#58]
```
 ERROR  Failed to compile with 1 errors                                                                              00:07:17

 error  in ./src/pages/test/index.mdx

Syntax Error: SyntaxError: /Users/username/Sites/sitename/src/pages/test/index.mdx: Unexpected token, expected "}" (10:82)

   8 | import DefaultLayout from "/Users/username/Sites/sitename/src/components/layout.js";
   9 |
> 10 | export default ({components, ...props}) => <MDXTag name="wrapper" Layout={_default;
     |                                                                                   ^
  11 | export var _frontmatter = {};
  12 | ;} layoutProps={props} components={components}>
  13 | <MDXTag name="p" components={components}>{`(function () {
```
After following the docs to install gatsby-mdx, it doesn't compile.
I just updated to gatsby v2. Everything else works fine.

**Comment by ChristopherBiscardi** [comment]
Can you paste the contents of `/src/pages/test/index.mdx`? At least through the layout component but the whole file would be best.

It looks like it's trying to use the frontmatter as part of the layout so my best guess would be a parsing error related to the layout component.

**Comment by MiKatre** [comment]
Sorry for the delay. The issue was in my layout file. 
I don't know exactly what it was but creating a layout specifically for mdx files solved it.
So, yes, error related to the layout component, thanks !

**Comment by ChristopherBiscardi** [comment]
cool :) 

If you happen to run into it again let us know and we'll try to document/fix it. MDX itself is moving reasonably quickly so sometimes parsing errors pop up with upgrading versions.
