### ISSUE TITLE
Frontmatter

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#6]
# Desired Functionality

A user should be able to add frontmatter in either the classic way or as ES2015 style export.
##### Classic
```md
---
title: My First Post
---

Welcome to my blog
```

##### ES2015 export
```js
export const frontmatter = {
  title: "My First Post"
}

Welcome to my blog
```

**Comment by ChristopherBiscardi** [comment]
Should probably use [gray-matter](https://www.npmjs.com/package/gray-matter) just like [the remark transformer does](https://github.com/gatsbyjs/gatsby/blob/0d9f892e5df04e7c38e3ca8cc32946d35e5dfc0c/packages/gatsby-transformer-remark/src/on-node-create.js#L1). I can't think of a situation in which running the frontmatter package over file contents messes with mdx, so we should be able to just run it every time.

**Comment by ChristopherBiscardi** [comment]
released in 0.0.2

**Comment by avigoldman** [comment]
Looks like it doesn't quite work – it is adding the frontmatter code into the content.

https://gatsby-mdx-kitchen-sink.netlify.com/basic/

**Comment by ChristopherBiscardi** [comment]
Need to identify why that case is happening, it's definitely working on my blog, for example, which has frontmatter all over the place. Should file a different bug for it.
