### ISSUE TITLE
Page Support should be done through createPages

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#62]
**Describe the bug**
Currently we support src/pages by adding to the extensions, etc, but the "official" method is to overlay a createPages call instead.

**Comment by macklinu** [comment]
The process moving forward would look something like in [this doc](https://next.gatsbyjs.org/tutorial/part-seven/)?

**Comment by ChristopherBiscardi** [comment]
yes, but also I'm not entirely sure how this ends up looking. I believe that if we try to do the createPages/sourcing ourselves we can get rid of src/pages being run through the webpack loader, which will reduce the impact of issues like #90.

**Comment by ChristopherBiscardi** [comment]
Think I'm going to try to upstream some changes into the page creator plugin instead here. Basically, the page creator plugin should be sourcing the filesystem for change and we should be able to hook into it to create pages from the resulting nodes.

Either way, we need upstream support for adding plugins from plugins (ie: adding a source-filesystem from gatsby-mdx or a source-filesystem from page-creator)

**Comment by ChristopherBiscardi** [comment]
closing since this is mostly changes to other packages
