### ISSUE TITLE
Better errors for generated wrapper issues

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#63]
**Is your feature request related to a problem? Please describe.**

When a generated wrapper has an error, the error points to the generated wrapper rather than the user's wrapper. This makes it super weird when debugging a `pageQuery` that got hoisted into the wrapper.

```
GraphQL Error Unknown field `markdownRemark` on type `Query`

  file: /Users/chris/github/christopherbiscardi/gatsby-starter-blog-mdx/.cache/gatsby-mdx/mdx-wrappers-dir/948d44de256b74ce08daa27cfc231ecc--scope-hash-3010b3badc54a9dfa4a4c80e419a41b2.js

   1 |
   2 |   query BlogPostBySlug($slug: String!) {
   3 |     site {
   4 |       siteMetadata {
   5 |         title
   6 |         author
   7 |       }
   8 |     }
>  9 |     markdownRemark(fields: { slug: { eq: $slug } }) {
     |     ^
  10 |       id
  11 |       excerpt
  12 |       html
  13 |       frontmatter {
  14 |         title
  15 |         date(formatString: "MMMM DD, YYYY")
  16 |       }
  17 |     }
  18 |   }
  19 |
```

**Describe the solution you'd like**
We need to put some debug information into the generated wrapper to point someone to the user's page component if there's an error.

**Describe alternatives you've considered**
Is there a way to do this automatically?

**Comment by ChristopherBiscardi** [comment]
Closing as not important enough to fix right now. If people start finding it confusing we can come back and try to do something about it. 

For now, the overriding path for generating errors is "validate as early as possible"

**Comment by dceddia** [comment]
I ran into a related problem while trying to import a bunch of blog posts from a Jekyll site. There are formatting issues I need to fix, but the errors don't say which file caused them, so it's a game of grepping for unique-looking strings and hoping for the best 😅 

My hacky workaround was to wrap most of the code in `on-create-node.js` in a try/catch and prepend the filename to the error message:

```js
try {

  /**** Everything in this block is original to the file, no changes here ***/

  const mdxNode = await createMDXNode({
    id: createNodeId(`${node.id} >>> Mdx`),
    node,
    content
  });

  createNode(mdxNode);
  createParentChildLink({ parent: node, child: mdxNode });

  // write scope files into .cache for later consumption
  const { scopeImports, scopeIdentifiers } = await genMDX({
    node: mdxNode,
    getNode,
    getNodes,
    reporter,
    cache,
    pathPrefix,
    options
  });
  await cacheScope({
    scopeIdentifiers,
    scopeImports,
    createContentDigest: contentDigest,
    directory: store.getState().program.directory,
    parentNode: node
  });
} catch (e) {
  // Add the filename to the error and rethrow
  e.message = `in ${node.absolutePath} -- ${e.message}`;
  throw e;
}
```

I don't know much about Gatsby at this point so I'm sure there's a more proper way to do this, but it did help me track down the errors at least.

**Comment by ChristopherBiscardi** [comment]
@dceddia moved you here since this is a new bug report: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/273
