### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#66]
We should start to improve the `gatsby-mdx` documentation. We have a [gatsby-mdx.netlify.com](https://gatsby-mdx.netlify.com/) – the docs should live there.

### Content
Some initial thoughts on topics we should cover.

- [ ] Getting Started
	- [ ] Installing and Configuring MDX
	- [ ] Importing and using an MDX component
	- [ ] Creating an MDX page
- [ ] Creating MDX pages from GraphQL
	- [ ] Sourcing MDX from the filesystem
	- [ ] Sourcing MDX from remote sources
	- [ ] Creating MDX pages from GraphQL
- [ ] Using a Design System
- [ ] Contributing
	- [ ] Local setup
	- [ ] Where MDX lives in the Gatsby Lifecycle
	- [ ] Extending MDX

### Website

We should look at using [rebass](https://github.com/jxnblk/rebass), which is what the [MDX website](https://mdxjs.com/) uses.

Maybe we can through some Gatsby purple into it 😉

### Starter

We should have a Gatsby MDX starter ready to go with MDX pages created from GraphQL queries.

**Comment by ChristopherBiscardi** [comment]
Yeah, I suppose we should start splitting stuff out of the main readme, especially so we can use it on the docs site.

Love the idea of a contributing section in the main IA.

wydt about this as a top level information architecture:

* Getting Started (is a link to a getting started guide)
* Docs
  - Installation
  - Guides
    * Sourcing MDX Content from the Filesystem
    * Sourcing MDX Content from a CMS
    * Creating Pages (single mdx and multi-mdx)
    * Editing MDX on Contentful
    * Editing MDX in netlify-cms
    * Rendering MDX using Design System Components
    * Creating Interactive Code Blocks
  - API Reference
    * Plugin Configuration
    * GraphQL Schema
    * component-with-mdx-scope
    * mdx-renderer
  - Extensions
    * mdx-deck
* Contributing
  - Local setup
  - Where MDX lives in the Gatsby Lifecycle
  - Extending MDX
* Help
* Repl

##### repls

I like the idea of using a full repl for code examples at some point, maybe we can write a code components that uses \`\`\`repl-mdx as an indicator for an mdx repl. I also like the idea of having a playground somewhere. Maybe we should just kick people off to codesandbox at that point though and we can import the gatsby-mdx package into it.

![screen shot 2018-08-18 at 1 39 56 pm](https://user-images.githubusercontent.com/551247/44303077-3cc00980-a2ec-11e8-97f0-a2e79e078a9b.png)

**Comment by ChristopherBiscardi** [comment]
oh also, an Architectural Overview under the Contributing heading. I'll make some diagrams and stuff

**Comment by ChristopherBiscardi** [comment]
@macklinu dope, I've added you to the repo :) The docs themselves will live in the examples/docs location for now and we can always move it later. It deploys automatically to https://gatsby-mdx.netlify.com/ 

My plan is to scaffold out the graphql queries and such so we can just start writing .mdx files in that directory and then let people loose on the content and design, etc :)

**Comment by ChristopherBiscardi** [comment]
https://gatsby-mdx.netlify.com/ will now build any mdx file in the [content directory](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/master/examples/docs/content) at the relative path url.

I'm thinking the API reference should be a single `CMD+f`able page and the guides should be each their own pages. There's no styling and such yet, just focusing on getting the content up to par and maybe figuring out what we need in terms of repls etc.

**Comment by ChristopherBiscardi** [comment]
Re: that comment above, we should start splitting out the readme into docs site and point people there instead.

I'm thinking as we put stuff in docs we remove it from the core readme, instead leaving a brief description of the project and a link to the docs mdx files at first, and then a link to the docs site later when it's not horrible looking 😝

**Comment by ChristopherBiscardi** [comment]
Making full documentation a hard requirement for a 1.0 release (note: I have no idea when we'll do a 1.0, just declaring that docs are necessary for it)

**Comment by greggb** [comment]
@macklinu 
>What did you have in mind for that? EDIT: I could see a need for using an icon library in our docs based on the Notification component

Exactly what I had in mind.  Feather is perfect for this - I'll add that to the notification component.

You and Chris are waaaay faster at contributing than I am, so don't let me be a blocker for anything. All your choices are pretty much the way I would go as well. I write with Emotion exclusively now at work, so that's a huge 👍👍 .

**Comment by ChristopherBiscardi** [comment]
> @avigoldman @ChristopherBiscardi did you have thoughts on what the docs site would look like visually in terms of branding/colors/etc.?

No strong feels at this point. I think getting the site to a usable point from a UX perspective trumps any sort of visual work. At some point we'll want to do a pass and try to come up with good use cases, etc to put on the front page for marketing purposes, etc but for now I'm mostly concerned with the documentation content itself.

Vaguely, maybe something that combines the minimal-ness of the MDX logo with the purples of gatsby?

![image](https://user-images.githubusercontent.com/551247/44950540-33ac5d80-adff-11e8-9047-86acc2d05341.png)

<img width="934" alt="screen shot 2018-09-01 at 3 53 50 pm" src="https://user-images.githubusercontent.com/551247/44950543-445cd380-adff-11e8-93fe-da0569d2a0b7.png">

I think the typography, etc is going to be the most important here since we're marketing a markup format and people use markup formats for writing longform content.

**Comment by ChristopherBiscardi** [comment]
As far as fonts, it'd be cool to have a modern font-loading solution that pulls in [Inter UI](https://rsms.me/inter/) for the body/linear text content and maybe a system font stack for headings.

**Comment by greggb** [comment]
@avigoldman if you have a general direction for design I can build it out - I've been referencing the docs a bunch the last day or two and it would be great to get them to a more functional place.

**Comment by avigoldman** [comment]
@greggb #116 is in progress. Waiting on a little nav clean up from @ChristopherBiscardi.

You can reference the designed docs here: https://deploy-preview-116--gatsby-mdx.netlify.com/

**Comment by avigoldman** [comment]
The new design is live! 🎉 

There is definitely more docs work to do, but I'm going to close this issue in favor of creating more specific documentation issues.
