### ISSUE TITLE
componentWithMDXScope fails if there is no scope

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#67]
**Describe the bug**
`componentWithMDXScope` fails with an error if there isn't anything imported into an MDX file.

**To Reproduce**
Use `componentWithMDXScope` to create a page with a queried scope, but **don't** import anything into the MDX file.

You should see an error like this:
```
TypeError: Cannot read property 'map' of null

  - component-with-mdx-scope.js:29 componentWithMD    XScope
    [v6]/[gatsby-mdx]/component-with-mdx-scope.js:    29:41
```

**Comment by ChristopherBiscardi** [comment]
Please include a code snippet for createPage reproducing the error or a test project that displays the issue :) This is working in our kitchen sink example set.

- [basic mdx file](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/0cfdd608b39392fb39716cc0dcc1022024cd8c33/examples/kitchen-sink/content/non-page.mdx)
- [createPage call](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/0cfdd608b39392fb39716cc0dcc1022024cd8c33/examples/kitchen-sink/gatsby-node.js#L53-L67)
- [rendered page live](https://gatsby-mdx-kitchen-sink.netlify.com/posts/non-page)

**Comment by ChristopherBiscardi** [comment]
You have to use the `root: __dirname` gatsby-mdx plugin config option until we make a better way to find the project root.

```
options: {
  extensions: ['mdx'],
  root: __dirname
}
```
