### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#7]
# Desired Functionality

A user should be able to query MDX components in any directory that's sourced by [`gatsby-source-filesystem`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem/) plugin.

```graphql
{
  allMdx {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
}
```

**Comment by ChristopherBiscardi** [comment]
this happens now.
