### ISSUE TITLE
Error When Using Node 6.x

### ISSUE THREAD

**Issue by ryanwiemer** [ChristopherBiscardi/gatsby-mdx#73]
**Describe the bug**
I created a fresh install using the `gatsby-starter-default` making sure to use the `v2` branch. I followed the instructions via the setup process to install this plugin and the necessary dependencies. I also added the plugin to the `gatsby-config.js`

When I run `gatsby develop` I get an error (see screenshot below)

**To Reproduce**
1. Clone https://github.com/ryanwiemer/gatsby-mdx-test
2. Install dependencies
3. Run `gatsby develop`

**Screenshots**
<img width="742" alt="error" src="https://user-images.githubusercontent.com/5171579/44443861-d870a480-a58e-11e8-89af-696602af30bd.png">

**Additional context**
I tried running your [`kitchen-sink`](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/master/examples/kitchen-sink) example locally and I see the same error. 🤷Maybe I am missing something super obvious and if so I apologize.

**Comment by ChristopherBiscardi** [comment]
@ryanwiemer  What node version are you running?

**Comment by ryanwiemer** [comment]
Node - `v6.11.4`

I can upgrade Node to see if that resolves the issue.

**Comment by ChristopherBiscardi** [comment]
I believe you have to use [at least node version 8](https://node.green/#ES2017-features-async-functions) for async function support. The `engines` field can help us articulate support here, but when using npm it will only show as a warning and not error out. We could run a build to support node v6 if this is important to you and you can't upgrade for some reason, but I'm inclined to ask you to upgrade node to at least the latest active release (v8+) first.

![screen shot 2018-08-21 at 11 11 49 pm](https://user-images.githubusercontent.com/551247/44445930-ccd5ab80-a597-11e8-88d3-743178c3fa49.png)

**Comment by ryanwiemer** [comment]
Thanks for the help! No issues at all with upgrading. I will do that.

**Comment by ChristopherBiscardi** [comment]
cool, let us know if you're still running into trouble after upgrading :)

**Comment by ryanwiemer** [comment]
I have confirmed that upgrading Node to `v8.11.4` resolved the issue. Thanks again.
