### ISSUE TITLE
Passing props in code blocks to component

### ISSUE THREAD

**Issue by jeroenransijn** [ChristopherBiscardi/gatsby-mdx#76]
The following markdown spec mentions being able to use `props` (?) inside of code blocks: https://github.github.com/gfm/#indented-code-blocks. I am not sure if this would a issue we can fix within `gatsby-mdx`.

![image](https://user-images.githubusercontent.com/564463/44505269-4089be00-a655-11e8-8d5d-f32e1b376ea3.png)

**Comment by ChristopherBiscardi** [comment]
I really want this too. Will look into it to see if it's something we can enable here. My suspicion is that we'll have to PR to mdx itself to support it though.

**Comment by ChristopherBiscardi** [comment]
Looks like it's going to require this PR to get merged -- https://github.com/remarkjs/remark/pull/345 -- since mdx uses remark-parse, whose AST is mdast (and the mdast description PR [was merged](https://github.com/syntax-tree/mdast/pull/22)).

**Comment by ChristopherBiscardi** [comment]
Might be able to work around since apparently we could do the infostring splitting ourselves for now -- https://github.com/mdx-js/specification/issues/17#issuecomment-417070073

**Comment by ChristopherBiscardi** [comment]
we lose the inforstring in between mdPlugins and hastPlugins in mdx core: https://codesandbox.io/s/3y4wymyj75

I believe it's due to this line in mdast-util-tohast -- https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/handlers/code.js#L15

**Comment by ChristopherBiscardi** [comment]
We need this: https://github.com/syntax-tree/mdast-util-to-hast/issues/24

and then we should add handling to MDX core to turn the meta string into props

**Comment by ChristopherBiscardi** [comment]
Just waiting on an MDX core release now. Should be available in any `@mdx-js/mdx` version > 0.15.2 but I don't think there's anything left to do in gatsby-mdx so going to close this.
