### ISSUE TITLE
Error After Upgrade from 0.0.11 to 0.0.14 

### ISSUE THREAD

**Issue by ryanwiemer** [ChristopherBiscardi/gatsby-mdx#78]
**Describe the bug**
My test repo is failing to compile with an error in `./node_modules/gatsby-mdx/context.js`. In version `v0.0.11` of `gatsby-mdx` my code worked. 

**To Reproduce**
1. `git clone https://github.com/ryanwiemer/gatsby-mdx-test`
2. Run `gatsby develop`
3. See error

**Screenshots**
<img width="929" alt="error" src="https://user-images.githubusercontent.com/5171579/44559990-42f62180-a702-11e8-90a2-f68606548c18.png">

**Additional context**
I assume this is related to the changes you made to "remove requirement for manual __mdxScope handling". What is the proper syntax that I should be using when programmatically creating pages with a [page template](https://github.com/ryanwiemer/gatsby-mdx-test/blob/master/src/templates/post.js)?

`<MDXRenderer {...props}>{data.mdx.code.body}</MDXRenderer>`

**Comment by ChristopherBiscardi** [comment]
fixed in 0.0.15

**Comment by ChristopherBiscardi** [comment]
Thanks again for the awesome bug report. Made it super easy to find, fix, and make sure it fixed it.

To follow up with the proper syntax for a page template, you can now omit the `scope` prop entirely. `React`, `MDXTag`, and anything else you import should be passed through via context into the MDXRenderer itself.

The [current kitchen sink](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/9d794741b61ea1d65229f2967e9a6e8c0479bafd/examples/kitchen-sink/src/components/mdx-runtime-test.js#L23) example shows the basic usage but note that you don't need to pass `props` into the MDXRenderer if you aren't using any props in your MDX file or layouts.

**Comment by ryanwiemer** [comment]
@ChristopherBiscardi Thank you for the additional explanation on the proper syntax. I'm sure this will be clearer in the future as the docs get built out and the project matures. 

Thanks again!
