### ISSUE TITLE
Art Directed Content

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#79]
# What is Art Directed Content

It's the idea that the design is specifically created for the content of the article, like this (art-directed post on the right, default template on left).

![image](https://user-images.githubusercontent.com/551247/44606090-bcdce800-a7a0-11e8-8dfe-4a1c340dc465.png)

MDX and MDXProviders are uniquely suited to creating dynamic new experiences across different blog posts. We should document patterns for doing this (for example, nesting MDXProviders for specific posts and organizing custom components for one-off headers, etc).

#### More Links

- [automatically art directed responsive images](https://www.smashingmagazine.com/2016/02/automatically-art-directed-responsive-images-go/)
- [Art Direction for the Web: Designing standfirst paragraphs](https://stuffandnonsense.co.uk/blog/art-direction-for-the-web-designing-standfirst-paragraphs) via [twitter](https://twitter.com/Malarkey/status/1037864260897005568)

**Comment by KyleAMathews** [comment]
💜💜💜

**Comment by ChristopherBiscardi** [comment]
Standfirst paragraph examples from [Art Direction for the Web](https://stuffandnonsense.co.uk/blog/art-direction-for-the-web-designing-standfirst-paragraphs)

---

![standfirst paragraphs](https://user-images.githubusercontent.com/551247/45193131-64c2ce80-b201-11e8-8c53-5101fa3412d0.png)

---

![with a title](https://user-images.githubusercontent.com/551247/45193373-7d7fb400-b202-11e8-95c1-41d92eb838a2.png)

**Comment by ChristopherBiscardi** [comment]
oh also, the art-directed documentation should be art-directed

**Comment by ChristopherBiscardi** [comment]
Closing as we move toward migrating to the gatsby repo

This can turn into a cool starter if anyone wants to do it
