### ISSUE TITLE
Warnings from gatsby-plugin-filesystem when building pages from markdown in gatsby-node.js

### ISSUE THREAD

**Issue by craigmcginley** [ChristopherBiscardi/gatsby-mdx#83]
First off, thank you for putting together this plugin. It is exactly what I needed for a new project, and just in time!

**Describe the bug**
Following docs on this repo to build pages in gatsby-node.js, I am intermittently receiving a warning "It looks like you have a node that's set its parent as itself". It seems the warnings only trigger when running `gatsby develop` after having adjusted core gatsby files like gatsby-config.js. I've traced the warning to coming from gatsby-source-filesystem plugin, but I'm not sure why it is happening.

**To Reproduce**
I'm using gatsby v2, gatsby-source-filesystem@next.
The full package.json and setup can be found in this demo repo: https://github.com/craigmcginley/gatsby-mdx-warning

It should model your docs for creating pages in gatsby-node.js.

The first time running `gatsby develop`, you should see warnings in the output. Subsequent executions of `gatsby develop` will not display warnings again, unless you modify core gatsby files like gatsby-config.js (say, by adding a comment).

**Expected behavior**
Docs show method for building pages without warnings.

**Additional context**
Not sure if this is a result of using the plugin with Gatsby v2 or gatsby-source-filesystem@next.

**Comment by ChristopherBiscardi** [comment]
I'm 99% sure this is "our problem", not the filesystem source's. It doesn't currently affect plugin or site behavior but is something we need to fix (even if just so that we don't spam the console with warnings).

**Comment by ChristopherBiscardi** [comment]
published as 0.1.1
