### ISSUE TITLE
Move global context providers to wrapRootElement SSR API

### ISSUE THREAD

**Issue by macklinu** [ChristopherBiscardi/gatsby-mdx#88]
**Is your feature request related to a problem? Please describe.**

Breaking out this task from https://github.com/ChristopherBiscardi/gatsby-mdx/pull/86#issuecomment-416499889.

**Describe the solution you'd like**

Include the `ThemeProvider` and possibly the `MDXProvider` in the docs website to a `gatsby-ssr.js` config file similar to what's happening here:

https://github.com/ChristopherBiscardi/gatsby-mdx/blob/05f8eacf5b8f81e5ea521b672673c7762ae2786a/examples/kitchen-sink/gatsby-ssr.js#L8-L12

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ChristopherBiscardi** [comment]
I believe we'll need to do this in gatsby-browser as well

**Comment by ChristopherBiscardi** [comment]
done in new docs
