### ISSUE TITLE
Changing .mdx file does not result in live update in docs website

### ISSUE THREAD

**Issue by macklinu** [ChristopherBiscardi/gatsby-mdx#89]
**Describe the bug**

When developing the docs site and saving an `.mdx` file, the Gatsby site does not display the newly saved `.mdx` content in the browser.

**To Reproduce**

1. Run `yarn` to install dependencies.
2. Run `yarn workspace gatsby-mdx-docs develop` to start the Gatsby dev server for the `examples/docs` package.
3. Visit http://localhost:8000/docs/api-reference.
4. Change some content in `examples/docs/content/docs/api-reference.mdx` and save the file.

**Expected behavior**

The MDX content live updates in the browser.

**Screenshots**

N/A

**Additional context**

Changes to JavaScript files (like React components) are properly reflected in the browser, but not changes to `.mdx` files. Thoughts on what we might need to set up to get this working?

**Comment by ChristopherBiscardi** [comment]
hmmm, I don't know. Will have to investigate. We definitely want this from a UX perspective.

**Comment by greggb** [comment]
Ran into this as well. Changing a js file worked fine, but the MDX files required restarting the development task.

**Comment by ChristopherBiscardi** [comment]
My guess right now is that we need to write some hot-reload support into the webpack loader or something like that but I haven't done into this yet

**Comment by cdnil** [comment]
I came across this issue too.

**Comment by avigoldman** [comment]
Did some digging on this today. Seems like it doesn't update if you query for the MDX based on its ID. If you query for it by any other property or or as a child of a specific file node, this issue goes away.

**Comment by ChristopherBiscardi** [comment]
think this was fixed awhile ago. Happy to re-open if not
