### ISSUE TITLE
Error with gatsby-remark-images plugin

### ISSUE THREAD

**Issue by chasemccoy** [ChristopherBiscardi/gatsby-mdx#90]
**Describe the bug**
I am trying to use the `gatsby-remark-images` plugin with the latest version of `gatsby-mdx` and I am getting this error when running `gatsby develop`:

<img width="571" alt="screen shot 2018-08-29 at 10 42 06 am" src="https://user-images.githubusercontent.com/8663074/44798951-6bee3a80-ab78-11e8-8b7d-3744d2632365.png">

Here is the relevant portion of my `gatsby-config.js`:

```
{
      resolve: `gatsby-mdx`,
      options: {
        defaultLayouts: {
          docs: require.resolve('./src/templates/page.js')
        },
        gatsbyRemarkPlugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 1035,
              sizeByPixelDensity: true
            }
          },
          {
            resolve: "gatsby-remark-copy-linked-files",
            options: {
              ignoreFileExtensions: []
            }
          }
        ]
      }
    }
```

**Comment by ChristopherBiscardi** [comment]
@KyleAMathews we do the same `on-create-node`/`extend-node-type` dance as the remark transformer. The issue here is what happens if you `require('./thing.mdx')`, in which case it hits a webpack loader and not the gatsby pipeline so it's not really a node but is sourced from a fileNode. afaik this is new territory so I'm very open to pointers to other implementations of these concepts.

**Comment by ChristopherBiscardi** [comment]
we don't have to actually create the mdx node, but we do have to match the node structure that plugins expect to see (like having a parent field and other arbitrary requirements).

**Comment by KyleAMathews** [comment]
yeah — this is hard. I've always avoided trying to mix webpack & graphql as they're such different paradigms. Now that I understand what you're doing, this is probably the best you can do, recreate the graphql environment from within webpack.
